### ISSUE TITLE
null keys not supported

### ISSUE THREAD

**Issue by ricardojmendez** [cursive-ide/cursive#1154]
Cursive 0.1.69, IDEA 14.1.5.  Exception raised while attempting to create a project from existing sources using repository: https://github.com/ricardojmendez/lein-chromebuild

```
null keys not supported
java.lang.NullPointerException: null keys not supported
	at gnu.trove.THashMap.put(THashMap.java:162)
	at com.intellij.util.indexing.ValueContainerImpl.a(ValueContainerImpl.java:71)
	at com.intellij.util.indexing.ValueContainerImpl.addValue(ValueContainerImpl.java:62)
	at com.intellij.util.indexing.ValueContainerImpl.readFrom(ValueContainerImpl.java:553)
	at com.intellij.util.indexing.ValueContainerMap$ValueContainerExternalizer.read(ValueContainerMap.java:95)
	at com.intellij.util.indexing.ValueContainerMap$ValueContainerExternalizer.read(ValueContainerMap.java:78)
	at com.intellij.util.io.PersistentHashMap.doGet(PersistentHashMap.java:522)
	at com.intellij.util.io.PersistentHashMap.get(PersistentHashMap.java:455)
	at com.intellij.util.indexing.MapIndexStorage$2$1.compute(MapIndexStorage.java:118)
	at com.intellij.util.indexing.MapIndexStorage$2$1.compute(MapIndexStorage.java:106)
	at com.intellij.util.indexing.ChangeTrackingValueContainer.a(ChangeTrackingValueContainer.java:121)
	at com.intellij.util.indexing.ChangeTrackingValueContainer.getValueIterator(ChangeTrackingValueContainer.java:82)
	at com.intellij.util.indexing.FileBasedIndexImpl$14.convert(FileBasedIndexImpl.java:973)
	at com.intellij.util.indexing.FileBasedIndexImpl$14.convert(FileBasedIndexImpl.java:948)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:921)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:994)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValues(FileBasedIndexImpl.java:902)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValues(FileBasedIndexImpl.java:892)
	at cursive.index.js$root_object_map_by_name.invoke(js.clj:222)
	at cursive.index.js$all_properties$fn__3960.invoke(js.clj:258)
	at clojure.core$map$fn__4553.invoke(core.clj:2624)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:674)
	at clojure.core$next__4112.invoke(core.clj:64)
	at clojure.core.protocols$fn__6523.invoke(protocols.clj:170)
	at clojure.core.protocols$fn__6478$G__6473__6487.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31)
	at clojure.core.protocols$fn__6506.invoke(protocols.clj:101)
	at clojure.core.protocols$fn__6452$G__6447__6465.invoke(protocols.clj:13)
	at clojure.core$reduce.invoke(core.clj:6519)
	at cursive.index.js$all_properties.invoke(js.clj:256)
	at cursive.resolve.symbol.editor.cljs$all_properties$fn__5482.invoke(cljs.clj:89)
	at cursive.psi$cached_value$reify__12543.compute(psi.clj:497)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:200)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:83)
	at cursive.psi$cached_value.doInvoke(psi.clj:500)
	at clojure.lang.RestFn.invoke(RestFn.java:525)
	at cursive.resolve.symbol.editor.cljs$all_properties.invoke(cljs.clj:86)
	at cursive.resolve.symbol.editor.cljs$resolve_js_element.invoke(cljs.clj:149)
	at cursive.resolve.symbol.editor.cljs$editor_resolver$reify__5616.resolve_unqualified(cljs.clj:312)
	at cursive.resolve.symbol$resolve_normal_symbol.invoke(symbol.clj:74)
	at cursive.resolve.symbol$resolve_symbol.invoke(symbol.clj:100)
	at clojure.lang.Var.invoke(Var.java:383)
	at cursive.psi.impl.symbols.SymbolReference$SymbolResolver.resolve(SymbolReference.java:67)
	at cursive.psi.impl.symbols.SymbolReference$SymbolResolver.resolve(SymbolReference.java:64)
	at com.intellij.psi.impl.source.resolve.ResolveCache.a(ResolveCache.java:139)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:159)
	at cursive.psi.impl.symbols.SymbolReference.multipleResolveResults(SymbolReference.java:90)
	at cursive.psi.impl.symbols.SymbolReference.isReferenceTo(SymbolReference.java:150)
	at com.intellij.psi.search.SingleTargetRequestResultProcessor.processTextOccurrence(SingleTargetRequestResultProcessor.java:50)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$14.execute(PsiSearchHelperImpl.java:739)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.a(LowLevelSearchUtil.java:129)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.access$000(LowLevelSearchUtil.java:42)
	at com.intellij.psi.impl.search.LowLevelSearchUtil$1.execute(LowLevelSearchUtil.java:199)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processTextOccurrences(LowLevelSearchUtil.java:242)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processElementsContainingWordInElement(LowLevelSearchUtil.java:195)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2$1.compute(PsiSearchHelperImpl.java:211)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2$1.compute(PsiSearchHelperImpl.java:208)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:884)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.process(PsiSearchHelperImpl.java:208)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.process(PsiSearchHelperImpl.java:205)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$13.process(PsiSearchHelperImpl.java:703)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$13.process(PsiSearchHelperImpl.java:697)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$5.compute(PsiSearchHelperImpl.java:366)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$5.compute(PsiSearchHelperImpl.java:348)
	at com.intellij.openapi.application.ex.ApplicationUtil$1.run(ApplicationUtil.java:37)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
	at com.intellij.openapi.application.ex.ApplicationUtil.tryRunReadAction(ApplicationUtil.java:34)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.a(PsiSearchHelperImpl.java:348)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.access$000(PsiSearchHelperImpl.java:67)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$3.process(PsiSearchHelperImpl.java:295)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$3.process(PsiSearchHelperImpl.java:290)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:122)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
```

**Comment by cursiveclojure** [comment]
I just tried to reproduce this and I can't - does *File->Invalidate caches and restart* help with this?

**Comment by ulsa** [comment]
I just ran into this with 1.3.0-eap1-15. Tried invalidate cache and restart, but it keeps indexing until I disable Cursive.

```
2016-05-29 22:00:13,110 [  83167]   INFO - il.indexing.FileBasedIndexImpl - scheduleIndexRebuild, reason: checkRebuild 
2016-05-29 22:00:13,195 [  83252]   INFO - .diagnostic.PerformanceWatcher - Pushing properties took 1ms; general responsiveness: o
k; EDT responsiveness: ok 
2016-05-29 22:00:14,687 [  84744]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 1492ms; general responsi
veness: ok; EDT responsiveness: ok 
2016-05-29 22:00:14,687 [  84744]   INFO - indexing.UnindexedFilesUpdater - Unindexed files update started: 29 files to update 
2016-05-29 22:00:14,701 [  84758]   INFO - .diagnostic.PerformanceWatcher - Unindexed files update took 14ms; general responsivene
ss: ok; EDT responsiveness: ok 
2016-05-29 22:00:15,468 [  85525]   INFO - ellij.project.impl.ProjectImpl - 25 project components initialized in 62 ms 
2016-05-29 22:00:15,468 [  85525]   INFO - le.impl.ModuleManagerComponent - 0 module(s) loaded in 0 ms 
2016-05-29 22:00:15,712 [  85769]   INFO - .diagnostic.PerformanceWatcher - Unindexed files update took 3463ms; general responsive
ness: ok; EDT responsiveness: ok 
2016-05-29 22:00:15,782 [  85839]   INFO - .diagnostic.PerformanceWatcher - Pushing properties took 70ms; general responsiveness: 
ok; EDT responsiveness: ok 
2016-05-29 22:00:16,667 [  86724]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 885ms; general responsiv
eness: ok; EDT responsiveness: ok 
2016-05-29 22:00:16,668 [  86725]   INFO - indexing.UnindexedFilesUpdater - Unindexed files update started: 1625 files to update 
2016-05-29 22:00:17,174 [  87231]   INFO - j.util.indexing.MapReduceIndex - Exception during updateWithMap:com.intellij.util.index
ing.StorageException: java.lang.NullPointerException: null keys not supported 
2016-05-29 22:00:17,213 [  87270]   INFO - il.indexing.FileBasedIndexImpl - Rebuild requested for index ClojureJavascript 
com.intellij.util.indexing.StorageException: java.lang.NullPointerException: null keys not supported
        at com.intellij.util.indexing.MapReduceIndex.updateWithMap(MapReduceIndex.java:756)
...
Caused by: java.lang.NullPointerException: null keys not supported
        at gnu.trove.THashMap.put(THashMap.java:161)
...
2016-05-29 22:00:17,244 [  87301]   INFO - .diagnostic.PerformanceWatcher - Unindexed files update took 576ms; general responsiveness: ok; EDT responsiveness: ok 
2016-05-29 22:00:17,325 [  87382]   INFO - il.indexing.FileBasedIndexImpl - scheduleIndexRebuild, reason: checkRebuild 
...
```

and so on.

**Comment by cursive-ide** [comment]
@ulsa Can you get your logs from *Help->Show logs in Finder/Explorer* and either attach them here, or send them via email?

**Comment by nicity** [comment]
it looks like a problem in IntelliJ IDEA, to avoid the problem one needs to have not null "values" returned from indexer of your index

**Comment by cursive-ide** [comment]
Thanks @nicity, I'll try to figure out how that is happening. In this error message, it would be very useful to see which file the error happens on - if it's in a file from an OSS repo, I can then reproduce it easily.
