### ISSUE TITLE
Hang with 100% CPU

### ISSUE THREAD

**Issue by pmoriarty** [cursive-ide/cursive#1210]
Tried to navigate to a recent file and the whole IDE hung.

[threadDump-20160108-160627.txt](https://github.com/cursive-ide/cursive/files/82909/threadDump-20160108-160627.txt)
[threadDump-20160108-160522.txt](https://github.com/cursive-ide/cursive/files/82908/threadDump-20160108-160522.txt)

Seeing lots of this in the idea.log but nothing else:
2016-01-08 16:01:16,593 [25546143]   INFO - .diagnostic.PerformanceWatcher - High memory usage (free 70 of 626 MB) while dumping threads to /Users/pmoriarty/Library/Logs/IntelliJIdea15/threadDumps-20160108-085539-IU-143.1184/20160108-160116/threadDump-20160108-160116.txt 

Restarted and now the IDE freezes on startup and starts spewing similar thread dumps again:
[threadDump-20160108-161043.txt](https://github.com/cursive-ide/cursive/files/82925/threadDump-20160108-161043.txt)

This seems to be a common theme:

```
"AWT-EventQueue-0 15.0.2#IU-143.1184.17, eap:false" prio=0 tid=0x0 nid=0x0 runnable
     java.lang.Thread.State: RUNNABLE
    at cursive.resolve$light_keys.invoke(resolve.clj:164)
    at cursive.resolve$resolve_keys.invoke(resolve.clj:179)
    at cursive.formatting$list_block_params.invoke(formatting.clj:223)
    at cursive.formatting$basic_block_params.invoke(formatting.clj:304)
    at cursive.formatting$sub_blocks.invoke(formatting.clj:314)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.core$apply.invoke(core.clj:630)
    at clojure.core$memoize$fn__5479.doInvoke(core.clj:6082)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at cursive.formatting.ElementBlock.getSubBlocks(formatting.clj:34)
    at com.intellij.psi.formatter.common.NewLineBlocksIterator.a(NewLineBlocksIterator.java:115)
```

IDEA 15.0.2
Cursive 1.1.0
OS X 10.11.2

**Comment by pmoriarty** [comment]
Cleared caches and restarted => same problem
Had to delete IDEA project and module files to resolve.

**Comment by cursive-ide** [comment]
Sorry for the delay in looking at this. This appears to be a deadlock with the indent detection functionality. Could you (or @levand) try disabling this at *Settings&rarr;Editor&rarr;Code Style&rarr;Indents detection* to see if that helps?

**Comment by levand** [comment]
@cursive-ide Will do, next time it starts happening again (which is likely to be soon... had to rebuild my project twice today already)

**Comment by levand** [comment]
@cursive-ide I can confirm that disabling "Detect and use existing file indents for editing" solves at least my instance of the problem. My application loads fine, now. 

Thank you! This workaround will be fine until you get around to fixing the bug itself.

**Comment by thevermeer** [comment]
I can confirm the same result
OSX 10.10.4 (14E46)
IntelliJ 15.0.2
cursive 1.1.0-15

**Comment by favila** [comment]
I ran into this where I never did before.

Ubuntu 15.10
Intellij 2016.1
Cursive 1.2.4 and 1.2.5

My threaddump looked similar (mentioned light-keys and resolve-keys).

Same workaround (disabling "Detect and use existing file indents") worked for me.

I guess I must have edited a file's indents in just the wrong way that it triggered this?

**Comment by 42alex** [comment]
disabling "Detect and use existing file indents" did not work for me.
i cleared all caches. 
What's the problem here?
[threadDump-20160628-175621.txt](https://github.com/cursive-ide/cursive/files/337464/threadDump-20160628-175621.txt)
