### ISSUE TITLE
IndexOutOfBoundsException - prevents some code navigation

### ISSUE THREAD

**Issue by martinraison** [cursive-ide/cursive#1257]
I get the stack trace below when opening one of my projects. I tried recreating the intellij project from scratch but it didn't help.

    chars sequence.length:256, start:433, end:1015
    java.lang.IndexOutOfBoundsException: chars sequence.length:256, start:433, end:1015
        at com.intellij.util.text.CharSequenceSubSequence.<init>(CharSequenceSubSequence.java:34)
        at com.intellij.util.text.ImmutableText.subSequence(ImmutableText.java:229)
        at com.intellij.openapi.editor.impl.DocumentImpl$5.compute(DocumentImpl.java:796)
        at com.intellij.openapi.editor.impl.DocumentImpl$5.compute(DocumentImpl.java:793)
        at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:963)
        at com.intellij.openapi.editor.impl.DocumentImpl.getText(DocumentImpl.java:793)
        at cursive.intellij.class$create_class.invoke(class.clj:187)
        at clojure.lang.Var.invoke(Var.java:383)
        at cursive.psi.impl.javaView.ClojureClassFinder$1$1.createValue(ClojureClassFinder.java:58)
        at cursive.psi.impl.javaView.ClojureClassFinder$1$1.createValue(ClojureClassFinder.java:54)
        at com.intellij.util.containers.SLRUCache.get(SLRUCache.java:46)
        at cursive.psi.impl.javaView.ClojureClassFinder.createClass(ClojureClassFinder.java:85)
        at cursive.intellij.class$classes_by_fqn$fn__6499.invoke(class.clj:270)
        at clojure.core$mapv$fn__6727.invoke(core.clj:6616)
        at clojure.lang.PersistentVector.reduce(PersistentVector.java:333)
        at clojure.core$reduce.invoke(core.clj:6518)
        at clojure.core$mapv.invoke(core.clj:6616)
        at cursive.intellij.class$classes_by_fqn.invoke(class.clj:270)
        at clojure.lang.Var.invoke(Var.java:388)
        at cursive.psi.impl.javaView.ClojureClassFinder.findClasses(ClojureClassFinder.java:78)
        at com.intellij.psi.impl.JavaPsiFacadeImpl.findClasses(JavaPsiFacadeImpl.java:166)
        at cursive.index.ClojureShortNamesCache.getClassesByName(ClojureShortNamesCache.java:43)
        at com.intellij.psi.impl.CompositeShortNamesCache.getClassesByName(CompositeShortNamesCache.java:77)
        at cursive.indexes.java$classes_by_short_name.invoke(java.clj:42)
        at cursive.annotator$annotate_class_import.invoke(annotator.clj:137)
        at cursive.annotator$annotate_import_require.invoke(annotator.clj:264)
        at cursive.annotator$annotate_unresolved.invoke(annotator.clj:267)
        at cursive.annotator$annotate_symbol.invoke(annotator.clj:355)
        at cursive.annotator$fn__6040.invoke(annotator.clj:384)
        at cursive.annotator$fn__6025$G__6020__6032.invoke(annotator.clj:375)
        at cursive.annotator.ClojureAnnotator.annotate(annotator.clj:399)
        at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:162)
        at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:103)
        at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:354)
        at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$100(GeneralHighlightingPass.java:65)
        at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$3.run(GeneralHighlightingPass.java:283)
        at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:308)
        at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$200(GeneralHighlightingPass.java:65)
        at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$4.run(GeneralHighlightingPass.java:314)
        at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:87)
        at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:311)
        at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:280)
        at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:219)
        at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
        at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
        at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
        at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1177)
        at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
        at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:432)
        at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
        at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
        at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
        at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
        at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
        at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)

    java.lang.IndexOutOfBoundsException: chars sequence.length:256, start:433, end:1015
        at com.intellij.util.text.CharSequenceSubSequence.<init>(CharSequenceSubSequence.java:34)
        at com.intellij.util.text.ImmutableText.subSequence(ImmutableText.java:229)
        at com.intellij.openapi.editor.impl.DocumentImpl$5.compute(DocumentImpl.java:796)
        at com.intellij.openapi.editor.impl.DocumentImpl$5.compute(DocumentImpl.java:793)
        at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:963)
        at com.intellij.openapi.editor.impl.DocumentImpl.getText(DocumentImpl.java:793)
        at cursive.intellij.class$create_class.invoke(class.clj:187)
        at clojure.lang.Var.invoke(Var.java:383)
        at cursive.psi.impl.javaView.ClojureClassFinder$1$1.createValue(ClojureClassFinder.java:58)
        at cursive.psi.impl.javaView.ClojureClassFinder$1$1.createValue(ClojureClassFinder.java:54)
        at com.intellij.util.containers.SLRUCache.get(SLRUCache.java:46)
        at cursive.psi.impl.javaView.ClojureClassFinder.createClass(ClojureClassFinder.java:85)
        at cursive.intellij.class$classes_by_fqn$fn__6499.invoke(class.clj:270)
        at clojure.core$mapv$fn__6727.invoke(core.clj:6616)
        at clojure.lang.PersistentVector.reduce(PersistentVector.java:333)
        at clojure.core$reduce.invoke(core.clj:6518)
        at clojure.core$mapv.invoke(core.clj:6616)
        at cursive.intellij.class$classes_by_fqn.invoke(class.clj:270)
        at clojure.lang.Var.invoke(Var.java:388)
        at cursive.psi.impl.javaView.ClojureClassFinder.findClasses(ClojureClassFinder.java:78)
        at com.intellij.psi.impl.JavaPsiFacadeImpl.findClasses(JavaPsiFacadeImpl.java:166)
        at cursive.index.ClojureShortNamesCache.getClassesByName(ClojureShortNamesCache.java:43)
        at com.intellij.psi.impl.CompositeShortNamesCache.getClassesByName(CompositeShortNamesCache.java:77)
        at cursive.indexes.java$classes_by_short_name.invoke(java.clj:42)
        at cursive.annotator$annotate_class_import.invoke(annotator.clj:137)
        at cursive.annotator$annotate_import_require.invoke(annotator.clj:264)
        at cursive.annotator$annotate_unresolved.invoke(annotator.clj:267)
        at cursive.annotator$annotate_java_interop.invoke(annotator.clj:332)
        at cursive.annotator$annotate_symbol.invoke(annotator.clj:350)
        at cursive.annotator$fn__6040.invoke(annotator.clj:384)
        at cursive.annotator$fn__6025$G__6020__6032.invoke(annotator.clj:375)
        at cursive.annotator.ClojureAnnotator.annotate(annotator.clj:399)
        at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:162)
        at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:103)
        at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:354)
        at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$100(GeneralHighlightingPass.java:65)
        at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$3.run(GeneralHighlightingPass.java:288)
        at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:308)
        at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$200(GeneralHighlightingPass.java:65)
        at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$4.run(GeneralHighlightingPass.java:314)
        at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:87)
        at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:311)
        at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:280)
        at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:219)
        at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
        at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
        at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
        at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1177)
        at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
        at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:432)
        at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
        at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
        at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
        at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
        at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
        at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)

**Comment by martinraison** [comment]
just reported that issue via the plugin directly - I think I can close this
