### ISSUE TITLE
Locks up on CLJC expression involving #?@ [do]

### ISSUE THREAD

**Issue by mfikes** [cursive-ide/cursive#1296]
Put the following into a CLJC file in Cursive and it will exhibit a StackOverFlowError and lock-ups:

```
(defn foo []
  (#?@(:cljs [do])))
```

The error (truncated by me to get it to fit into the issue—otherwise GitHub won't allow it to be submitted):

```
null
java.lang.StackOverflowError
    at com.intellij.util.indexing.FileBasedIndexImpl.processExceptions(FileBasedIndexImpl.java:940)
    at com.intellij.util.indexing.FileBasedIndexImpl.processValuesImpl(FileBasedIndexImpl.java:1010)
    at com.intellij.util.indexing.FileBasedIndexImpl.processValues(FileBasedIndexImpl.java:918)
    at com.intellij.util.indexing.FileBasedIndexImpl.processValues(FileBasedIndexImpl.java:908)
    at cursive.index$var_meta_by_fqn.invoke(index.clj:249)
    at cursive.symbol$var_meta.invoke(symbol.clj:53)
    at cursive.resolve.symbol$resolve_symbol.invoke(symbol.clj:88)
    at clojure.lang.Var.invoke(Var.java:383)
    at cursive.psi.impl.symbols.SymbolReference$SymbolResolver.resolve(SymbolReference.java:67)
    at cursive.psi.impl.symbols.SymbolReference$SymbolResolver.resolve(SymbolReference.java:64)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:144)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:159)
    at cursive.psi.impl.symbols.SymbolReference.multiResolve(SymbolReference.java:58)
    at cursive.resolve$resolve.invoke(resolve.clj:55)
    at cursive.resolve$resolve_keys.invoke(resolve.clj:183)
    at cursive.resolve.lists$process_list_declarations.invoke(lists.clj:16)
    at cursive.resolve.symbol.editor.cljs$editor_resolver$reify__5680$fn__5711.invoke(cljs.clj:316)
    at clojure.core$some.invoke(core.clj:2570)
    at cursive.resolve.symbol.editor.cljs$editor_resolver$reify__5680.resolve_unqualified(cljs.clj:316)
    at cursive.resolve.symbol$resolve_normal_symbol.invoke(symbol.clj:74)
    at cursive.resolve.symbol$resolve_symbol.invoke(symbol.clj:100)
    at clojure.lang.Var.invoke(Var.java:383)
    at cursive.psi.impl.symbols.SymbolReference$SymbolResolver.resolve(SymbolReference.java:67)
    at cursive.psi.impl.symbols.SymbolReference$SymbolResolver.resolve(SymbolReference.java:64)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:144)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:159)
    at cursive.psi.impl.symbols.SymbolReference.multiResolve(SymbolReference.java:58)
    at cursive.resolve$resolve.invoke(resolve.clj:55)
    at cursive.resolve$resolve_keys.invoke(resolve.clj:183)
    at cursive.resolve.lists$process_list_declarations.invoke(lists.clj:16)
    at cursive.resolve.symbol.editor.cljs$editor_resolver$reify__5680$fn__5711.invoke(cljs.clj:316)
    at clojure.core$some.invoke(core.clj:2570)
    at cursive.resolve.symbol.editor.cljs$editor_resolver$reify__5680.resolve_unqualified(cljs.clj:316)
    at cursive.resolve.symbol$resolve_normal_symbol.invoke(symbol.clj:74)
    at cursive.resolve.symbol$resolve_symbol.invoke(symbol.clj:100)
    at clojure.lang.Var.invoke(Var.java:383)
    at cursive.psi.impl.symbols.SymbolReference$SymbolResolver.resolve(SymbolReference.java:67)
    at cursive.psi.impl.symbols.SymbolReference$SymbolResolver.resolve(SymbolReference.java:64)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:144)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:159)
    at cursive.psi.impl.symbols.SymbolReference.multiResolve(SymbolReference.java:58)
    at cursive.resolve$resolve.invoke(resolve.clj:55)
    at cursive.resolve$resolve_keys.invoke(resolve.clj:183)
    at cursive.resolve.lists$process_list_declarations.invoke(lists.clj:16)
    at cursive.resolve.symbol.editor.cljs$editor_resolver$reify__5680$fn__5711.invoke(cljs.clj:316)
    at clojure.core$some.invoke(core.clj:2570)
    at cursive.resolve.symbol.editor.cljs$editor_resolver$reify__5680.resolve_unqualified(cljs.clj:316)
    at cursive.resolve.symbol$resolve_normal_symbol.invoke(symbol.clj:74)
    at cursive.resolve.symbol$resolve_symbol.invoke(symbol.clj:100)
    at clojure.lang.Var.invoke(Var.java:383)
    at cursive.psi.impl.symbols.SymbolReference$SymbolResolver.resolve(SymbolReference.java:67)
    at cursive.psi.impl.symbols.SymbolReference$SymbolResolver.resolve(SymbolReference.java:64)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:144)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:159)
    at cursive.psi.impl.symbols.SymbolReference.multiResolve(SymbolReference.java:58)
    at cursive.resolve$resolve.invoke(resolve.clj:55)
    at cursive.resolve$resolve_keys.invoke(resolve.clj:183)
    at cursive.resolve.lists$process_list_declarations.invoke(lists.clj:16)
    at cursive.resolve.symbol.editor.cljs$editor_resolver$reify__5680$fn__5711.invoke(cljs.clj:316)
    at clojure.core$some.invoke(core.clj:2570)
    at cursive.resolve.symbol.editor.cljs$editor_resolver$reify__5680.resolve_unqualified(cljs.clj:316)
    at cursive.resolve.symbol$resolve_normal_symbol.invoke(symbol.clj:74)
    at cursive.resolve.symbol$resolve_symbol.invoke(symbol.clj:100)
    at clojure.lang.Var.invoke(Var.java:383)
    at cursive.psi.impl.symbols.SymbolReference$SymbolResolver.resolve(SymbolReference.java:67)
    at cursive.psi.impl.symbols.SymbolReference$SymbolResolver.resolve(SymbolReference.java:64)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:144)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:159)
    at cursive.psi.impl.symbols.SymbolReference.multiResolve(SymbolReference.java:58)
    at cursive.resolve$resolve.invoke(resolve.clj:55)
    at cursive.resolve$resolve_keys.invoke(resolve.clj:183)
    at cursive.resolve.lists$process_list_declarations.invoke(lists.clj:16)
    at cursive.resolve.symbol.editor.cljs$editor_resolver$reify__5680$fn__5711.invoke(cljs.clj:316)
    at clojure.core$some.invoke(core.clj:2570)
    at cursive.resolve.symbol.editor.cljs$editor_resolver$reify__5680.resolve_unqualified(cljs.clj:316)
    at cursive.resolve.symbol$resolve_normal_symbol.invoke(symbol.clj:74)
    at cursive.resolve.symbol$resolve_symbol.invoke(symbol.clj:100)
    at clojure.lang.Var.invoke(Var.java:383)
    at cursive.psi.impl.symbols.SymbolReference$SymbolResolver.resolve(SymbolReference.java:67)
    at cursive.psi.impl.symbols.SymbolReference$SymbolResolver.resolve(SymbolReference.java:64)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:144)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:159)
    at cursive.psi.impl.symbols.SymbolReference.multiResolve(SymbolReference.java:58)
    at cursive.resolve$resolve.invoke(resolve.clj:55)
    at cursive.resolve$resolve_keys.invoke(resolve.clj:183)
    at cursive.resolve.lists$process_list_declarations.invoke(lists.clj:16)
    at cursive.resolve.symbol.editor.cljs$editor_resolver$reify__5680$fn__5711.invoke(cljs.clj:316)
    at clojure.core$some.invoke(core.clj:2570)
    at cursive.resolve.symbol.editor.cljs$editor_resolver$reify__5680.resolve_unqualified(cljs.clj:316)
    at cursive.resolve.symbol$resolve_normal_symbol.invoke(symbol.clj:74)
    at cursive.resolve.symbol$resolve_symbol.invoke(symbol.clj:100)
    at clojure.lang.Var.invoke(Var.java:383)
    at cursive.psi.impl.symbols.SymbolReference$SymbolResolver.resolve(SymbolReference.java:67)
    at cursive.psi.impl.symbols.SymbolReference$SymbolResolver.resolve(SymbolReference.java:64)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:144)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:159)
    at cursive.psi.impl.symbols.SymbolReference.multiResolve(SymbolReference.java:58)
    at cursive.resolve$resolve.invoke(resolve.clj:55)
    at cursive.resolve$resolve_keys.invoke(resolve.clj:183)
    at cursive.resolve.lists$process_list_declarations.invoke(lists.clj:16)
    at cursive.resolve.symbol.editor.cljs$editor_resolver$reify__5680$fn__5711.invoke(cljs.clj:316)
    at clojure.core$some.invoke(core.clj:2570)
    at cursive.resolve.symbol.editor.cljs$editor_resolver$reify__5680.resolve_unqualified(cljs.clj:316)
    at cursive.resolve.symbol$resolve_normal_symbol.invoke(symbol.clj:74)
    at cursive.resolve.symbol$resolve_symbol.invoke(symbol.clj:100)
    at clojure.lang.Var.invoke(Var.java:383)
    at cursive.psi.impl.symbols.SymbolReference$SymbolResolver.resolve(SymbolReference.java:67)
    at cursive.psi.impl.symbols.SymbolReference$SymbolResolver.resolve(SymbolReference.java:64)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:144)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:159)
    at cursive.psi.impl.symbols.SymbolReference.multiResolve(SymbolReference.java:58)
    at cursive.resolve$resolve.invoke(resolve.clj:55)
    at cursive.resolve$resolve_keys.invoke(resolve.clj:183)
    at cursive.resolve.lists$process_list_declarations.invoke(lists.clj:16)
    at cursive.resolve.symbol.editor.cljs$editor_resolver$reify__5680$fn__5711.invoke(cljs.clj:316)
    at clojure.core$some.invoke(core.clj:2570)
    at cursive.resolve.symbol.editor.cljs$editor_resolver$reify__5680.resolve_unqualified(cljs.clj:316)
    at cursive.resolve.symbol$resolve_normal_symbol.invoke(symbol.clj:74)
    at cursive.resolve.symbol$resolve_symbol.invoke(symbol.clj:100)
    at clojure.lang.Var.invoke(Var.java:383)
    at cursive.psi.impl.symbols.SymbolReference$SymbolResolver.resolve(SymbolReference.java:67)
    at cursive.psi.impl.symbols.SymbolReference$SymbolResolver.resolve(SymbolReference.java:64)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:144)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:159)
    at cursive.psi.impl.symbols.SymbolReference.multiResolve(SymbolReference.java:58)
    at cursive.resolve$resolve.invoke(resolve.clj:55)
    at cursive.resolve$resolve_keys.invoke(resolve.clj:183)
    at cursive.resolve.lists$process_list_declarations.invoke(lists.clj:16)
    at cursive.resolve.symbol.editor.cljs$editor_resolver$reify__5680$fn__5711.invoke(cljs.clj:316)
    at clojure.core$some.invoke(core.clj:2570)
    at cursive.resolve.symbol.editor.cljs$editor_resolver$reify__5680.resolve_unqualified(cljs.clj:316)
    at cursive.resolve.symbol$resolve_normal_symbol.invoke(symbol.clj:74)
    at cursive.resolve.symbol$resolve_symbol.invoke(symbol.clj:100)
    at clojure.lang.Var.invoke(Var.java:383)
    at cursive.psi.impl.symbols.SymbolReference$SymbolResolver.resolve(SymbolReference.java:67)
    at cursive.psi.impl.symbols.SymbolReference$SymbolResolver.resolve(SymbolReference.java:64)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:144)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:159)
    at cursive.psi.impl.symbols.SymbolReference.multiResolve(SymbolReference.java:58)
    at cursive.resolve$resolve.invoke(resolve.clj:55)
    at cursive.resolve$resolve_keys.invoke(resolve.clj:183)
    at cursive.resolve.lists$process_list_declarations.invoke(lists.clj:16)
    at cursive.resolve.symbol.editor.cljs$editor_resolver$reify__5680$fn__5711.invoke(cljs.clj:316)
    at clojure.core$some.invoke(core.clj:2570)
    at cursive.resolve.symbol.editor.cljs$editor_resolver$reify__5680.resolve_unqualified(cljs.clj:316)
    at cursive.resolve.symbol$resolve_normal_symbol.invoke(symbol.clj:74)
    at cursive.resolve.symbol$resolve_symbol.invoke(symbol.clj:100)
    at clojure.lang.Var.invoke(Var.java:383)
    at cursive.psi.impl.symbols.SymbolReference$SymbolResolver.resolve(SymbolReference.java:67)
    at cursive.psi.impl.symbols.SymbolReference$SymbolResolver.resolve(SymbolReference.java:64)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:144)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:159)
    at cursive.psi.impl.symbols.SymbolReference.multiResolve(SymbolReference.java:58)
    at cursive.resolve$resolve.invoke(resolve.clj:55)
    at cursive.resolve$resolve_keys.invoke(resolve.clj:183)
    at cursive.resolve.lists$process_list_declarations.invoke(lists.clj:16)
    at cursive.resolve.symbol.editor.cljs$editor_resolver$reify__5680$fn__5711.invoke(cljs.clj:316)
    at clojure.core$some.invoke(core.clj:2570)
    at cursive.resolve.symbol.editor.cljs$editor_resolver$reify__5680.resolve_unqualified(cljs.clj:316)
    at cursive.resolve.symbol$resolve_normal_symbol.invoke(symbol.clj:74)
    at cursive.resolve.symbol$resolve_symbol.invoke(symbol.clj:100)
    ...
```

**Comment by cursive-ide** [comment]
This has been fixed for the next build, it was the root cause of #1554.
