### ISSUE TITLE
"Attempt to modify read-only document"

### ISSUE THREAD

**Issue by ricardojmendez** [cursive-ide/cursive#1312]
IDEA raised an exception while attempting to switch from Parinfer to Paredit, using the selector at the bottom-right corner.

Not sure if it's related or now, but I was trying to turn it off because Parinfer kept mistakenly moving a closing parenthesis whenI tried to add a comment inside a function.  IDEA beachballed when I went to the change the setting then raised a ReadOnlyModificationException.

```
Attempt to modify read-only document
com.intellij.openapi.editor.ReadOnlyModificationException: Attempt to modify read-only document
	at com.intellij.openapi.editor.impl.DocumentImpl.insertString(DocumentImpl.java:469)
	at cursive.structural.ParinferComponent$applyResult$1$1.run(ParinferComponent.kt:230)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.runUndoTransparentAction(CoreCommandProcessor.java:296)
	at cursive.structural.ParinferComponent$applyResult$1.run(ParinferComponent.kt:226)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1009)
	at cursive.structural.ParinferComponent.applyResult(ParinferComponent.kt:223)
	at cursive.structural.ParinferComponent.applyParinfer(ParinferComponent.kt:215)
	at cursive.structural.ParinferComponent.updateDocument(ParinferComponent.kt:170)
	at cursive.structural.ParinferComponent$documentChanged$1.run(ParinferComponent.kt:97)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:378)
	at com.intellij.util.Alarm$Request.run(Alarm.java:398)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:227)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.a(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by ricardojmendez** [comment]
Environment: IDEA 2016.1, Build #IU-145.258, Cursive 1.2.1-2016.1, OS X.

**Comment by cursive-ide** [comment]
BTW I fixed this a release or two back, if you see it again please reopen.

**Comment by ricardojmendez** [comment]
Will do, thanks!
