### ISSUE TITLE
Cursive init thread dead lock when IDEA start

### ISSUE THREAD

**Issue by zhanghuabin** [cursive-ide/cursive#1345]
I installed IDEA 2016.1.1 ultimate & cursive 1.2.2

This is jstack output:

http://pastebin.com/SyGye2tU

and this is my plugin list as blow:

![ss](https://cloud.githubusercontent.com/assets/5813426/14226940/c3fc88a8-f923-11e5-975d-640ada08d158.png)

**Comment by zhanghuabin** [comment]
cursive 1.2.2 works well in 2015.0.5

**Comment by zhanghuabin** [comment]
This problem is still exist in IDEA 2016.1.2 + cursive 1.2.6, this is the dead lock thread stack as below:



Found one Java-level deadlock:
=============================
"ApplicationImpl pooled thread 4":
  waiting to lock monitor 0x0000000023425d68 (object 0x0000000722a7e4b8, a java.lang.Object),
  which is held by "AWT-EventQueue-0 2016.1.2#IU-145.971.21 IDEA, eap:false, os:Windows 8.1 6.3, java-version:Oracle Corporation 1.8.0_92-b14"
"AWT-EventQueue-0 2016.1.2#IU-145.971.21 IDEA, eap:false, os:Windows 8.1 6.3, java-version:Oracle Corporation 1.8.0_92-b14":
  waiting to lock monitor 0x00000000234265a8 (object 0x00000007b7957cf8, a java.lang.Object),
  which is held by "ApplicationImpl pooled thread 4"

Java stack information for the threads listed above:
===================================================
"ApplicationImpl pooled thread 4":
	at cursive.config.InitComponent.initClojure(InitComponent.java:89)
	- waiting to lock <0x0000000722a7e4b8> (a java.lang.Object)
	at cursive.formatter.codeStyle.ClojureCodeStyleSettings.<init>(ClojureCodeStyleSettings.java:38)
	at cursive.formatter.codeStyle.ClojureCodeStyleSettingsProvider.createCustomSettings(ClojureCodeStyleSettingsProvider.java:40)
	at com.intellij.psi.codeStyle.CodeStyleSettings.<init>(CodeStyleSettings.java:73)
	at com.intellij.psi.codeStyle.CodeStyleSettings.<init>(CodeStyleSettings.java:62)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at com.intellij.openapi.util.DefaultJDOMExternalizer.readExternal(DefaultJDOMExternalizer.java:272)
	at com.intellij.psi.codeStyle.CodeStyleSettingsManager.readExternal(CodeStyleSettingsManager.java:83)
	at com.intellij.psi.codeStyle.CodeStyleSettingsManager.loadState(CodeStyleSettingsManager.java:105)
	at com.intellij.psi.codeStyle.CodeStyleSettingsManager.loadState(CodeStyleSettingsManager.java:33)
	at com.intellij.configurationStore.ComponentStoreImpl.a(ComponentStoreImpl.kt:291)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:96)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.java:54)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:237)
	- locked <0x0000000724d13430> (a com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:212)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:46)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:37)
	at com.intellij.psi.codeStyle.CodeStyleSettingsManager.getInstance(CodeStyleSettingsManager.java:60)
	at com.wrq.tabifier.TabifierActionHandler.<init>(TabifierActionHandler.java:65)
	at com.wrq.tabifier.tabifier_action.<init>(tabifier_action.java:30)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:484)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:154)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:511)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:491)
	- locked <0x00000007b7957cf8> (a java.lang.Object)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:484)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActions(ActionManagerImpl.java:1263)
	at com.intellij.openapi.actionSystem.impl.ActionPreloader.preload(ActionPreloader.java:31)
	at com.intellij.openapi.application.Preloader$2$1.run(Preloader.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.application.Preloader$2.run(Preloader.java:74)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
"AWT-EventQueue-0 2016.1.2#IU-145.971.21 IDEA, eap:false, os:Windows 8.1 6.3, java-version:Oracle Corporation 1.8.0_92-b14":
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:488)
	- waiting to lock <0x00000007b7957cf8> (a java.lang.Object)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:484)
	at cursive.actions$unregister_action.doInvoke(actions.clj:31)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at cursive.actions.paredit$initialise.invoke(paredit.clj:836)
	at cursive.initialise$initialise_all.invoke(initialise.clj:38)
	at clojure.lang.Var.invoke(Var.java:375)
	at cursive.config.InitComponent.initClojure(InitComponent.java:122)
	- locked <0x0000000722a7e4b8> (a java.lang.Object)
	at cursive.config.InitComponent.initComponent(InitComponent.java:78)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:522)
	- locked <0x000000072386ee58> (a com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:123)
	at com.intellij.openapi.application.impl.ApplicationImpl.access$801(ApplicationImpl.java:92)
	at com.intellij.openapi.application.impl.ApplicationImpl$12.run(ApplicationImpl.java:500)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:516)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:107)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:458)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:450)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:194)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:61)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Found 1 deadlock.

**Comment by cursive-ide** [comment]
This looks like #1210, check that issue for a workaround.

**Comment by zhanghuabin** [comment]
That workaround worked fine.

Thanks a lot!
