### ISSUE TITLE
Support Leiningen 2.7.0

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/cursive#1506]
Currently creating the shim breaks:
```
java.lang.RuntimeException: Could not create Shim
	at cursive.leiningen.project.LeinShimProvider.getShim(ProjectDetails.kt:79)
	at cursive.leiningen.project.LeinShimProvider.withShim(ProjectDetails.kt:48)
	at cursive.leiningen.project.LeiningenProjectDetails.getProjectDetails(ProjectDetails.kt:116)
	at cursive.leiningen.project.LeiningenProjectsManager$reimportAllProjects$task$1.run(LeiningenProjectsManager.kt:127)
	at cursive.leiningen.LeiningenUtil$4$1.run(LeiningenUtil.java:103)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: No such var: classpath/resolve-managed-dependencies, compiling:(leiningen/core/project.clj:695:10)
	at clojure.lang.Compiler.analyze(Compiler.java:6688)
	at clojure.lang.Compiler.analyze(Compiler.java:6625)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3766)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6870)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.analyze(Compiler.java:6625)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6001)
	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6319)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6868)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6856)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.analyze(Compiler.java:6625)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6001)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6868)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.analyze(Compiler.java:6625)
	at clojure.lang.Compiler$IfExpr$Parser.parse(Compiler.java:2797)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6868)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6856)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.analyze(Compiler.java:6625)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6001)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5380)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3972)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6866)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6856)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.access$300(Compiler.java:38)
	at clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:589)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6868)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.analyze(Compiler.java:6625)
	at clojure.lang.Compiler.eval(Compiler.java:6931)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:1523)
	at cursive.leiningen.project$eval25$loading__5569__auto____26.invoke(project.clj:1)
	at cursive.leiningen.project$eval25.invokeStatic(project.clj:1)
	at cursive.leiningen.project$eval25.invoke(project.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:379)
	at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.require(ClojureRuntimeShimImpl.java:78)
	at cursive.leiningen.ShimBootstrap.invoke(ShimBootstrap.java:27)
	at cursive.leiningen.Shim$createShimProvider$1.invoke(Shim.kt:61)
	at cursive.leiningen.project.LeinShimProvider$createShim$1.invoke(ProjectDetails.kt:86)
	at cursive.leiningen.project.LeinShimProvider$createShim$1.invoke(ProjectDetails.kt:30)
	at cursive.application.ApplicationKt$sam$Runnable$67b3445a.run(Application.kt)
	... 6 more
Caused by: java.lang.RuntimeException: No such var: classpath/resolve-managed-dependencies
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.Compiler.resolveIn(Compiler.java:7138)
	at clojure.lang.Compiler.resolve(Compiler.java:7108)
	at clojure.lang.Compiler.analyzeSymbol(Compiler.java:7069)
	at clojure.lang.Compiler.analyze(Compiler.java:6648)
	... 99 more
```

**Comment by cprice404** [comment]
@cursive-ide I'm the one who made the changes in lein introducing that `resolve-managed-dependencies` fn, so let me know if there's anything I can do to help.

**Comment by cprice404** [comment]
@cursive-ide thanks for this - any idea on a 1.4.0 release date?

**Comment by cursive-ide** [comment]
@cprice404 Not yet sorry, it's being delayed by some non-work nonsense unfortunately. I'm hoping within two weeks.

**Comment by cprice404** [comment]
@cursive-ide would it be helpful if I filed a separate issue about the managed-dependencies stuff?  Happy to do it if it helps your book-keeping, but didn't want to spam you if you are already on top of it.

Also, just FYI, there was a small bug in lein 2.7.0 related to managed deps, which will necessitate a lein 2.7.1 pretty soon.  I don't *think* that the changes therein should have any impact on cursive - they should be much less invasive/drastic than the 2.7.0 changes, but wanted to give you a heads up in case that helps you in any way.

**Comment by cprice404** [comment]
@cursive-ide FYI, lein 2.7.1 is out, containing that fix.  Also, curious whether you had a chance to test that workaround that we discussed in IRC the other day, about changing your "hook" to be a no-op if the input to that read command was a Stream?

**Comment by cursive-ide** [comment]
@cprice404 I haven't yet sorry, I will do shortly.

**Comment by cprice404** [comment]
@cursive-ide cool, thanks.  Let me know if there's anything I can do to help - happy to jump onto IRC again, or whatever.  (File a PR?  :)

We're getting ready to switch all of our libraries over to use lein-parent, but if I do that right now it will break all of our Cursive users and I might get punched :)

**Comment by cursive-ide** [comment]
@cprice404 Actually, in the end I filed #1543, since this one is already closed.
