### ISSUE TITLE
Generate stubs fails with ArityException

### ISSUE THREAD

**Issue by trimtab613** [cursive-ide/cursive#1507]
Trying "Generate now" when the "requires namespaces which need stubs" results in this IntelliJ error:

```
Error generating stubs for module <<my-module>>

Exception in thread "main" clojure.lang.ArityException: Wrong number of args (3) passed to: api/analyze-file, compiling:(/Users/<<my-username>>/Library/Caches/IntelliJIdea15/tmp/create-stub288816042424425542.clj:2:1)
at clojure.lang.Compiler.load(Compiler.java:7239)
at clojure.lang.Compiler.loadFile(Compiler.java:7165)
at clojure.lang.RT$3.invoke(RT.java:319)
at user$eval9406.invoke(form-init6054901920397180778.clj:1)
at clojure.lang.Compiler.eval(Compiler.java:6782)
at clojure.lang.Compiler.eval(Compiler.java:6772)
at clojure.lang.Compiler.load(Compiler.java:7227)
at clojure.lang.Compiler.loadFile(Compiler.java:7165)
at clojure.main$load_script.invoke(main.clj:275)
at clojure.main$init_opt.invoke(main.clj:280)
at clojure.main$initialize.invoke(main.clj:308)
at clojure.main$null_opt.invoke(main.clj:343)
at clojure.main$main.doInvoke(main.clj:421)
at clojure.lang.RestFn.invoke(RestFn.java:421)
at clojure.lang.Var.invoke(Var.java:383)
at clojure.lang.AFn.applyToHelper(AFn.java:156)
at clojure.lang.Var.applyTo(Var.java:700)
at clojure.main.main(main.java:37)
Caused by: clojure.lang.ArityException: Wrong number of args (3) passed to: api/analyze-file
at clojure.lang.AFn.throwArity(AFn.java:429)
at clojure.lang.AFn.invoke(AFn.java:40)
at user$eval13264.invoke(create-stub288816042424425542.clj:2)
at clojure.lang.Compiler.eval(Compiler.java:6782)
at clojure.lang.Compiler.eval(Compiler.java:6772)
at clojure.lang.Compiler.load(Compiler.java:7227)
... 17 more
```

**Comment by a613** [comment]
Still happening after updating to 1.5.1-2017.1 today.
