### ISSUE TITLE
"ns" and "defn" cannot be resolved.

### ISSUE THREAD

**Issue by darrensony** [cursive-ide/cursive#1531]
Similar behaviour to #626. Things worked until recently. This is affecting all my projects, new and old.

I can reproduce this problem with a single-file project, consisting only of a project.clj and core.clj

$ cat project.clj
```
(defproject test "0.1.0"
  :dependencies [[org.clojure/clojure "1.8.0"]])
```

$ cat src/test/core.clj
```
 (ns test.core)
```

Hovering over "ns" in the editor shows "ns" cannot be resolved.

Things already tried:
- Invalidate caches and restart
- Delete .idea directory
- Delete entire ~/.m2/repository hierarchy
- Clojure 1.7 and 1.8
- Java 1.8.0_25 and 1.8.0_92
- Cursive 1.3.1-15 and 1.40-eap2-15 (uninstall and re-install)
- Re-install Leiningen
- Delete ~/lein/profiles.clj

System: 
- OSX 10.11.6
- IntelliJ 15.0.6
- Leiningen 2.7.0

The only suspicious thing in the log is "#cursive.leiningen.Shim - Bootstrap loader cannot load RT"

I unfortunately can't find the black magic to increate the log level from INFO for Cursive.

Attached: 
- [dot-idea.zip](https://github.com/cursive-ide/cursive/files/478942/dot-idea.zip)
- [idea.log.zip](https://github.com/cursive-ide/cursive/files/478962/idea.log.zip)

**Comment by cursive-ide** [comment]
That is very strange, and that log line would indeed cause that problem (it would mean that lein can't sync any dependencies). I'll try to reproduce that problem. My immediate suspicion would be that somehow Clojure is not on the classpath, but looking at your project it seems like it should be.

**Comment by darrensony** [comment]
I'm not sure if this is even a valid test, but I started a REPL with "Use clojure.main in normal JVM Process" and dumped the classpath.

My project.clj says to use clojure-1.8.0, but it looks like Cursive is injecting clojure-1.7.0 into $PROJECT/lib

Unfortunately, removing the JAR from the PROJECT/lib directory doesn't solve the problem. The PROJECT/target/classes dir is empty as well.

Cut/Paste
```
user=> (for [cp (.getURLs (ClassLoader/getSystemClassLoader))] (println (.getFile cp)))
/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/lib/charsets.jar
... other standard jdk jars ...
/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/lib/tools.jar
/Users/dholloway1/src/sne/test/src/
/Users/dholloway1/src/sne/test/target/classes/
/Users/dholloway1/src/sne/test/lib/clojure-1.7.0.jar
/Users/dholloway1/.m2/repository/clojure-complete/clojure-complete/0.2.4/clojure-complete-0.2.4.jar
/Users/dholloway1/.m2/repository/org/clojure/clojure/1.8.0/clojure-1.8.0.jar
/Users/dholloway1/.m2/repository/org/clojure/tools.nrepl/0.2.12/tools.nrepl-0.2.12.jar
/Applications/IntelliJ%20IDEA%2015.app/Contents/lib/idea_rt.jar
```

**Comment by cursive-ide** [comment]
That's very strange - Cursive definitely doesn't automatically inject anything into the classpath like that. Looking at your `.idea` directory, you seem to have a "Clojure 1.7.0" library manually added there.

Does this occur if you create a new project using `lein new test-project` and then import it using *File->Open...*?

**Comment by darrensony** [comment]
Following that workflow, classpath looks normal, but symbols are still not resolved in Cursive.

Classpath (skipping Java part)
```
/Users/dholloway1/src/tmp/test-project/resources/
/Users/dholloway1/src/tmp/test-project/src/
/Users/dholloway1/src/tmp/test-project/test/
/Users/dholloway1/src/tmp/test-project/target/classes/
/Users/dholloway1/.m2/repository/clojure-complete/clojure-complete/0.2.4/clojure-complete-0.2.4.jar
/Users/dholloway1/.m2/repository/org/clojure/clojure/1.8.0/clojure-1.8.0.jar
/Users/dholloway1/.m2/repository/org/clojure/tools.nrepl/0.2.12/tools.nrepl-0.2.12.jar
/Applications/IntelliJ%20IDEA%2015.app/Contents/lib/idea_rt.jar
```

Attached: 
- [test-project.zip](https://github.com/cursive-ide/cursive/files/483172/test-project.zip)

**Comment by cursive-ide** [comment]
Do you still get the error about `RT` in the log?

**Comment by darrensony** [comment]
Yes, it's still there.

Attached:
- [idea.log.zip](https://github.com/cursive-ide/cursive/files/483555/idea.log.zip)

**Comment by cursive-ide** [comment]
Could you try downloading the build [here](http://colinfleming.net/dhalloway/cursive-1.3.1-15.zip), install it with *Settings->Plugins->Install plugin from disk* and then reproduce the problem? That should print out the exception which is currently being swallowed.

**Comment by darrensony** [comment]
```
2016-09-20 15:45:43,016 [  11977]   INFO -        #cursive.leiningen.Shim - Bootstrap loader cannot load RT 
java.lang.ClassNotFoundException: clojure.lang.RT
	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:249)
	at cursive.leiningen.Shim.createShimProvider(Shim.kt:42)
	at cursive.leiningen.project.LeinShimProvider.getShim(ProjectDetails.kt:66)
	at cursive.leiningen.project.LeinShimProvider.withShim(ProjectDetails.kt:48)
	at cursive.leiningen.project.LeiningenProjectDetails.getProjectDetails(ProjectDetails.kt:116)
	at cursive.leiningen.project.LeiningenProjectsManager$reimportAllProjects$task$1.run(LeiningenProjectsManager.kt:127)
	at cursive.leiningen.LeiningenUtil$4$1.run(LeiningenUtil.java:103)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:366)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
```

- [idea.log.zip](https://github.com/cursive-ide/cursive/files/483755/idea.log.zip)

**Comment by darrensony** [comment]
I did a full uninstall and re-install of IntellIJ and Cursive, and the problem seems to have gone away.

I did save all the original directories if there are any files for which you might want a diff, but otherwise, I consider this solved, and thanks for all your support!

Now I just have to re-engineer a year's worth of customizations ;)

**Comment by shlomi-schwartz** [comment]
Having the same issue with:
IntelliJ IDEA 2017.1.4
Build #IU-171.4694.23, built on June 6, 2017
Licensed to IntelliJ IDEA Evaluator
Expiration date: July 21, 2017
JRE: 1.8.0_112-release-736-b21 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.5

and:

Cursive Version: 1.5.1-2017.1

other clojure plugins works fine, and I can run the repl from the command line on any terminal window.

It seems like the issue occurs when indexing file is done.

**Comment by sbreatnach** [comment]
I also had this issue with my install:
Cursive Version: 1.6.1-2017.2
IntelliJ IDEA 2017.2.4
Build #IU-172.4155.36, built on September 11, 2017
JRE: 1.8.0_152-release-915-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-93-generic

It randomly occurred sometime in the last few days. The only change to my install in that timeframe was a few new plugins, specifically GNU GetText and Lua support. My workaround was to uninstall Cursive, restart and reinstall.
The log output "#cursive.leiningen.Shim - Bootstrap loader cannot load RT" still occurs but, crucially, it doesn't make any difference.

**Comment by lumir-mrkva** [comment]
i had some problem, make sure that leiningen project is added - open project.clj to check

**Comment by nickbauman** [comment]
I got this too. I think there's a bug here, but it's probably really hard to reproduce.

**Comment by cursive-ide** [comment]
@nickbauman If you've had that recently and you're on IntelliJ 2019.1, that is probably #2173, which is caused by an underlying platform bug.

**Comment by Nek** [comment]
Same issue here.
