### ISSUE TITLE
IndexOutOfBoundsException regular occurrence during editing

### ISSUE THREAD

**Issue by ism-ssw** [cursive-ide/cursive#1546]
This frequently occurs during editing. Seems more likely to happen after cut/paste operations or deletions. Once it occurs can prevent autocomplete (though this seems intermittent) but the IDE will still understand if functions or variables are missing.
I have tried to identify the exact times it happens but the above description is as close as I can get. Once it has occurred the frequency of the event increases 

Example Stacktrace follows
```
chars sequence.length:1002, start:6895, end:6900
java.lang.IndexOutOfBoundsException: chars sequence.length:1002, start:6895, end:6900
	at com.intellij.util.text.CharSequenceSubSequence.<init>(CharSequenceSubSequence.java:34)
	at com.intellij.util.text.ImmutableText.subSequence(ImmutableText.java:229)
	at com.intellij.openapi.editor.impl.DocumentImpl$5.compute(DocumentImpl.java:829)
	at com.intellij.openapi.editor.impl.DocumentImpl$5.compute(DocumentImpl.java:826)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:859)
	at com.intellij.openapi.editor.impl.DocumentImpl.getText(DocumentImpl.java:826)
	at cursive.symbol$arglists$fn__1551.invoke(symbol.clj:71)
	at clojure.core$mapv$fn__6727.invoke(core.clj:6616)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:333)
	at clojure.core$reduce.invoke(core.clj:6518)
	at clojure.core$mapv.invoke(core.clj:6616)
	at cursive.symbol$arglists.invoke(symbol.clj:71)
	at cursive.lookup$fn__4410.invoke(lookup.clj:63)
	at cursive.lookup$fn__4380$G__4375__4389.invoke(lookup.clj:19)
	at cursive.lookup$fn__4410.invoke(lookup.clj:61)
	at cursive.lookup$fn__4380$G__4375__4389.invoke(lookup.clj:19)
	at cursive.resolve.symbol.editor.clj$editor_resolver$reify__5087$fn__5092.invoke(clj.clj:366)
	at clojure.core$map$fn__4553.invoke(core.clj:2624)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.length(RT.java:1727)
	at clojure.lang.RT.seqToTypedArray(RT.java:1696)
	at clojure.core$into_array.invoke(core.clj:3321)
	at cursive.resolve.symbol.editor.clj$editor_resolver$reify__5087.unqualified_variants(clj.clj:367)
	at cursive.resolve.symbol$variants.invoke(symbol.clj:44)
	at clojure.lang.Var.invoke(Var.java:379)
	at cursive.psi.impl.symbols.SymbolReference.getVariants(SymbolReference.java:157)
	at cursive.completion.ClojureCompletionContributor.fillCompletionVariants(completion.clj:92)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:132)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:125)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:90)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:155)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:110)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.a(CompletionProgressIndicator.java:776)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$500(CompletionProgressIndicator.java:90)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:758)
	at com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:87)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:848)
	at com.intellij.codeInsight.completion.AsyncCompletion.b(CompletionThreading.java:84)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:82)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
IntelliJ IDEA 2016.2.4
Build #IU-162.2032.8, built on September 9, 2016
JRE: 1.8.0_60-b27 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

Cursive
Built on: 2016-08-29 13:42
Built from: 1.4.0-eap2

**Comment by ism-ssw** [comment]
an update on this is that I don't believe this is just when copy or paste has been used. any editing seems to cause the issue.

**Comment by ism-ssw** [comment]
This is no longer occurring since the upgrade to 1.4.0-eap3-2016.2
Built on: 2016-10-03 13:04
Built from: 1.4.0-eap3-4-g6138141
I will close for now
