### ISSUE TITLE
Unable to run Leiningen tasks with 1.4.0-eap3

### ISSUE THREAD

**Issue by ckarlsen84** [cursive-ide/cursive#1561]
Intellij CE 2016.3 EAP, cursive 1.4.0-eap3, Leiningen 2.7.1

> java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key console.too.much.text.buffer.ratio
	at java.util.ResourceBundle.getObject(ResourceBundle.java:450)
	at java.util.ResourceBundle.getString(ResourceBundle.java:407)
	at com.intellij.openapi.util.registry.RegistryValue.getBundleValue(RegistryValue.java:166)
	at com.intellij.openapi.util.registry.RegistryValue._get(RegistryValue.java:157)
	at com.intellij.openapi.util.registry.RegistryValue.get(RegistryValue.java:137)
	at com.intellij.openapi.util.registry.RegistryValue.asInteger(RegistryValue.java:74)
	at com.intellij.openapi.util.registry.Registry.intValue(Registry.java:69)
	at cursive.runner.console.ConsoleViewImpl.<init>(ConsoleViewImpl.java:339)
	at cursive.runner.console.ConsoleViewImpl.<init>(ConsoleViewImpl.java:273)
	at cursive.runner.console.ConsoleViewImpl.<init>(ConsoleViewImpl.java:266)
	at cursive.leiningen.run.LeiningenCommandLineState$getConsoleBuilder$1.getConsole(LeiningenCommandLineState.kt:212)
	at com.intellij.execution.configurations.CommandLineState.createConsole(CommandLineState.java:91)
	at com.intellij.execution.configurations.CommandLineState.execute(CommandLineState.java:81)
	at com.intellij.execution.impl.DefaultJavaProgramRunner.doExecute(DefaultJavaProgramRunner.java:84)
	at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:43)
	at com.intellij.execution.impl.ExecutionManagerImpl.lambda$startRunProfile$3(ExecutionManagerImpl.java:381)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:91)
	at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:41)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:116)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:126)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.execution.impl.ExecutionManagerImpl.lambda$startRunProfile$4(ExecutionManagerImpl.java:438)
	at com.intellij.execution.impl.ExecutionManagerImpl.compileAndRun(ExecutionManagerImpl.java:293)
	at com.intellij.execution.impl.ExecutionManagerImpl.startRunProfile(ExecutionManagerImpl.java:438)
	at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:40)
	at cursive.leiningen.run.LeiningenRunner.access$001(LeiningenRunner.java:18)
	at cursive.leiningen.run.LeiningenRunner$1$1.run(LeiningenRunner.java:59)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:311)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:421)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:405)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:838)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:674)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by extesy** [comment]
Same problem for me

**Comment by cursive-ide** [comment]
This is an error with the latest EAP build.
