### ISSUE TITLE
Error opening project file which slurps file

### ISSUE THREAD

**Issue by RaymondKroon** [cursive-ide/cursive#1564]
If I open https://github.com/PDOK/featured I get an error:
```Error opening project: Error loading /home/raymond/Development/PDOK/featured/project.clj
java.lang.Exception: Error loading /home/raymond/Development/PDOK/featured/project.clj
	at leiningen.core.project$read_raw$fn__6407.invoke(project.clj:962)
	at leiningen.core.project$read_raw.invokeStatic(project.clj:956)
	at leiningen.core.project$read_raw.invoke(project.clj:952)
	at cursive.leiningen.project$read_raw_hook.invokeStatic(project.clj:429)
	at cursive.leiningen.project$read_raw_hook.invoke(project.clj:393)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at robert.hooke$compose_hooks$fn__11994.doInvoke(hooke.clj:40)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.core$apply.invoke(core.clj:641)
	at robert.hooke$run_hooks.invokeStatic(hooke.clj:46)
	at robert.hooke$run_hooks.invoke(hooke.clj:45)
	at robert.hooke$prepare_for_hooks$fn__11999$fn__12000.doInvoke(hooke.clj:54)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at cursive.leiningen.project_details$details$fn__1477.invoke(project_details.clj:9)
	at cursive.leiningen.project_details$details.invokeStatic(project_details.clj:7)
	at cursive.leiningen.project_details$details.invoke(project_details.clj:6)
	at clojure.lang.Var.invoke(Var.java:383)
	at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke(ClojureRuntimeShimImpl.java:124)
	at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke(ClojureRuntimeShimImpl.java:117)
	at cursive.leiningen.ShimBootstrap$Shim.invoke(ShimBootstrap.java:51)
	at cursive.leiningen.project.LeiningenProjectOpenProcessor$doQuickImport$1$run$details$1.invoke(Import.kt:359)
	at cursive.leiningen.project.LeiningenProjectOpenProcessor$doQuickImport$1$run$details$1.invoke(Import.kt:351)
	at cursive.leiningen.project.LeinShimProvider.withShim(ProjectDetails.kt:50)
	at cursive.leiningen.project.LeiningenProjectOpenProcessor$doQuickImport$1.run(Import.kt:357)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager$9.run(CoreProgressManager.java:384)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:548)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: VERSION (No such file or directory), compiling:(project.clj:1:14)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3657)
	at clojure.lang.Compiler$DefExpr.eval(Compiler.java:451)
	at clojure.lang.Compiler.eval(Compiler.java:6932)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.lang.RT$3.invoke(RT.java:320)
	at leiningen.core.project$read_raw$fn__6407.invoke(project.clj:960)
	... 43 more
Caused by: java.io.FileNotFoundException: VERSION (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at clojure.java.io$fn__9520.invokeStatic(io.clj:229)
	at clojure.java.io$fn__9520.invoke(io.clj:229)
	at clojure.java.io$fn__9433$G__9426__9440.invoke(io.clj:69)
	at clojure.java.io$fn__9532.invokeStatic(io.clj:258)
	at clojure.java.io$fn__9532.invoke(io.clj:254)
	at clojure.java.io$fn__9433$G__9426__9440.invoke(io.clj:69)
	at clojure.java.io$fn__9494.invokeStatic(io.clj:165)
	at clojure.java.io$fn__9494.invoke(io.clj:165)
	at clojure.java.io$fn__9446$G__9422__9453.invoke(io.clj:69)
	at clojure.java.io$reader.invokeStatic(io.clj:102)
	at clojure.java.io$reader.doInvoke(io.clj:86)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$slurp.invokeStatic(core.clj:6657)
	at clojure.core$slurp.doInvoke(core.clj:6657)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3652)
	... 49 more```

When I already got the project imported I got something similar:
```
Error loading /home/raymond/Development/PDOK/featured-to-extracts/project.clj
			java.io.FileNotFoundException: VERSION (No such file or directory), compiling:(project.clj:1:14)
			VERSION (No such file or directory)
```
(This is for another project, but the layout is the same)

**Comment by cursive-ide** [comment]
Yes, this is a bug in the latest EAP (I'm assuming you're on EAP 3). It's tracked in #1551.

**Comment by RaymondKroon** [comment]
I was feeling bad about using Cursive yesterday, not realizing I was on the EAP branch. It does work on stable :)
