### ISSUE TITLE
IDE freezes, CPU at 100%

### ISSUE THREAD

**Issue by gerrit-hntschl** [cursive-ide/cursive#1566]
Hi!

Hi! I have an issue with one project that cannot be opened anymore. 

Cursive Version is 1.4.0-eap3-2016.2, Intellij CE 2016.2.5. I am on Ubuntu 16.04.

The UI freezes and one CPU is constantly at 100% and seems to be stuck inside here:
```
"ApplicationImpl pooled thread 13" #91 prio=4 os_prio=0 tid=0x00007f1d01923000 nid=0x11f8 runnable [0x00007f1cd21f6000]
   java.lang.Thread.State: RUNNABLE
	at cursive.resolve$light_keys.invoke(resolve.clj:164)
	at cursive.resolve$resolve_keys.invoke(resolve.clj:179)
	at cursive.formatting$list_block_params.invoke(formatting.clj:230)
	at cursive.formatting$basic_block_params.invoke(formatting.clj:311)
	at cursive.formatting$sub_blocks.invoke(formatting.clj:321)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:630)
	at clojure.core$memoize$fn__5479.doInvoke(core.clj:6082)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at cursive.formatting.ElementBlock.getSubBlocks(formatting.clj:36)
      ......
```
The only warnings I see on the terminal are some more of these:
```
[  18918]   WARN - tectAndAdjustIndentOptionsTask - Indent detection is too long for: test.clj 
```

I tried invalidating the caches but that didn't help. Any other quick workarounds I could try?

Would be great if you could have a look at that because it prevents me from working on that project with your awesome editor :/

**Comment by gerrit-hntschl** [comment]
Btw I also tried Cursive 1.3.0-2016.2 but had the same issue. Funny thing is that the project could be opened initially, but now it is trying to index again and never gets past that `light_keys` call.

**Comment by gerrit-hntschl** [comment]
Right, after deleting `.idea` and the `.iml` Cursive can open the project again, and finishes indexing just fine. 
Might still be worthy to investigate what could make that call spin forever?

**Comment by gerrit-hntschl** [comment]
Just saw that this is a duplicate of [#1210](https://github.com/cursive-ide/cursive/issues/1210). I will try the workaround (disabling indent detection) when it happens next time
