### ISSUE TITLE
A way to mute "Your project requires namespaces which need stubs to be generated"

### ISSUE THREAD

**Issue by oshyshko** [cursive-ide/cursive#1599]
![image](https://cloud.githubusercontent.com/assets/73026/20773916/e2e07088-b708-11e6-9bf2-94d7096fc93b.png)

This message is stealing space from editor and it doesn't have a way to remove it (Generate now button is not working). This message appears every time I change current branch or reload Lein project.

Please, provide a way to mute this message once and forever (even at the cost if some Cursive's features won't be working).

Thank you for a great IDEA plugin.

P.S. Long version for UI/UX specialists at Cursive:

From developer perspective, I understand that this message is important (for developers) because Cursive couldn't build some indexes and therefore some functionality won't be working.

But, from user perspective, this message is extremely invasive and makes user feel not of in control of their own IDE.

For end user, the message on screenshot "Your project requires namespaces which need stubs to be generated" [Generate now] ...reads and feels as: "Cursive plugin is not happy because it has some internal problems with your project and this is why you'll be seeing this unremovable message many times. You can try clicking a button on the right side, but if it's not working, then the message will remain here forever. In a case, if you really want to remove this message, you should spend your time on investigating error log, solving the problem and then trying to click the button again. Until then, we will keep this unremovable message here, because we believe internal problems of Cursive plugin are more important than yours. Good luck and you hold on there." [Button: Press this button if you believe your project is ready to make Cursive plugin happy, and, also every time you reload a Lein project or change your git branch]

Please, let users to stay in control of the IDE and let them decide what's important for them.

**Comment by conan** [comment]
I'd also like to do this.  I develop on Windows, and we have a project which I regularly work on that also contains a small amount of openCV image manipulation; the openCV native library is not available in any sensible way on Windows, and generating stubs for this project always fails because it can't find that dependency on the classpath.  I don't work on that image code, and can compile and run the project just fine from the command line (the dependency is resolved at runtime as it's a native library). 

Even better than just hiding this error would be to generate all the stubs that can be generated, and leave the ones that require an unresolvable dependency.

**Comment by trimtab613** [comment]
It's quite upsetting when emacs fans see my screen and ask why that message is there.

**Comment by cursive-ide** [comment]
So, first up, I'm sorry this is so aggravating. I didn't expect so many problems building the stubs.

In general, it should be possible to make this work every time, and as much as I can that's what I'd like to do since every bug I fix in the stub generation then applies to everyone.

That said, there will probably always be situations where it doesn't work for one reason or another (like @conan's case), so I'm definitely interested in making this UI better. However I definitely don't want to provide a blanket method to disable the notification entirely since I do want users to file bugs when it doesn't work rather than just muting them.

I think the best option would be to use the standard notifications with a custom group. This would mean that users could turn them off under the Notifications settings if they were really annoying in a particular case, and individual notifications can be simply dismissed. The only drawback to this mechanism that I can think of is that they can't then be disabled per-project. The only other option would be to provide some custom UI for that, but I'd rather stick to the standard IntelliJ mechanism if possible.

Does that sound like a reasonable solution?

**Comment by oshyshko** [comment]
> I think the best option would be to use the standard notifications with a custom group. This would mean that users could turn them off under the Notifications settings if they were really annoying in a particular case, and individual notifications can be simply dismissed.

Sounds good.

Also, a typical behavior of IntelliJ is to stack error messages in "Event Log" that is quite noticable, if something is in there (becomes red and shows a number of errors on it). It's not getting in user's way and it can be reset by visiting it -- this is important (so you can detect the moment when a new error appears).

![image](https://cloud.githubusercontent.com/assets/73026/21440519/36663788-c848-11e6-95b7-81197507f1b5.png)

P.S. Also, please, could you take a look at #1579 ? https://github.com/cursive-ide/cursive/issues/1579 That's another super-annoying UI/UX behavior.

**Comment by cursive-ide** [comment]
Right, using the notification mechanism means they'll appear in the event log automatically.

I've been meaning to comment on #1579, I'll comment over there now.

**Comment by conan** [comment]
Yeah, the event log is a good place for this kind of thing, I look at it regularly but it doesn't interfere with my coding.

**Comment by ioRekz** [comment]
I would also prefer the notification mechanism. I managed to make the stub generation work by commenting some of the pre-tasks in project.clj.
In my case
```
:prep-tasks ["compile"]
               ;["less" "once"]
               ;["cljsbuild" "once"]]
```

**Comment by oshyshko** [comment]
The issue is still relevant. Cursive version `1.5.0-2017.1`.

**Comment by lacogubik** [comment]
It seems `less once` task in `:pre-tasks` section of project.clj will throw exception when stubs are being generated.
I got this exception when I tried to generate stubs:
```Invalid javascript engine (javascript)
java.lang.IllegalArgumentException: Invalid javascript engine (javascript)
	at leiningen.less.engine$with_engine_STAR_.invokeStatic(engine.clj:26)
	at leiningen.less.engine$with_engine_STAR_.invoke(engine.clj:23)
	at leiningen.less$run_compiler.invokeStatic(less.clj:23)
	at leiningen.less$run_compiler.invoke(less.clj:20)
	at leiningen.less$once.invokeStatic(less.clj:37)
	at leiningen.less$once.invoke(less.clj:34)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:650)
	at clojure.core$apply.invoke(core.clj:641)
	at leiningen.less$less.invokeStatic(less.clj:54)
	at leiningen.less$less.doInvoke(less.clj:44)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at leiningen.core.main$partial_task$fn__5932.doInvoke(main.clj:272)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at leiningen.core.main$apply_task.invokeStatic(main.clj:322)
	at leiningen.core.main$apply_task.invoke(main.clj:308)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.core$apply.invoke(core.clj:641)
	at robert.hooke$run_hooks.invokeStatic(hooke.clj:46)
	at robert.hooke$run_hooks.invoke(hooke.clj:45)
	at robert.hooke$prepare_for_hooks$fn__11999$fn__12000.doInvoke(hooke.clj:54)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at leiningen.core.eval$run_prep_tasks.invokeStatic(eval.clj:51)
	at leiningen.core.eval$run_prep_tasks.invoke(eval.clj:43)
	at leiningen.core.eval$prep.invokeStatic(eval.clj:86)
	at leiningen.core.eval$prep.invoke(eval.clj:73)
	at leiningen.core.eval$eval_in_project.invokeStatic(eval.clj:362)
	at leiningen.core.eval$eval_in_project.invoke(eval.clj:356)
	at leiningen.core.eval$eval_in_project.invokeStatic(eval.clj:360)
	at leiningen.core.eval$eval_in_project.invoke(eval.clj:356)
	at cursive.leiningen.eval$eval_details$fn__1519.invoke(eval.clj:42)
	at cursive.leiningen.eval$eval_details.invokeStatic(eval.clj:35)
	at cursive.leiningen.eval$eval_details.invoke(eval.clj:13)
	at clojure.lang.Var.invoke(Var.java:383)
	at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke(ClojureRuntimeShimImpl.java:124)
	at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke(ClojureRuntimeShimImpl.java:117)
	at cursive.leiningen.ShimBootstrap$Shim.invoke(ShimBootstrap.java:53)
	at cursive.stubs$lein_parameters$reify__12787.invoke(stubs.clj:211)
	at cursive.leiningen.project.LeinShimProvider.withShim(ProjectDetails.kt:50)
	at cursive.stubs$lein_parameters.invoke(stubs.clj:207)
	at cursive.stubs$generate_stubs$fn__12794$process__12795.invoke(stubs.clj:273)
	at cursive.stubs$generate_stubs$fn__12794.invoke(stubs.clj:297)
	at cursive.task$backgroundable$reify__12723.run(task.clj:12)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:718)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:165)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:343)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)```

**Comment by oshyshko** [comment]
Still relevant.
Cursive version 1.6.0-2017.2.

It's been almost 1 year, since this ticket was created and this never left my screen:
![image](https://user-images.githubusercontent.com/73026/30629814-b20a0430-9d92-11e7-98b7-e2237c430776.png)

Again, clicking "Generate now" doesn't remove it.
The IDE is working normally despite it.

Dear developers, could you, please, hide this into error log?

It's really annoying.

**Comment by a613** [comment]
Could we maybe get a master toggle button for the entire stub generation feature of Cursive? I don't know what it's doing or whether it helps me at all, and I'd like to go back to how it was before this thing got added last year.

**Comment by cursive-ide** [comment]
@a613 I'm working on a fix for this which will give better control. It allows it to be disabled for a particular module in case you have a problematic one, and since it uses notifications now you can also just mute them altogether. The error messages are also better so hopefully we'll have a better chance of figuring out why it's not working in particular cases. 

Once this change is stable I'll also document it and explain why it's needed and how it works.
