### ISSUE TITLE
"Execution error without description" starting local REPL

### ISSUE THREAD

**Issue by jcf** [cursive-ide/cursive#1611]
I'm trying out Cursive and Intellij IDEA on Linux, and have run into an issue importing an existing Leiningen project.

When I try to run a REPL I get an "Unknown error" in the UI, and the following exception logged in the IntelliJ log file:

```
com.intellij.execution.ExecutionException
	at cursive.repl.process_runner$create_run_profile_state$reify__12235.createJavaParameters(process_runner.clj:333)
	at com.intellij.execution.configurations.JavaCommandLineState.getJavaParameters(JavaCommandLineState.java:34)
	at cursive.repl.runner.LeiningenReplRunner$2.run(LeiningenReplRunner.java:146)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:710)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at clojure.core$with_meta__4375.invokeStatic(core.clj:218)
	at clojure.core$with_meta__4375.invoke(core.clj:217)
	at leiningen.core.project$init_profiles.invokeStatic(project.clj:818)
	at leiningen.core.project$init_profiles.doInvoke(project.clj:814)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at leiningen.core.project$set_profiles.invokeStatic(project.clj:860)
	at leiningen.core.project$set_profiles.doInvoke(project.clj:855)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at leiningen.core.project$merge_profiles.invokeStatic(project.clj:870)
	at leiningen.core.project$merge_profiles.invoke(project.clj:864)
	at leiningen.repl$fixup_no_project.invokeStatic(repl.clj:269)
	at leiningen.repl$fixup_no_project.invoke(repl.clj:262)
	at leiningen.repl$repl.invokeStatic(repl.clj:312)
	at leiningen.repl$repl.doInvoke(repl.clj:273)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at cursive.leiningen.repl$repl_details$fn__1493.invoke(repl.clj:59)
	at cursive.leiningen.repl$repl_details.invokeStatic(repl.clj:57)
	at cursive.leiningen.repl$repl_details.invoke(repl.clj:28)
	at clojure.lang.Var.invoke(Var.java:383)
	at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke(ClojureRuntimeShimImpl.java:124)
	at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke(ClojureRuntimeShimImpl.java:117)
	at cursive.leiningen.ShimBootstrap$Shim.invoke(ShimBootstrap.java:51)
	at cursive.repl.process_runner$create_lein_parameters$reify__12219.invoke(process_runner.clj:280)
	at cursive.leiningen.project.LeinShimProvider.withShim(ProjectDetails.kt:50)
	at cursive.repl.process_runner$create_lein_parameters.invoke(process_runner.clj:276)
	at cursive.repl.process_runner$create_run_profile_state$reify__12235.createJavaParameters(process_runner.clj:324)
	... 15 more
```

It'd be nice if this was in the UI somewhere but I guess I don't know how to fix the problem from the stacktrace alone so maybe it doesn't matter.

I'm using the built-in JDK included with IntelliJ (version 1.8.0 something), and have updated IntelliJ using AppBox. I'm getting the same NPE exception with both EAP and without, which makes me think I've not configured something properly.

Here's my REPL Run/Debug configuration:

![2016-12-16-15 37 50-d7f34f5985a3](https://cloud.githubusercontent.com/assets/18374/21268264/df0496ca-c3a5-11e6-860f-9d84e0399880.png)

I'm not sure if there's a better way to share the above. Maybe an XML file in the project `.idea` directory? I'm pretty new to IntelliJ… Sorry!

**Comment by jcf** [comment]
I'm surprised return only 'sends' an expression when you're at the end of the line? I guess I can use some chord to send things; just have to look it up. :smile:

**Comment by jcf** [comment]
Running tests doesn't appear to work in the remote REPL. I can see the namespace loaded, and get some warnings about boxed math (that comes from my `~/.lein/profiles.clj`). But nothing else. No errors in the IntelliJ logs, and no output in my headless REPL. Just silence.

![2016-12-16-16 20 33-74a1375bb4d9](https://cloud.githubusercontent.com/assets/18374/21269673/94aae538-c3ab-11e6-9536-45a24a208a3f.png)
