### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by stephenway** [cursive-ide/cursive#1612]
**Running**

**Leiningen Version** 2.7.1
**Cursive Version** 1.4.1-2016.3
**IntelliJ IDEA** 2016.3.1
**Build** #IU-163.9166.29, built on December 9, 2016
**JRE:** 1.8.0_112-release-408-b2 x86_64
**JVM:** OpenJDK 64-Bit Server VM by JetBrains s.r.o
**macOS Sierra Version** 10.12.2

**Description**

When I refreshing Leiningen projects I get:
`java.lang.NullPointerException: java.lang.NullPointerException`

**Detailed error**

```
java.lang.NullPointerException
java.lang.NullPointerException
	at clojure.lang.Murmur3.hashUnencodedChars(Murmur3.java:76)
	at clojure.lang.Symbol.hasheq(Symbol.java:89)
	at clojure.lang.Util.dohasheq(Util.java:177)
	at clojure.lang.Util.hasheq(Util.java:168)
	at clojure.lang.PersistentHashMap.hash(PersistentHashMap.java:120)
	at clojure.lang.PersistentHashMap$TransientHashMap.doAssoc(PersistentHashMap.java:324)
	at clojure.lang.ATransientMap.assoc(ATransientMap.java:64)
	at clojure.lang.ATransientSet.conj(ATransientSet.java:27)
	at clojure.lang.ATransientSet.conj(ATransientSet.java:15)
	at clojure.core$conj_BANG_.invokeStatic(core.clj:3257)
	at clojure.core$conj_BANG_.invoke(core.clj:3249)
	at clojure.core.protocols$fn__6755.invokeStatic(protocols.clj:167)
	at clojure.core.protocols$fn__6755.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__6710$G__6705__6719.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__6738.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__6738.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__6684$G__6679__6697.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6545)
	at clojure.core$into.invokeStatic(core.clj:6610)
	at clojure.core$into.invoke(core.clj:6604)
	at cursive.leiningen.project$project_info.invokeStatic(project.clj:530)
	at cursive.leiningen.project$project_info.invoke(project.clj:508)
	at cursive.leiningen.project$invoke.invokeStatic(project.clj:580)
	at cursive.leiningen.project$invoke.invoke(project.clj:575)
	at clojure.lang.Var.invoke(Var.java:383)
	at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke(ClojureRuntimeShimImpl.java:124)
	at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke(ClojureRuntimeShimImpl.java:117)
	at cursive.leiningen.ShimBootstrap$Shim.invoke(ShimBootstrap.java:51)
	at cursive.leiningen.project.LeiningenProjectDetails$getProjectDetails$1.invoke(ProjectDetails.kt:117)
	at cursive.leiningen.project.LeiningenProjectDetails$getProjectDetails$1.invoke(ProjectDetails.kt:102)
	at cursive.leiningen.project.LeinShimProvider.withShim(ProjectDetails.kt:50)
	at cursive.leiningen.project.LeiningenProjectDetails.getProjectDetails(ProjectDetails.kt:116)
	at cursive.leiningen.project.LeiningenProjectsManager$reimportAllProjects$task$1.run(LeiningenProjectsManager.kt:127)
	at cursive.leiningen.LeiningenUtil$4$1.run(LeiningenUtil.java:103)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:710)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by stephenway** [comment]
Sovled! Was a problem with my `~/.lein/profiles.clj`

**Comment by cursive-ide** [comment]
What was the issue? It would be better if Cursive showed something more than just an NPE.

**Comment by stephenway** [comment]
I never pinned it down to a single part of the profiles.clj, because I just deleted that file and it started working again, would you like a copy of the profiles file?

**Comment by cursive-ide** [comment]
Sure, if you have it there that would be great, thanks. Either attach it here or mail it to cursive@cursive-ide.com.
