### ISSUE TITLE
Break on Exception?

### ISSUE THREAD

**Issue by Linchy** [cursive-ide/cursive#1700]
Hi I have an agent which is returning an error:

```
Exception in thread "LWJGL Application" java.lang.RuntimeException: Agent is failed, needs restart
	at clojure.lang.Util.runtimeException(Util.java:225)
	at clojure.lang.Agent.dispatch(Agent.java:238)
	at clojure.core$send_via.doInvoke(core.clj:1995)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invoke(core.clj:636)
	at clojure.core$send.doInvoke(core.clj:2006)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at breakout.game$game_update.invoke(game.clj:284)
	at breakout.game$eval16860$fn__16893.invoke(game.clj:360)
	at clojure.lang.Var.invoke(Var.java:383)
	at play_clj.core$defscreen_STAR_$execute_fn_BANG___954$fn__957.invoke(core.clj:83)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at play_clj.core$wrapper.invoke(core.clj:56)
	at play_clj.core$defscreen_STAR_$execute_fn_BANG___954.doInvoke(core.clj:85)
	at clojure.lang.RestFn.invoke(RestFn.java:439)
	at play_clj.core$defscreen_STAR_$fn__970.invoke(core.clj:120)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:630)
	at play_clj.core$set_screen_BANG_$run_fn_BANG___1011.doInvoke(core.clj:517)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at play_clj.core$set_screen_BANG_$reify__1019.render(core.clj:529)
	at com.badlogic.gdx.Game.render(Game.java:46)
	at play_clj.core.proxy$com.badlogic.gdx.Game$ff19274a.render(Unknown Source)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:223)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
Caused by: java.lang.IllegalArgumentException: Key must be integer
	at clojure.lang.APersistentVector.invoke(APersistentVector.java:284)
	at clojure.core$binding_conveyor_fn$fn__4444.invoke(core.clj:1919)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.lang.Agent$Action.doRun(Agent.java:114)
	at clojure.lang.Agent$Action.run(Agent.java:163)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Problem is, I have no idea what part of my code is the problem. The lines it points to is just me doing `(send agent (mymethod))`.

I tried turning on Java Exceptions, but that just shows me this:

```
    private void initialize() {
        this.mainLoopThread = new Thread("LWJGL Application") {
            public void run() {
                LwjglApplication.this.graphics.setVSync(LwjglApplication.this.graphics.config.vSyncEnabled);

                try {
                    LwjglApplication.this.mainLoop();
                } catch (Throwable var2) {
                    if(LwjglApplication.this.audio != null) {
                        LwjglApplication.this.audio.dispose();
                    }

                    Gdx.input.setCursorCatched(false);
                    if(var2 instanceof RuntimeException) {
                        throw (RuntimeException)var2;
                    } else {
                        throw new GdxRuntimeException(var2);
                    }
                }
            }
        };
        this.mainLoopThread.start();
    }
```

Again nothing to do with my code. Is it not possible to break on exception? I have no clue how I could ever do multi threaded code if I can't find a single error.

**Comment by JoelSanchez** [comment]
Hi, I was just looking for this, first I found this issue, then I found this:

https://stackoverflow.com/questions/934794/is-there-break-on-exception-in-intellij

So the answer seems to be: Run | View Breakpoints | Exception Breakpoints
