### ISSUE TITLE
Intellij 2017.2 crashing with Cursive 1.6.0-2017.2

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/cursive#1818]
Reported on the [mailing list](https://groups.google.com/d/topic/cursive/v6N0x5gCQG4/discussion):

I'm getting this stack trace:

```
Plugin 'com.cursiveclojure.cursive' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.NoClassDefFoundError: Could not initialize class clojure.lang.RT
    at cursive.config.InitComponent.initClojure(InitComponent.java:80)
    at cursive.config.InitComponent.initComponent(InitComponent.java:60)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:492)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:118)
    at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:475)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:482)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:102)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:434)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:420)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:203)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:67)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:345)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by cursive-ide** [comment]
This is the same root cause as #1602.

**Comment by mattbishop** [comment]
snapshot3 fixed this, thanks!

Built on: 2017-07-24 21:10

Built from: 1.6.1-snapshot3

**Comment by cursive-ide** [comment]
If anyone else suffers from this problem, here's how to install the dev build which fixes it until it's released.

Go to the [plugin repo page](https://plugins.jetbrains.com/plugin/8090?pr=), click on “dev” to see the dev builds and then manually download a 1.6.1-snapshot3 build corresponding to your IntelliJ version. Then go to Settings->Plugins->Install plugin from disk and point it at the downloaded zip file. This build is just 1.6.0 with this extra fix.
