### ISSUE TITLE
Unable to start lein repl with managed-dependencies

### ISSUE THREAD

**Issue by jstrength** [cursive-ide/cursive#1927]
We recently added a parent project so we could use managed-dependencies and now when I try to run a repl in one of the downstream projects via 'Run nREPL with Leiningen' it hangs with the message 'Calculating REPL classpath' at the bottom with a spinner next to it. I've checked the the IntelliJ log file but it doesn't show anything during this. Any idea how to fix this?

**Comment by tkocmathla** [comment]
I have the same problem, and I get this exception on the command line as the repl starts up:

```
<... application start-up messages ...>
java.lang.NullPointerException
        at clojure.core$deliver.invoke(core.clj:6839)
        at clojure.tools.nrepl.ack$handle_ack$fn__11205.invoke(ack.clj:41)
        at clojure.tools.nrepl.server$handle_STAR_.invoke(server.clj:19)
        at clojure.tools.nrepl.server$handle$fn__11582.invoke(server.clj:28)
        at clojure.core$binding_conveyor_fn$fn__4444.invoke(core.clj:1916)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
nREPL server started on port 42505 on host 127.0.0.1 - nrepl://127.0.0.1:42505
```

Despite it saying the nREPL server has started, Cursive never stops "Calculating REPL classpath".

**Comment by jstrength** [comment]
So we've figured out the issue. We had this piece of code in our parent project.clj and inheriting it into our other projects.
`:eval-in ~(if (= "Linux" (System/getProperty "os.name")) :subprocess :classloader)`
The solution is to not have this inherited and to directly have it in each projects project.clj. 
Possibly something cursive needs to investigate as it is probably due to the macro expansion.
I'm going to close this issue for now.
