### ISSUE TITLE
Windows: exception generating stubs when classpath is too long, CreateProcess error=206

### ISSUE THREAD

**Issue by timgilbert** [cursive-ide/cursive#2021]
I think I reported this through the exception reporter, but I figured it would be more helpful to have a public issue.

When I try to "generate stubs" for my project I'm seeing this exception:

`com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "C:\Program Files\Java\jdk1.8.0_172\bin\java.exe" (in directory "C:\workframe\ocp"): CreateProcess error=206, The filename or extension is too long`

(I'll add the whole traceback to the bottom of this ticket.)

The root of the problem seems to be that my classpath has exceeded 32K, which is the maximum amount of characters Windows can process on the command line:

```
PS C:\workframe\ocp> lein classpath | measure -Character                                                                    
                                                                                                                            
Lines Words Characters Property                                                                                             
----- ----- ---------- --------                                                                                             
                 41150                                                                                                      
```

I'm running Windows 10 with IntelliJ IDEA 2018.2 CE and EAP cursive, which as I write this is at 1.8.0-eap3-2018.2.

The underlying issue isn't only a Cursive problem, I've also run into some trouble with lein which I've filed a ticket for at technomancy/leiningen#2452 (there's a smidgen of background info there as well). I've been able to work around most of the related problems in various ways, but I don't have any way of working around the stub generation.

Here's the whole traceback:

```
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "C:\Program Files\Java\jdk1.8.0_172\bin\java.exe" (in directory "C:\workframe\ocp"): CreateProcess error=206, The filename or extension is too long
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:408)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:51)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:44)
	at cursive.stubs$generate_stubs$fn__6618$process__6619.invoke(stubs.clj:325)
	at cursive.stubs$generate_stubs$fn__6618.invoke(stubs.clj:356)
	at cursive.task$backgroundable$reify__6427.run(task.clj:12)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:736)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:310)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Cannot run program "C:\Program Files\Java\jdk1.8.0_172\bin\java.exe" (in directory "C:\workframe\ocp"): CreateProcess error=206, The filename or extension is too long
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:436)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:404)
	... 18 more
Caused by: java.io.IOException: CreateProcess error=206, The filename or extension is too long
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 20 more
```

**Comment by conan** [comment]
I'm experiencing this issue with 1.8.2-eap3, is there a workaround?  Lack of stubs means I get ClassNotFoundExceptions when I run my REPL

**Comment by cursive-ide** [comment]
@conan Yes, you can fix this. Open _File->Project Structure->Modules->[your module]->Clojure_. There you'll find an option: Shorten command line for stub generation. Probably "classpath file" is the best one to try.

Note that the lack of stubs doesn't cause ClassNotFoundExceptions in your REPL, stubs are strictly used in the editor - that's a different problem of some kind.

**Comment by conan** [comment]
This resolves the problem for me, I'd seen a similar option in run configurations but hadn't spotted that, thanks for the tip.  I'd recommend enabling this by default if there's no downside to it.
