### ISSUE TITLE
Can't update local repository

### ISSUE THREAD

**Issue by conan** [cursive-ide/cursive#2071]
From **Build, Execution, Deployment > Build Tools > Maven > Repositories**, in the list of Indexed maven repositories, Cursive has correctly found my local repository but incorrectly identified it as remote:

![image](https://user-images.githubusercontent.com/3037019/47096663-92029380-d227-11e8-8985-896c50234465.png)

Here's the snippet from `project.clj` where it's configured:

      :repositories [["local" ~(str (.toURI (clojure.java.io/file "repo")))]]

There's some background on why I've done it like this here: 

https://github.com/cursive-ide/cursive/issues/573#issuecomment-357180431

As you can see, pressing the "Update" button gives an error.

[Stack trace from `idea.log`](https://gist.github.com/conan/9c6ff4a2729cdb8494c3a48da8823184)

**Comment by cursive-ide** [comment]
This isn't actually a Cursive issue. You're not defining a local repo there (use the `:local-repo` option for that), you're defining a remote repository called `"local"`. In Maven terminology, there's only ever one local repo, which users colloquially refer to as the cache - this is `~/.m2/repository` by default. 

The problem is that your new repo has no index, which is what that dialog is trying to read - in your log file, you'll see something like this:

```
Caused by: java.lang.RuntimeException: org.apache.maven.wagon.ResourceDoesNotExistException: File: /Users/colin/dev/cursive-bugs/cursive-2071/repo/.index/nexus-maven-repository-index.properties does not exist
	at org.apache.maven.wagon.providers.file.FileWagon.fillInputData(FileWagon.java:69)
	at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:116)
	at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
	at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
	at org.jetbrains.idea.maven.server.Maven3ServerIndexFetcher.retrieve(Maven3ServerIndexFetcher.java:101)
	... 26 more
```

You can fix this by indexing your local repo using the Maven Indexer CLI:

```
java -jar ~/Downloads/indexer-cli-6.0.0.jar -r repo -i repo/.index -d repo/.index -n local
```

Where `indexer-cli-6.0.0.jar` comes from e.g. [here](https://search.maven.org/remotecontent?filepath=org/apache/maven/indexer/indexer-cli/6.0.0/indexer-cli-6.0.0.jar).
