### ISSUE TITLE
cannot use cursive on windows 10

### ISSUE THREAD

**Issue by henryw374** [cursive-ide/cursive#2144]
Hi, using Windows 10, I can no longer open any Leiningen project in Intellij with Cursive.

 This is a major problem because this is in a corporate environment and I don't have a choice of OS :-(

I get “Exception in plugin Cursive” with this stack trace –

 
```
java.lang.IllegalStateException: facade.login must not be null

                at cursive.leiningen.LeiningenUtil.standardArgs(LeiningenUtil.kt:115)

                at cursive.leiningen.project.LeiningenModuleBuilder$setupRootModel$1$1.run(CreateProject.kt:64)

                at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:731)

                at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:442)

                at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)

                at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)

                at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)

                at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)

                at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)

                at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$10(ApplicationImpl.java:594)

                at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)

                at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)

                at java.base/java.util.concurrent.FutureTask.run(Unknown Source)

                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

                at java.base/java.lang.Thread.run(Unknown Source)
```
 

I have tried these versions of Intellij and Cursive and get the same issue, so I’m sure its related to the Windows 10 upgrade:

 

IntelliJ IDEA 2017.3.6

IntelliJ IDEA 2018.2.4

IntelliJ IDEA 2018.3.6

IntelliJ IDEA 2019.1

 

Cursive 1.8.1

Cursive 1.8.0

jdk is 1.8.0_60_windows_x64 

Thanks,
Henry

**Comment by cursive-ide** [comment]
Hmm, I see - this is a problem in Cursive, but it looks like there might be a workaround. It seems that you have an HTTP proxy configured, but you don't have a username configured for that. If you add the username, I think that will work around this bug.

**Comment by henryw374** [comment]
Thanks. Unfortunately I cannot try this out just yet because of hardware issues. Will check once it's back and close the issue then

**Comment by henryw374** [comment]
This works. thanks
