### ISSUE TITLE
Cant open project

### ISSUE THREAD

**Issue by smogstate** [cursive-ide/cursive#2168]
Hello, opening project cause an exception. The folder exists, but i an not sure what cursive what to execute.

**Environment:**
cursive: v1.8.2-eap2-2019.1
JetBrains Toolbox 1.14.5179 (Apr 15 2019)
IntelliJ IDEA 2019.1.1 (Community Edition)
Build #IC-191.6707.61, built on April 16, 2019
JRE: 1.8.0_202-release-1483-b44 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
OS kernel linux 5.0.0-13-generic on x86_64

**Exception:**

2019-05-05 14:12:12,007 [1261943]   WARN - nal.AbstractExternalSystemTask -  
java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy101.getResolver(Unknown Source)
	at com.intellij.openapi.externalSystem.service.internal.ExternalSystemResolveProjectTask.doExecute(ExternalSystemResolveProjectTask.java:83)
	at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:165)
	at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:151)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$3.executeImpl(ExternalSystemUtil.java:559)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$3.lambda$execute$0(ExternalSystemUtil.java:399)
	at com.intellij.openapi.project.DumbServiceImpl.suspendIndexingAndRun(DumbServiceImpl.java:146)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$3.execute(ExternalSystemUtil.java:399)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$4.run(ExternalSystemUtil.java:655)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:731)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$10(ApplicationImpl.java:594)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.intellij.execution.ExecutionException: Cannot execute: /home/denis/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/191.6707.61/bin does not exist
	at com.intellij.execution.rmi.RemoteProcessSupport.acquire(RemoteProcessSupport.java:144)
	at com.intellij.openapi.externalSystem.service.RemoteExternalSystemCommunicationManager.acquire(RemoteExternalSystemCommunicationManager.java:209)
	at com.intellij.openapi.externalSystem.service.ExternalSystemFacadeManager.doCreateFacade(ExternalSystemFacadeManager.java:186)
	at com.intellij.openapi.externalSystem.service.ExternalSystemFacadeManager.doGetFacade(ExternalSystemFacadeManager.java:175)
	at com.intellij.openapi.externalSystem.service.ExternalSystemFacadeManager.doInvoke(ExternalSystemFacadeManager.java:131)
	at com.intellij.openapi.externalSystem.service.ExternalSystemFacadeManager$MyHandler.invoke(ExternalSystemFacadeManager.java:267)
	... 23 more
Caused by: com.intellij.execution.ExecutionException: Cannot execute: /home/denis/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/191.6707.61/bin does not exist
	at cursive.deps.DepsManager.enhanceRemoteProcessing(DepsSupport.kt:159)
	at com.intellij.openapi.externalSystem.service.RemoteExternalSystemCommunicationManager$2.createJavaParameters(RemoteExternalSystemCommunicationManager.java:175)
	at com.intellij.openapi.externalSystem.service.RemoteExternalSystemCommunicationManager$2.startProcess(RemoteExternalSystemCommunicationManager.java:192)
	at com.intellij.openapi.externalSystem.service.RemoteExternalSystemCommunicationManager$2.execute(RemoteExternalSystemCommunicationManager.java:185)
	at com.intellij.execution.rmi.RemoteProcessSupport.startProcess(RemoteProcessSupport.java:197)
	at com.intellij.execution.rmi.RemoteProcessSupport.acquire(RemoteProcessSupport.java:124)
	... 28 more

**Comment by smogstate** [comment]
Problem solved, added path to clojure
