### ISSUE TITLE
2019.2: the plugin com.cursiveclojure.cursive failed to save settings and has been disabled. Please restart IntelliJ IDEA

### ISSUE THREAD

**Issue by rborer** [cursive-ide/cursive#2211]
I just bumped my IntelliJ to 2019.2 with cursive 1.8.2 and am not experiencing an issue 😭. At startup everything looks fine but after 2-3 minutes, I get multiple times the red error message:

`Unable to save plugin settings: The plugin com.cursiveclojure.cursive failed to save settings and has been disabled. Please restart IntelliJ IDEA`

Then if I try to open any not already open clojure source code file, I get the following stacktrace:

```
java.lang.IllegalArgumentException: Area already instantiated for: ProjectDefault (Template) Project
at com.intellij.openapi.extensions.Extensions.instantiateArea(Extensions.java:138)
at com.intellij.openapi.project.impl.ProjectImpl.bootstrapPicoContainer(ProjectImpl.java:148)
at com.intellij.openapi.project.impl.DefaultProject$1$1.init(DefaultProject.java:74)
at com.intellij.openapi.project.impl.DefaultProject$1.init(DefaultProject.java:104)
at com.intellij.openapi.project.impl.DefaultProjectTimed.get(DefaultProjectTimed.java:34)
at com.intellij.openapi.project.impl.DefaultProject.getDelegate(DefaultProject.java:131)
at com.intellij.openapi.project.impl.DefaultProject.getComponent(DefaultProject.java:216)
at com.intellij.openapi.wm.ToolWindowManager.getInstance(ToolWindowManager.java:26)
at net.orfjackal.sbt.plugin.SbtRunnerComponent.unregisterToolWindow(SbtRunnerComponent.java:117)
at net.orfjackal.sbt.plugin.SbtRunnerComponent.disposeComponent(SbtRunnerComponent.java:98)
at com.intellij.openapi.components.impl.ComponentManagerImpl.disposeComponents(ComponentManagerImpl.java:169)
at com.intellij.openapi.project.impl.ProjectImpl.dispose(ProjectImpl.java:330)
at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:47)
at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:43)
at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:135)
at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:104)
at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:194)
at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:104)
at com.intellij.openapi.util.objectTree.ObjectTree.executeAll(ObjectTree.java:142)
at com.intellij.openapi.util.Disposer.dispose(Disposer.java:136)
at com.intellij.openapi.util.Disposer.dispose(Disposer.java:132)
at com.intellij.util.Timed.dispose(Timed.java:41)
[...]
```

When I restart IntelliJ the plugin is disabled so I have to enable it again, restart, wait on project indexing to finish, and then the same error happens after a few minutes.

I've tried to invalidate the cache without luck. Also, it's happening on 2 different projects so my guess is that it is not project specific.

Is this issue already known? What kind of information can I provide to help its diagnostic?

**Comment by cursive-ide** [comment]
I actually can't see anything in that stacktrace related to Cursive, strangely enough. It looks like it's related to the SBT plugin - does disabling that one help?

**Comment by rborer** [comment]
Shame on me I didn't notice the stacktrace was about SBT plugin :roll_eyes: 

I have disabled it and so far so good, I haven't seen this error about failure to save settings :tada: . Still, I find quite suspicious that IntelliJ reports and issue with cursive plugin and it seems to be in fact about SBT. Do you think it should be reported to Jetbrains somehow?

**Comment by tobiasadam0770** [comment]
@rborer: I had the same problem, too. Your description of this issue and @cursive-ide’s answer helped me to fix this problem, so thanks a lot.

The problem is really introduced by this SBT plugin by @luontola: https://github.com/luontola/idea-sbt-plugin

I removed it completely instead of only disabling it because in the plugin’s README says that it is unmaintained and deprecated since April 2017:

> JetBrains have recently added support for an SBT console to the IntellIJ Scala Plugin. This is now the recommended way to use SBT within IntellIJ. No new releases of this plugin are planned.

**Comment by rborer** [comment]
@tobiasadam0770 glad it helped! I wasn't aware that this plugin was not maintained anymore so I have also completely removed it. I'll now close this issue as it is definitely not related to cursive.
