### ISSUE TITLE
Stub generation fails, datomic 0.5.5951, IDEA 2018.3.6 and 2019.2

### ISSUE THREAD

**Issue by mickelangelo** [cursive-ide/cursive#2224]
```java.lang.ClassCastException: clojure.lang.Cons cannot be cast to java.lang.Comparable
	at clojure.lang.Util.compare(Util.java:153)
	at clojure.core$compare.invokeStatic(core.clj:840)
	at clojure.core$compare.invoke(core.clj:831)
	at clojure.lang.AFunction.compare(AFunction.java:51)
	at java.util.TimSort.binarySort(TimSort.java:296)
	at java.util.TimSort.sort(TimSort.java:239)
	at java.util.Arrays.sort(Arrays.java:1438)
	at clojure.core$sort.invokeStatic(core.clj:3115)
	at clojure.core$sort.invokeStatic(core.clj:3102)
	at clojure.core$sort.invoke(core.clj:3102)
	at leiningen.compile$find_namespaces_by_regex.invokeStatic(compile.clj:22)
	at leiningen.compile$find_namespaces_by_regex.invoke(compile.clj:18)
	at leiningen.compile$compilable_namespaces.invokeStatic(compile.clj:31)
	at leiningen.compile$compilable_namespaces.invoke(compile.clj:25)
	at leiningen.compile$stale_namespaces.invokeStatic(compile.clj:37)
	at leiningen.compile$stale_namespaces.invoke(compile.clj:33)
	at leiningen.compile$compile.invokeStatic(compile.clj:150)
	at leiningen.compile$compile.invoke(compile.clj:136)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at leiningen.core.main$partial_task$fn__6592.doInvoke(main.clj:284)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at leiningen.core.main$apply_task.invokeStatic(main.clj:334)
	at leiningen.core.main$apply_task.invoke(main.clj:320)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$apply.invoke(core.clj:660)
	at cursive.leiningen.hooke$run_hooks.invokeStatic(hooke.clj:49)
	at cursive.leiningen.hooke$run_hooks.invoke(hooke.clj:48)
	at cursive.leiningen.hooke$prepare_for_hooks$fn__1128$fn__1129.doInvoke(hooke.clj:57)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at leiningen.core.eval$run_prep_tasks.invokeStatic(eval.clj:51)
	at leiningen.core.eval$run_prep_tasks.invoke(eval.clj:43)
	at leiningen.core.eval$prep.invokeStatic(eval.clj:86)
	at leiningen.core.eval$prep.invoke(eval.clj:73)
	at leiningen.core.eval$eval_in_project.invokeStatic(eval.clj:363)
	at leiningen.core.eval$eval_in_project.invoke(eval.clj:357)
	at leiningen.core.eval$eval_in_project.invokeStatic(eval.clj:361)
	at leiningen.core.eval$eval_in_project.invoke(eval.clj:357)
	at cursive.leiningen.eval$eval_details$fn__1678.invoke(eval.clj:44)
	at cursive.leiningen.eval$eval_details.invokeStatic(eval.clj:37)
	at cursive.leiningen.eval$eval_details.invoke(eval.clj:14)
	at clojure.lang.Var.invoke(Var.java:388)
	at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke(ClojureRuntimeShimImpl.java:124)
	at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke(ClojureRuntimeShimImpl.java:117)
	at cursive.shim.ShimBootstrap$Shim.apply(ShimBootstrap.java:53)
	at cursive.stubs$lein_parameters$reify__6786.invoke(stubs.clj:251)
	at cursive.shim.ShimProvider.withShim(Shim.kt:99)
	at cursive.stubs$lein_parameters.invoke(stubs.clj:247)
	at cursive.stubs$generate_stubs$fn__6800$process__6801.invoke(stubs.clj:329)
	at cursive.stubs$generate_stubs$fn__6800.invoke(stubs.clj:363)
	at cursive.task$backgroundable$reify__6594.run(task.clj:12)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by cursive-ide** [comment]
Closing this because it seems the same as #2225.
