### ISSUE TITLE
Java lang not resolved

### ISSUE THREAD

**Issue by tuh8888** [cursive-ide/cursive#2254]
Java classes which I believe are automatically imported from clojure like java.lang.Integer are not being resolved. The program runs fine, but I've lost completion for these classes

IntelliJ Version: 2019.3 EAP
Cursive Version: 1.9.0-eap6-2019.3
OS: Ubuntu 19.10

**Comment by d-t-w** [comment]
I've just discovered the same after updating to Intellij 2019.3 and Cursive 1.9.1-eap4-2019.3.

When I start a REPL I no longer get auto-import suggestions for any Java classes (doesn't matter if they're java.lang or otherwise).

E.g. 
![image](https://user-images.githubusercontent.com/2832467/74492718-e6a14600-4f23-11ea-989b-ca5299ab2a25.png)

Would normally offer to import java.util.UUID with option-enter. After I updated (yesterday) no longer offers.

**Comment by ivarref** [comment]
I'm getting the following stacktrace when I type in `(UUID/)` after updating to Ultimate `2019.3.3`:

```
In file: file:///home/ire/code/learn/bah/src/bah/core.clj

java.lang.NullPointerException
	at cursive.annotator$annotate_class_import$reify__6072.getReferenceName(annotator.clj:164)
	at com.intellij.codeInsight.daemon.impl.quickfix.ImportClassFixBase.calcClassesToImport(ImportClassFixBase.java:120)
	at com.intellij.codeInsight.daemon.impl.quickfix.ImportClassFixBase.<init>(ImportClassFixBase.java:60)
	at cursive.annotator$annotate_class_import$reify__6072.<init>(annotator.clj:160)
	at cursive.annotator$annotate_class_import.invokeStatic(annotator.clj:157)
	at cursive.annotator$annotate_class_import.invoke(annotator.clj:136)
	at cursive.annotator$annotate_import_require.invokeStatic(annotator.clj:274)
	at cursive.annotator$annotate_import_require.invoke(annotator.clj:268)
	at cursive.annotator$annotate_unresolved.invokeStatic(annotator.clj:277)
	at cursive.annotator$annotate_unresolved.invoke(annotator.clj:276)
	at cursive.annotator$annotate_symbol.invokeStatic(annotator.clj:365)
	at cursive.annotator$annotate_symbol.invoke(annotator.clj:349)
	at cursive.annotator$fn__6195.invokeStatic(annotator.clj:395)
	at cursive.annotator$fn__6195.invoke(annotator.clj:389)
	at cursive.annotator$fn__6180$G__6175__6187.invoke(annotator.clj:386)
	at cursive.annotator.ClojureAnnotator.annotate(annotator.clj:410)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:126)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:108)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:351)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:285)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:93)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:282)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:227)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:997)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:157)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by imrekoszo** [comment]
Reproduced in a deps project with 2019.3.3 and latest Cursive eap

**Comment by cursive-ide** [comment]
I've moved the UUID not importing issue over to #2310, and I've fixed that stacktrace for the next EAP.

**Comment by cursive-ide** [comment]
@tuh8888 Most of this discussion has been unrelated to your original issue - is that still a problem for you?
