### ISSUE TITLE
REPL does not start

### ISSUE THREAD

**Issue by CarlosTrigosoS** [cursive-ide/cursive#2259]
Hello I just installed Cursive. After checking and re-checking all my settings, network, machine, Java installation, IntelliJ installation, Java versions, etc. I keep getting the following error (see error trace below).

I also made sure I have localhost and DNS resolution working. 

Java versions tried 13 and 8 (AdoptJDK)

IntelliJ Ultimate latest version.

Please help.

Carlos Trigoso
------------------------------

Exception in thread "main" Syntax error compiling at (C:\Users\Carlos Trigoso\AppData\Local\Temp\form-init10736058101244520561.clj:1:118).
	at clojure.lang.Compiler.load(Compiler.java:7647)
	at clojure.lang.Compiler.loadFile(Compiler.java:7573)
	at clojure.main$load_script.invokeStatic(main.clj:452)
	at clojure.main$init_opt.invokeStatic(main.clj:454)
	at clojure.main$init_opt.invoke(main.clj:454)
	at clojure.main$initialize.invokeStatic(main.clj:485)
	at clojure.main$null_opt.invokeStatic(main.clj:519)
	at clojure.main$null_opt.invoke(main.clj:516)
	at clojure.main$main.invokeStatic(main.clj:598)
	at clojure.main$main.doInvoke(main.clj:561)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:37)
Caused by: java.net.ConnectException: connect: Address is invalid on local machine, or port is not valid on remote machine
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)

**Comment by CarlosTrigosoS** [comment]
Hello, Please ignore the previous issue report. I started Clojure directly using Lein and the error is the same on my computer. Therefore the problem is not related to Cursive or IntelliJ. I will close this report.
Thank you
Carlos Trigoso
