### ISSUE TITLE
java.util.IllegalFormatConversionException: d != java.lang.String on IntelliJ 2019.2.4/2019.3 + cursive 1.9.0-2019.2/2019.3

### ISSUE THREAD

**Issue by PavlosMelissinos** [cursive-ide/cursive#2276]
I'm on IntelliJ IDEA 2019.2.4 and cursive is 1.9.0-2019.2

I'm getting the following error when I start a new Clojure REPL in IntelliJ for a tools.deps project

```
Starting nREPL server...
/usr/lib/jvm/java-1.11.0-openjdk-amd64/bin/java -javaagent:~/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/192.7142.36/lib/idea_rt.jar=36687:~/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/192.7142.36/bin -Dfile.encoding=UTF-8 -classpath /usr/lib/jvm/java-1.11.0-openjdk-amd64!/java.base:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/java.compiler:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/java.datatransfer:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/java.desktop:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/java.instrument:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/java.logging:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/java.management:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/java.management.rmi:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/java.naming:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/java.net.http:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/java.prefs:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/java.rmi:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/java.scripting:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/java.se:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/java.security.jgss:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/java.security.sasl:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/java.smartcardio:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/java.sql:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/java.sql.rowset:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/java.transaction.xa:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/java.xml:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/java.xml.crypto:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.accessibility:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.aot:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.attach:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.charsets:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.compiler:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.crypto.cryptoki:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.crypto.ec:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.dynalink:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.editpad:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.hotspot.agent:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.httpserver:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.internal.ed:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.internal.jvmstat:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.internal.le:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.internal.opt:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.internal.vm.ci:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.internal.vm.compiler:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.internal.vm.compiler.management:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.jartool:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.javadoc:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.jcmd:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.jconsole:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.jdeps:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.jdi:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.jdwp.agent:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.jfr:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.jlink:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.jshell:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.jsobject:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.jstatd:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.localedata:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.management:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.management.agent:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.management.jfr:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.naming.dns:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.naming.rmi:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.net:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.pack:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.rmic:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.scripting.nashorn:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.scripting.nashorn.shell:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.sctp:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.security.auth:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.security.jgss:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.unsupported:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.unsupported.desktop:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.xml.dom:/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.zipfs:~/.gitlibs/libs/bsq/vittle-standards/9280e09f9244ab52cb97966b9036f7c13e6a36d5:~/.m2/repository/com/adobe/granite/analytics/java-client/1.1/java-client-1.1.jar:~/.m2/repository/com/github/haifengl/smile-interpolation/1.5.2/smile-interpolation-1.5.2.jar:~/.m2/repository/org/clojure/clojure/1.9.0/clojure-1.9.0.jar:~/.m2/repository/joda-time/joda-time/2.9.7/joda-time-2.9.7.jar:~/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar:~/.m2/repository/io/github/java-diff-utils/java-diff-utils/4.0/java-diff-utils-4.0.jar:~/.m2/repository/org/clojure/tools.analyzer/0.6.9/tools.analyzer-0.6.9.jar:~/.m2/repository/org/apache/poi/poi/3.17/poi-3.17.jar:~/.m2/repository/org/apache/commons/commons-compress/1.8/commons-compress-1.8.jar:~/.m2/repository/com/auth0/java-jwt/2.2.1/java-jwt-2.2.1.jar:~/.m2/repository/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar:~/.m2/repository/com/draines/postal/2.0.3/postal-2.0.3.jar:~/.m2/repository/org/clojure/tools.logging/0.3.1/tools.logging-0.3.1.jar:~/.m2/repository/org/clojure/core.specs.alpha/0.1.24/core.specs.alpha-0.1.24.jar:~/.m2/repository/org/tukaani/xz/1.5/xz-1.5.jar:~/.m2/repository/com/google/oauth-client/google-oauth-client/1.22.0/google-oauth-client-1.22.0.jar:~/.m2/repository/lambdaisland/kaocha/0.0-529/kaocha-0.0-529.jar:~/.m2/repository/generateme/fastmath/1.2.0/fastmath-1.2.0.jar:~/.m2/repository/org/apache/poi/poi-ooxml-schemas/3.17/poi-ooxml-schemas-3.17.jar:~/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.9.9/jackson-databind-2.9.9.jar:~/.m2/repository/expound/expound/0.5.0/expound-0.5.0.jar:~/.m2/repository/org/clojure/spec.alpha/0.2.176/spec.alpha-0.2.176.jar:~/.m2/repository/org/clojure/tools.cli/0.4.1/tools.cli-0.4.1.jar:~/.m2/repository/clojurewerkz/urly/1.0.0/urly-1.0.0.jar:~/.m2/repository/webjure/json-schema/0.7.4/json-schema-0.7.4.jar:~/.m2/repository/mvxcvi/puget/1.1.2/puget-1.1.2.jar:~/.m2/repository/de/sciss/jwave/1.0.3/jwave-1.0.3.jar:~/.m2/repository/com/google/apis/google-api-services-analyticsreporting/v4-rev7-1.22.0/google-api-services-analyticsreporting-v4-rev7-1.22.0.jar:~/.m2/repository/cider/orchard/0.3.4/orchard-0.3.4.jar:~/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar:~/.m2/repository/com/taoensso/encore/2.91.0/encore-2.91.0.jar:~/.m2/repository/org/clojure/tools.trace/0.7.10/tools.trace-0.7.10.jar:~/.m2/repository/org/apache/httpcomponents/httpasyncclient/4.1.3/httpasyncclient-4.1.3.jar:~/.m2/repository/org/clojure/tools.analyzer.jvm/0.7.0/tools.analyzer.jvm-0.7.0.jar:~/.m2/repository/net/incongru/watchservice/barbary-watchservice/1.0/barbary-watchservice-1.0.jar:~/.m2/repository/net/jpountz/lz4/lz4/1.3/lz4-1.3.jar:~/.m2/repository/com/github/haifengl/smile-math/1.5.2/smile-math-1.5.2.jar:~/.m2/repository/io/jsonwebtoken/jjwt/0.5/jjwt-0.5.jar:~/.m2/repository/org/apache/commons/commons-math3/3.6.1/commons-math3-3.6.1.jar:~/.m2/repository/org/clojure/tools.macro/0.1.1/tools.macro-0.1.1.jar:~/.m2/repository/lambdaisland/deep-diff/0.0-47/deep-diff-0.0-47.jar:~/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-cbor/2.9.0/jackson-dataformat-cbor-2.9.0.jar:~/.m2/repository/com/gfredericks/test.chuck/0.2.9/test.chuck-0.2.9.jar:~/.m2/repository/org/flatland/useful/0.10.6/useful-0.10.6.jar:~/.m2/repository/clj-fuzzy/clj-fuzzy/0.4.1/clj-fuzzy-0.4.1.jar:~/.m2/repository/org/iq80/snappy/snappy/0.4/snappy-0.4.jar:~/.m2/repository/io/aviso/pretty/0.1.33/pretty-0.1.33.jar:~/.m2/repository/stax/stax-api/1.0.1/stax-api-1.0.1.jar:~/.m2/repository/cljfmt/cljfmt/0.6.1/cljfmt-0.6.1.jar:~/.m2/repository/rewrite-clj/rewrite-clj/0.6.0/rewrite-clj-0.6.0.jar:~/.m2/repository/honeysql/honeysql/0.8.0/honeysql-0.8.0.jar:~/.m2/repository/org/clojure/data.generators/0.1.2/data.generators-0.1.2.jar:~/.m2/repository/slingshot/slingshot/0.12.2/slingshot-0.12.2.jar:~/.m2/repository/org/apache/httpcomponents/httpcore-nio/4.4.6/httpcore-nio-4.4.6.jar:~/.m2/repository/commons-io/commons-io/2.5/commons-io-2.5.jar:~/.m2/repository/com/google/http-client/google-http-client-jackson2/1.22.0/google-http-client-jackson2-1.22.0.jar:~/.m2/repository/org/postgresql/postgresql/42.2.5/postgresql-42.2.5.jar:~/.m2/repository/org/clojure/tools.namespace/0.3.0-alpha4/tools.namespace-0.3.0-alpha4.jar:~/.m2/repository/fipp/fipp/0.6.17/fipp-0.6.17.jar:~/.m2/repository/refactor-nrepl/refactor-nrepl/2.4.0/refactor-nrepl-2.4.0.jar:~/.m2/repository/org/eclipse/jgit/org.eclipse.jgit/4.4.1.201607150455-r/org.eclipse.jgit-4.4.1.201607150455-r.jar:~/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.9.9/jackson-core-2.9.9.jar:~/.m2/repository/com/google/guava/guava-jdk5/17.0/guava-jdk5-17.0.jar:~/.m2/repository/clj-time/clj-time/0.13.0/clj-time-0.13.0.jar:~/.m2/repository/com/mchange/c3p0/0.9.5.4/c3p0-0.9.5.4.jar:~/.m2/repository/aero/aero/1.1.3/aero-1.1.3.jar:~/.m2/repository/clj-http/clj-http/3.9.1/clj-http-3.9.1.jar:~/.m2/repository/lambdaisland/tools.namespace/0.0-234/tools.namespace-0.0-234.jar:~/.m2/repository/org/apache/httpcomponents/httpcore/4.4.11/httpcore-4.4.11.jar:~/.m2/repository/com/github/haifengl/smile-core/1.5.2/smile-core-1.5.2.jar:~/.m2/repository/org/rosuda/REngine/Rserve/1.8.1/Rserve-1.8.1.jar:~/.m2/repository/org/apache/httpcomponents/httpclient-cache/4.5.5/httpclient-cache-4.5.5.jar:~/.m2/repository/org/slf4j/slf4j-simple/1.7.25/slf4j-simple-1.7.25.jar:~/.m2/repository/mvxcvi/arrangement/1.2.0/arrangement-1.2.0.jar:~/.m2/repository/instaparse/instaparse/1.3.6/instaparse-1.3.6.jar:~/.m2/repository/integrant/integrant/0.6.3/integrant-0.6.3.jar:~/.m2/repository/org/clojure/math.numeric-tower/0.0.4/math.numeric-tower-0.0.4.jar:~/.m2/repository/com/google/http-client/google-http-client/1.22.0/google-http-client-1.22.0.jar:~/.m2/repository/clj-tuple/clj-tuple/0.2.2/clj-tuple-0.2.2.jar:~/.m2/repository/com/sun/mail/javax.mail/1.5.5/javax.mail-1.5.5.jar:~/.m2/repository/clojure-humanize/clojure-humanize/0.2.2/clojure-humanize-0.2.2.jar:~/.m2/repository/com/taoensso/truss/1.5.0/truss-1.5.0.jar:~/.m2/repository/software/amazon/ion/ion-java/1.0.2/ion-java-1.0.2.jar:~/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.9.0/jackson-annotations-2.9.0.jar:~/.m2/repository/hiccup/hiccup/1.0.5/hiccup-1.0.5.jar:~/.m2/repository/org/apache/xmlbeans/xmlbeans/2.6.0/xmlbeans-2.6.0.jar:~/.m2/repository/riddley/riddley/0.1.12/riddley-0.1.12.jar:~/.m2/repository/progrock/progrock/0.1.2/progrock-0.1.2.jar:~/.m2/repository/com/googlecode/java-diff-utils/diffutils/1.3.0/diffutils-1.3.0.jar:~/.m2/repository/dk/ative/docjure/1.13.0/docjure-1.13.0.jar:~/.m2/repository/org/apache/poi/poi-ooxml/3.17/poi-ooxml-3.17.jar:~/.m2/repository/org/clojure/java.classpath/0.3.0/java.classpath-0.3.0.jar:~/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:~/.m2/repository/com/google/guava/guava/11.0.1/guava-11.0.1.jar:~/.m2/repository/viebel/codox-klipse-theme/0.0.1/codox-klipse-theme-0.0.1.jar:~/.m2/repository/com/amazonaws/jmespath-java/1.11.635/jmespath-java-1.11.635.jar:~/.m2/repository/org/clojure/algo.generic/0.1.2/algo.generic-0.1.2.jar:~/.m2/repository/com/amazonaws/aws-java-sdk-core/1.11.635/aws-java-sdk-core-1.11.635.jar:~/.m2/repository/orchestra/orchestra/2019.02.06-1/orchestra-2019.02.06-1.jar:~/.m2/repository/org/clojure/data.csv/0.1.4/data.csv-0.1.4.jar:~/.m2/repository/com/taoensso/timbre/4.10.0/timbre-4.10.0.jar:~/.m2/repository/org/clojure/java.jdbc/0.7.2/java.jdbc-0.7.2.jar:~/.m2/repository/quoin/quoin/0.1.2/quoin-0.1.2.jar:~/.m2/repository/com/mchange/mchange-commons-java/0.2.15/mchange-commons-java-0.2.15.jar:~/.m2/repository/com/google/http-client/google-http-client-gson/1.22.0/google-http-client-gson-1.22.0.jar:~/.m2/repository/spectacles/spectacles/0.3.3/spectacles-0.3.3.jar:~/.m2/repository/cider/cider-nrepl/0.19.0-SNAPSHOT/cider-nrepl-0.19.0-SNAPSHOT.jar:~/.m2/repository/org/rosuda/REngine/REngine/2.1.0/REngine-2.1.0.jar:~/.m2/repository/org/apache/httpcomponents/httpclient/4.5.9/httpclient-4.5.9.jar:~/.m2/repository/org/clojure/core.rrb-vector/0.0.14/core.rrb-vector-0.0.14.jar:~/.m2/repository/prismatic/schema/1.1.2/schema-1.1.2.jar:~/.m2/repository/net/jafama/jafama/2.3.1/jafama-2.3.1.jar:~/.m2/repository/org/clojure/math.combinatorics/0.1.3/math.combinatorics-0.1.3.jar:~/.m2/repository/robert/hooke/1.3.0/hooke-1.3.0.jar:~/.m2/repository/hickory/hickory/0.7.1/hickory-0.7.1.jar:~/.m2/repository/net/java/dev/jna/jna/3.2.2/jna-3.2.2.jar:~/.m2/repository/cheshire/cheshire/5.8.0/cheshire-5.8.0.jar:~/.m2/repository/tigris/tigris/0.1.1/tigris-0.1.1.jar:~/.m2/repository/com/andrewmcveigh/cljs-time/0.5.1/cljs-time-0.5.1.jar:~/.m2/repository/org/clojure/core.match/0.3.0-alpha4/core.match-0.3.0-alpha4.jar:~/.m2/repository/cljs-tooling/cljs-tooling/0.3.1/cljs-tooling-0.3.1.jar:~/.m2/repository/org/clojure/tools.reader/1.3.2/tools.reader-1.3.2.jar:~/.m2/repository/compliment/compliment/0.3.8/compliment-0.3.8.jar:~/.m2/repository/org/tcrawley/dynapath/1.0.0/dynapath-1.0.0.jar:~/.m2/repository/com/google/api-client/google-api-client/1.22.0/google-api-client-1.22.0.jar:~/.m2/repository/org/jsoup/jsoup/1.9.2/jsoup-1.9.2.jar:~/.m2/repository/com/taoensso/nippy/2.12.2/nippy-2.12.2.jar:~/.m2/repository/potemkin/potemkin/0.4.5/potemkin-0.4.5.jar:~/.m2/repository/nrepl/nrepl/0.5.3/nrepl-0.5.3.jar:~/.m2/repository/org/apache/commons/commons-collections4/4.1/commons-collections4-4.1.jar:~/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar:~/.m2/repository/org/clojure/test.check/0.9.0/test.check-0.9.0.jar:~/.m2/repository/thunknyc/profile/0.5.2/profile-0.5.2.jar:~/.m2/repository/me/raynes/conch/0.8.0/conch-0.8.0.jar:~/.m2/repository/com/github/virtuald/curvesapi/1.04/curvesapi-1.04.jar:~/.m2/repository/amazonica/amazonica/0.3.146/amazonica-0.3.146.jar:~/.m2/repository/me/raynes/fs/1.4.6/fs-1.4.6.jar:~/.m2/repository/javax/mail/javax.mail-api/1.5.5/javax.mail-api-1.5.5.jar:~/.m2/repository/org/clojure/core.memoize/0.5.9/core.memoize-0.5.9.jar:~/.m2/repository/com/stuartsierra/dependency/0.2.0/dependency-0.2.0.jar:~/.m2/repository/hawk/hawk/0.2.11/hawk-0.2.11.jar:~/.m2/repository/tech/droit/clj-diff/1.0.1/clj-diff-1.0.1.jar:~/.m2/repository/com/github/haifengl/smile-graph/1.5.2/smile-graph-1.5.2.jar:~/.m2/repository/com/nexmo/client/3.4.1/client-3.4.1.jar:~/.m2/repository/org/clojure/data.priority-map/0.0.7/data.priority-map-0.0.7.jar:~/.m2/repository/nrepl/bencode/1.0.0/bencode-1.0.0.jar:~/.m2/repository/org/apache/httpcomponents/httpmime/4.5.5/httpmime-4.5.5.jar:~/.m2/repository/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar:~/.m2/repository/org/clojure/core.cache/0.6.5/core.cache-0.6.5.jar:~/.m2/repository/meta-merge/meta-merge/1.0.0/meta-merge-1.0.0.jar:~/.m2/repository/rewrite-cljs/rewrite-cljs/0.4.4/rewrite-cljs-0.4.4.jar:~/.m2/repository/org/ow2/asm/asm-all/4.2/asm-all-4.2.jar:~/.m2/repository/com/amazonaws/aws-java-sdk-kms/1.11.635/aws-java-sdk-kms-1.11.635.jar:~/.m2/repository/org/clojure/core.async/0.4.474/core.async-0.4.474.jar:~/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-smile/2.9.0/jackson-dataformat-smile-2.9.0.jar:~/.m2/repository/org/clojure/data.codec/0.1.0/data.codec-0.1.0.jar:~/.m2/repository/javax/xml/bind/jaxb-api/2.3.0/jaxb-api-2.3.0.jar:~/.m2/repository/com/github/haifengl/smile-data/1.5.2/smile-data-1.5.2.jar:~/.m2/repository/com/google/code/gson/gson/2.3.1/gson-2.3.1.jar:~/.m2/repository/com/amazonaws/aws-java-sdk-s3/1.11.635/aws-java-sdk-s3-1.11.635.jar:~/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/192.7142.36.plugins/clojure-plugin/lib/nrepl-0.6.0.jar clojure.main -i /tmp/form-init15047303330478184867.clj
Exception in thread "main" java.util.IllegalFormatConversionException: d != java.lang.String, compiling:(/tmp/form-init15047303330478184867.clj:1:1)
	at clojure.lang.Compiler.load(Compiler.java:7526)
	at clojure.lang.Compiler.loadFile(Compiler.java:7452)
	at clojure.main$load_script.invokeStatic(main.clj:278)
	at clojure.main$init_opt.invokeStatic(main.clj:280)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invokeStatic(main.clj:311)
	at clojure.main$null_opt.invokeStatic(main.clj:345)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: java.util.IllegalFormatConversionException: d != java.lang.String
	at java.base/java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4426)
	at java.base/java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2938)
	at java.base/java.util.Formatter$FormatSpecifier.print(Formatter.java:2892)
	at java.base/java.util.Formatter.format(Formatter.java:2673)
	at java.base/java.util.Formatter.format(Formatter.java:2609)
	at java.base/java.lang.String.format(String.java:2897)
	at clojure.core$format.invokeStatic(core.clj:5684)
	at clojure.core$format.doInvoke(core.clj:5678)
	at clojure.lang.RestFn.invoke(RestFn.java:439)
	at nrepl.cmdline$run$fn__1269.invoke(cmdline.clj:274)
	at nrepl.cmdline$run.invokeStatic(cmdline.clj:273)
	at nrepl.cmdline$run.invoke(cmdline.clj:240)
	at nrepl.cmdline$_main.invokeStatic(cmdline.clj:296)
	at nrepl.cmdline$_main.doInvoke(cmdline.clj:293)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at user$eval1277.invokeStatic(form-init15047303330478184867.clj:1)
	at user$eval1277.invoke(form-init15047303330478184867.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7052)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	... 12 more
No nREPL ack received
Connecting to local nREPL server...
```

The same seems to happen on IntelliJ 2019.3 RC

**Comment by cursive-ide** [comment]
I think this is caused by you having an earlier version of nREPL on your classpath ahead of the one injected by Cursive. That stacktrace definitely doesn't match the version that Cursive ships. I'll see if I can reproduce this.

**Comment by cursive-ide** [comment]
As a workaround, if you can figure out where nrepl 0.5.3 is being brought into your project and exclude it from there, this should work. Looking at your classpath it looks like you have CIDER stuff on there (cider-nrepl, refactor-nrepl), do you have those in your user deps file, perhaps? Removing those might help this.

**Comment by cursive-ide** [comment]
I just managed to reproduce this by adding `cider/cider-nrepl:0.19.0-SNAPSHOT` to a project. So if you remove that, you should be good. I'll also fix this, of course.

**Comment by PavlosMelissinos** [comment]
Neither my system-level nor my user-level deps file contain any repl/cider/nrepl entries. They're the default ones that come with clojure 1.10. Everything in user deps.edn is commented out, for instance.

I've tried to use emacs in the past, maybe that might have something to do with this? I'm not sure how to investigate though. I've also tried to delete the project's .cpcache directory in order to rebuild it but I'm getting the same error.

I've rolled back to cursive 1.8.2 for the time being, which works fine: https://cursive-ide.com/userguide/#downgrading-cursive

**Comment by cursive-ide** [comment]
I'm not sure where they're coming from, but they're definitely present in your classpath somewhere:
```
/usr/lib/jvm/java-1.11.0-openjdk-amd64/bin/java -javaagent
~/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/192.7142.36/lib/idea_rt.jar=36687
~/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/192.7142.36/bin -Dfile.encoding=UTF-8 -classpath /usr/lib/jvm/java-1.11.0-openjdk-amd64!/java.base
/usr/lib/jvm/java-1.11.0-openjdk-amd64!/java.compiler
/usr/lib/jvm/java-1.11.0-openjdk-amd64!/java.datatransfer
...etc etc...
/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.xml.dom
/usr/lib/jvm/java-1.11.0-openjdk-amd64!/jdk.zipfs
~/.gitlibs/libs/bsq/vittle-standards/9280e09f9244ab52cb97966b9036f7c13e6a36d5
~/.m2/repository/com/adobe/granite/analytics/java-client/1.1/java-client-1.1.jar
~/.m2/repository/com/github/haifengl/smile-interpolation/1.5.2/smile-interpolation-1.5.2.jar
...etc etc...
~/.m2/repository/refactor-nrepl/refactor-nrepl/2.4.0/refactor-nrepl-2.4.0.jar
...etc etc...
~/.m2/repository/cider/cider-nrepl/0.19.0-SNAPSHOT/cider-nrepl-0.19.0-SNAPSHOT.jar
...etc etc...
~/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/192.7142.36.plugins/clojure-plugin/lib/nrepl-0.6.0.jar clojure.main -i /tmp/form-init15047303330478184867.clj
```
You should be able to see this in your Deps toolwindow by expanding out the dependencies tiree like [this](https://cursive-ide.com/userguide/eap/deps.html#viewing-your-project-dependencies).

**Comment by PavlosMelissinos** [comment]
Oh you're right, the culprit seems to be [generateme/fastmath](https://github.com/generateme/fastmath/blob/v1.2.0/project.clj#L20)

Thanks a lot :)

![image](https://user-images.githubusercontent.com/388545/69615703-02d8c980-103e-11ea-9e46-c948cb06652a.png)
