### ISSUE TITLE
Cannot create or import deps.edn project

### ISSUE THREAD

**Issue by mhavrlent** [cursive-ide/cursive#2332]
I cannot create or import any deps.edn project.
I'm instructed by Cursive plugin to download tools.deps in Settings, but the Refresh button is not working and there is no version in the drop-down to choose from:
![image](https://user-images.githubusercontent.com/11587892/75876259-9c6dff00-5e15-11ea-92ed-3250fefe0dbc.png)

There is no error message in the logs regarding the Refresh functionality, but in Wireshark I can see the request is failing on 501 as it requires HTTPS instead of HTTP. Is there something wrong with my maven settings.xml file?

![image](https://user-images.githubusercontent.com/11587892/75876823-b1975d80-5e16-11ea-9a46-c7be8fc12cef.png)

Error log:
`com.intellij.execution.ExecutionException: Cannot execute, please download tools.deps in Settings
	at cursive.deps.DepsProjectsManager$Companion.classpath(DepsSupport.kt:162)
	at cursive.deps.DepsProjectsManager$Companion.resourceConfigFile(DepsSupport.kt:125)
	at cursive.deps.DepsProjectsManager$Companion.configFiles(DepsSupport.kt:81)
	at cursive.deps.DepsProjectDetails.doGetDetails(Project.kt:158)
	at cursive.deps.DepsProjectDetails.doGetDetails(Project.kt:84)
	at cursive.build.BuildSystemProjectDetails.getProjectDetails(BuildSystem.kt:42)
	at cursive.build.BuildSystemProjectsManager$reimportAllProjects$$inlined$synchronized$lambda$1.run(BuildSystemManager.kt:139)
	at cursive.build.BuildSystemUtil$runTask$1$1.run(BuildSystemUtil.kt:93)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:888)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.lambda$run$0(CoreProgressManager.java:402)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:402)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-03-04 12:31:45,443 [  22582]  ERROR - #cursive.build.BuildSystemUtil - IntelliJ IDEA 2019.3.1  Build #IU-193.5662.53 
2020-03-04 12:31:45,443 [  22582]  ERROR - #cursive.build.BuildSystemUtil - JDK: 11.0.5; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2020-03-04 12:31:45,443 [  22582]  ERROR - #cursive.build.BuildSystemUtil - OS: Windows 10 
2020-03-04 12:31:45,455 [  22594]  ERROR - #cursive.build.BuildSystemUtil - Plugin to blame: Cursive version: 1.9.0-2019.3 
2020-03-04 12:31:45,455 [  22594]  ERROR - #cursive.build.BuildSystemUtil - Last Action:  
2020-03-04 12:31:45,839 [  22978]   INFO - CompilerWorkspaceConfiguration - Available processors: 12 
2020-03-04 12:31:56,266 [  33405]   INFO - rationStore.ComponentStoreImpl - Registering unknown macros a.b.c in component DatabaseSettings 
2020-03-04 12:31:56,414 [  33553]   INFO - tellij.openapi.util.IconLoader - replace '/actions/sync.png' with 'AllIcons.Actions.Refresh' 
2020-03-04 12:31:56,416 [  33555]   WARN - ystem.impl.ActionPopupMenuImpl - 1648ms to fill popup menu ProjectViewPopup 
2020-03-04 12:31:56,463 [  33602]   INFO - tellij.openapi.util.IconLoader - replace '/actions/sync.png' with 'AllIcons.Actions.Refresh' 
2020-03-04 12:31:57,784 [  34923]   WARN - ConfigurableExtensionPointUtil - ignore deprecated groupId: language for id: preferences.language.Kotlin.scripting 
2020-03-04 12:31:58,650 [  35789]   INFO - j.ide.plugins.RepositoryHelper - using cached plugin list (updated at 2020-03-04 12:29 PM) 
2020-03-04 12:31:58,983 [  36122]   INFO - j.ide.plugins.RepositoryHelper - using cached plugin list (updated at 2020-03-04 12:29 PM) 
2020-03-04 12:36:10,318 [ 287457]   WARN - ConfigurableExtensionPointUtil - ignore deprecated groupId: language for id: preferences.language.Kotlin.scripting 
2020-03-04 12:36:10,340 [ 287479]   WARN - ess.util.ProgressIndicatorBase - This progress indicator is indeterminate, this may lead to visual inconsistency. Please call setIndeterminate(false) before you start progress.
com.intellij.openapi.project.impl.ProjectImpl.setProgressDuringInit(ProjectImpl.java:311) 
2020-03-04 12:36:10,430 [ 287569]   WARN - ConfigurableExtensionPointUtil - ignore deprecated groupId: language for id: preferences.language.Kotlin.scripting 
2020-03-04 12:36:12,690 [ 289829]   INFO - j.ide.actions.RevealFileAction - 
Exit code 1 
2020-03-04 12:36:13,256 [ 290395]   INFO - rationStore.ComponentStoreImpl - Saving appFileTypeManager took 11 ms 
2020-03-04 12:36:13,677 [ 290816]   WARN - com.intellij.util.xmlb.Binding - no accessors for class scala.collection.mutable.HashMap 
2020-03-04 12:36:13,765 [ 290904]   INFO - rationStore.ComponentStoreImpl - Saving Project (name=clojure-deps-test, containerState=ACTIVE, componentStore=C:\Users\mipas\work\git\my\clojure-deps-test) Play2NestedBuildFilesCache took 30 ms, RunManager took 38 ms, XDebuggerManager took 15 ms 
2020-03-04 12:37:14,722 [ 351861]   WARN - ConfigurableExtensionPointUtil - ignore deprecated groupId: language for id: preferences.language.Kotlin.scripting 
2020-03-04 12:37:15,368 [ 352507]   INFO - j.ide.plugins.RepositoryHelper - using cached plugin list (updated at 2020-03-04 12:29 PM) 
2020-03-04 12:37:27,723 [ 364862]   WARN - ConfigurableExtensionPointUtil - ignore deprecated groupId: language for id: preferences.language.Kotlin.scripting 
2020-03-04 12:37:30,608 [ 367747]   INFO - j.ide.actions.RevealFileAction - 
Exit code 1 
2020-03-04 12:37:31,108 [ 368247]   INFO - rationStore.ComponentStoreImpl - Saving applibraryTable took 22 ms 
`

**IntelliJ version:** 
IntelliJ IDEA 2019.3.1 (Ultimate Edition)
Build #IU-193.5662.53, built on December 18, 2019
Runtime version: 11.0.5+10-b520.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Cursive version:**
1.9.0-2019.3

**Comment by cursive-ide** [comment]
See [this post](https://groups.google.com/d/msg/cursive/4qamAMxbo00/e-RD39o9HAAJ) on the mailing list for a workaround for this problem. The fix is in the latest EAP and should be in a stable build very soon.
