### ISSUE TITLE
[Deps] Sub-modules with same name do not resolve correctly in IntelliJ

### ISSUE THREAD

**Issue by boschi** [cursive-ide/cursive#2391]
When you have a Deps project that contains sub-modules, and they have the same name internally, they do not resolve correctly in IntelliJ as modules nor source-folders.
Example:

* Dir structure:
- **module-1/**
-- api/
--- deps.edn
-- impl/
--- deps.edn
- **module-2/**
-- api/
--- deps.edn
-- impl/
--- deps.edn

I would expect they to get resolved to IntelliJ Modules as:
- module-1/api  (module-1/api)
- module-1/impl  (module-1/impl)
- module-2/api  (module-2/api)
- module-2/impl  (module-2/impl)

However only the first module is created in the IntelliJ project, and the other one is ignored, even being displayed in the "Clojure Deps" tab:
- api  (module-1/api)
- impl  (module-1/impl)

**Comment by boschi** [comment]
I see this exception in the IntelliJ's log:
```
2020-06-23 09:27:02,339 [90816468]  ERROR - .impl.ModifiableModelCommitter - IntelliJ IDEA 2020.1.2  Build #IC-201.7846.76 
2020-06-23 09:27:02,339 [90816468]  ERROR - .impl.ModifiableModelCommitter - JDK: 11.0.7; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2020-06-23 09:27:02,340 [90816469]  ERROR - .impl.ModifiableModelCommitter - OS: Linux 
2020-06-23 09:27:02,340 [90816469]  ERROR - .impl.ModifiableModelCommitter - Plugin to blame: Cursive version: 1.9.2-eap7-2020.1 
2020-06-23 09:27:02,340 [90816469]  ERROR - .impl.ModifiableModelCommitter - Last Action: Build.AddManagedFiles 
2020-06-23 09:27:02,340 [90816469]  ERROR - .impl.ModifiableModelCommitter - Assertion failed: api 
java.lang.Throwable: Assertion failed: api
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:182)
	at com.intellij.openapi.roots.impl.ModifiableModelCommitterServiceImpl.createDFSTBuilder(ModifiableModelCommitterServiceImpl.java:74)
	at com.intellij.openapi.roots.impl.ModifiableModelCommitterServiceImpl.getSortedChangedModels(ModifiableModelCommitterServiceImpl.java:64)
	at com.intellij.openapi.roots.impl.ModifiableModelCommitterServiceImpl.multiCommit(ModifiableModelCommitterServiceImpl.java:29)
	at com.intellij.openapi.roots.impl.ModifiableModelCommitter.multiCommit(ModifiableModelCommitter.java:20)
	at com.intellij.openapi.roots.impl.ModifiableModelCommitter.multiCommit(ModifiableModelCommitter.java:14)
	at com.intellij.openapi.externalSystem.service.project.AbstractIdeModifiableModelsProvider.lambda$commit$5(AbstractIdeModifiableModelsProvider.java:331)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.mergeRootsChangesDuring(ProjectRootManagerImpl.java:331)
	at com.intellij.openapi.externalSystem.service.project.AbstractIdeModifiableModelsProvider.commit(AbstractIdeModifiableModelsProvider.java:306)
	at cursive.deps.sync$sync$fn$reify__6975.compute(sync.clj:171)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$runWriteAction$16(ApplicationImpl.java:985)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:964)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:985)
	at cursive.deps.sync$sync$fn__6974.invoke(sync.clj:170)
	at cursive.deps.sync$sync.invokeStatic(sync.clj:164)
	at cursive.deps.sync$sync.invoke(sync.clj:142)
	at clojure.lang.Var.invoke(Var.java:393)
	at cursive.api.DelayedFn.invoke(DelayedFn.java:41)
	at cursive.build.BuildSystemProjectsManager$reimportAllProjects$$inlined$synchronized$lambda$1$1.invoke(BuildSystemManager.kt:154)
	at cursive.build.BuildSystemProjectsManager$reimportAllProjects$$inlined$synchronized$lambda$1$1.invoke(BuildSystemManager.kt:35)
	at cursive.application.ApplicationKt$sam$java_lang_Runnable$0.run(Application.kt)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
