### ISSUE TITLE
Support Quoted Symbols in ClojureScript Projects

### ISSUE THREAD

**Issue by emmanuj** [cursive-ide/cursive#2465]
[shadow-cljs](http://shadow-cljs.org/) allows string symbols in requires. E.g 

`(require ["@material-ui/core" :as mui])`

Cursive stub generation breaks as a result:

```
Error generating stubs for module demo-app: clojure.lang.ExceptionInfo: Library name must be specified as a symbol in :require / :require-macros; offending spec: ["react" :as react] at line 1 jar:file:/Users/emmanuel.john/.m2/repository/lilactown/helix/0.0.13/helix-0.0.13.jar!/helix/core.cljs {:file #object[java.net.URL 0x790ed2d9 "jar:file:/Users/emmanuel.john/.m2/repository/lilactown/helix/0.0.13/helix-0.0.13.jar!/helix/core.cljs"], :line 1, :column 1, :tag :cljs/analysis-error}
				at cljs.analyzer$error.invokeStatic(analyzer.cljc:645)
				at cljs.analyzer$error.invoke(analyzer.cljc:641)
				at cljs.analyzer$error.invokeStatic(analyzer.cljc:643)
				at cljs.analyzer$error.invoke(analyzer.cljc:641)
				at cljs.analyzer$basic_validate_ns_spec.invokeStatic(analyzer.cljc:2008)
				at cljs.analyzer$basic_validate_ns_spec.invoke(analyzer.cljc:1999)
				at cljs.analyzer$parse_require_spec.invokeStatic(analyzer.cljc:2107)
				at cljs.analyzer$parse_require_spec.invoke(analyzer.cljc:2103)
				at clojure.lang.AFn.applyToHelper(AFn.java:171)
				at clojure.lang.AFn.apply... (show balloon)
```

Is there a workaround or can support be added for it?

**Comment by cursive-ide** [comment]
@emmanuj Which version of Cursive are you using? I thought I had fixed this in the latest version.

**Comment by emmanuj** [comment]
I have _Cursive v1.9.4-2020.2_
and _IntelliJ v2020.2.4_

**Comment by emmanuj** [comment]
I'll see if I can reproduce in a demo project. Standby.

**Comment by emmanuj** [comment]
I'm able to reproduce with this project https://github.com/lilactown/helix-todo-mvc

**Comment by cursive-ide** [comment]
I just tried to reproduce this, and I get a different error (this is the root exception, not the later layers):

```
Caused by: java.lang.IllegalArgumentException: /_SLASH_impl_SLASH_class/js.cljs is not a relative path
	at clojure.java.io$as_relative_path.invokeStatic(io.clj:414)
	at clojure.java.io$file.invokeStatic(io.clj:426)
	at clojure.java.io$file.invoke(io.clj:418)
	at cljs.analyzer$locate_src.invokeStatic(analyzer.cljc:2560)
	at cljs.analyzer$locate_src.invoke(analyzer.cljc:2547)
	at cljs.analyzer$analyze_deps.invokeStatic(analyzer.cljc:2603)
	at cljs.analyzer$analyze_deps.invoke(analyzer.cljc:2575)
	at cljs.analyzer$ns_side_effects.invokeStatic(analyzer.cljc:4082)
	at cljs.analyzer$ns_side_effects.invoke(analyzer.cljc:4077)
	at cljs.analyzer$analyze_STAR_$fn__2706.invoke(analyzer.cljc:4201)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$reduce.invoke(core.clj:6810)
	at cljs.analyzer$analyze_STAR_.invokeStatic(analyzer.cljc:4201)
	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:4191)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:4220)
	... 53 more
``` 
Unfortunately this seems to be a bug in the CLJS compiler ([see here](https://clojure.atlassian.net/browse/CLJS-3241)), so I'm not sure how to proceed with this one.

**Comment by emmanuj** [comment]
Are you able to it reproduce with this project instead- https://github.com/emmanuj/cursive-demo?
