### ISSUE TITLE
Unable to navigate to namespace

### ISSUE THREAD

**Issue by awebneck** [cursive-ide/cursive#2469]
I recently got a new machine with Mac OS X Big Sur, Intel i7, and after installing IntelliJ and cursive I find that attempting to navigate to a namespace no longer works at all. I've imported a deps project, refreshed and indexed everything, but neither the default key-binding "ctrl-shift-O" for "navigate to namespace" nor selecting it from the dropdown menu yield any results; No namespace entry field opens, no notification fires... nothing. It's as if I didn't issue a command at all. I invalidated my IntelliJ cache, wiped the .iml and .idea files/dirs, and reimported fresh. Same bag - I cannot navigate to namespaces at all in a project in which I previously had no issues doing so. I can reproduce this across multiple projects, too.

**Comment by awebneck** [comment]
This is the stacktrace of the exception that occurs when I attempt to navigate to a namespace:
```
java.lang.IllegalArgumentException: There is no such tab - NamespaceSearchEverywhereContributor
	at com.intellij.ide.actions.searcheverywhere.SearchEverywhereUI.lambda$switchToTab$8(SearchEverywhereUI.java:180)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at com.intellij.ide.actions.searcheverywhere.SearchEverywhereUI.switchToTab(SearchEverywhereUI.java:180)
	at com.intellij.ide.actions.searcheverywhere.SearchEverywhereManagerImpl.show(SearchEverywhereManagerImpl.java:86)
	at com.intellij.ide.actions.SearchEverywhereBaseAction.showInSearchEverywherePopup(SearchEverywhereBaseAction.java:66)
	at cursive.navigation.GotoNamespaceAction.actionPerformed(Namespace.kt:56)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:281)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:615)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$3(IdeKeyEventDispatcher.java:675)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:674)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:625)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:522)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:476)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:225)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:892)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:837)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:507)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by awebneck** [comment]
Nevermind, just saw that this was already reported and fixed in EAP. My bad
