### ISSUE TITLE
"Error handling response"

### ISSUE THREAD

**Issue by titogarcia** [cursive-ide/cursive#2526]
Hi, I'm finding this repetitive message in the REPL, while running a test that writes log lines to stdout.

`Error handling response - class java.lang.ClassCastException: class clojure.lang.Symbol cannot be cast to class clojure.lang.Associative (clojure.lang.Symbol and clojure.lang.Associative are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @1bf71ddf)
`

What could be the reason for this?

Intellij traces give full stack trace:
```
java.lang.Throwable: Error handling response
java.lang.ClassCastException: class clojure.lang.Symbol cannot be cast to class clojure.lang.Associative (clojure.lang.Symbol and clojure.lang.Associative are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @1bf71ddf)
 at clojure.lang.RT.assoc (RT.java:827)
    clojure.core$assoc__3772.invokeStatic (core.clj:195)
    clojure.core$assoc__3772.doInvoke (core.clj:192)
    clojure.lang.RestFn.invoke (RestFn.java:731)
    cursive.testing.actions$test_handler$process__15152.invoke (actions.clj:295)
    cursive.testing.actions$test_handler$reify__15155.out (actions.clj:307)
    cursive.repl.nrepl$handler.invokeStatic (nrepl.clj:78)
    cursive.repl.nrepl$handler.invoke (nrepl.clj:61)
    cursive.repl.nrepl$start$reify__12621$fn__12629.invoke (nrepl.clj:141)
    cursive.repl.nrepl$start$reify__12621.run (nrepl.clj:140)
    com.intellij.util.RunnableCallable.call (RunnableCallable.java:20)
    com.intellij.util.RunnableCallable.call (RunnableCallable.java:11)
    com.intellij.openapi.application.impl.ApplicationImpl$1.call (ApplicationImpl.java:255)
    java.util.concurrent.FutureTask.run (FutureTask.java:264)
    java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    java.lang.Thread.run (Thread.java:834)

	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:146)
	at cursive.logging$do_error.invokeStatic(logging.clj:60)
	at cursive.logging$do_error.invoke(logging.clj:59)
	at cursive.logging$do_log.invokeStatic(logging.clj:45)
	at cursive.logging$do_log.doInvoke(logging.clj:38)
	at clojure.lang.RestFn.invoke(RestFn.java:464)
	at cursive.repl$print_exception.invokeStatic(repl.clj:140)
	at cursive.repl$print_exception.invoke(repl.clj:138)
	at cursive.repl.nrepl$start$reify__12621$fn__12629.invoke(nrepl.clj:143)
	at cursive.repl.nrepl$start$reify__12621.run(nrepl.clj:140)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:255)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by titogarcia** [comment]
Closing, as I am not seeing this after upgrading.
