### ISSUE TITLE
Error encountered performing task 'run' with profile(s): 'base,system,user,provided,dev,run'

### ISSUE THREAD

**Issue by xu20160924** [cursive-ide/cursive#2568]
When I run Metabase with lein run, it start successfully but start it through cursive show me:
 Error encountered performing task 'run' with profile(s): 'base,system,user,provided,dev,run'
os version :11.3.1 big sur
jdk: 1.8
cursive version: 1.10.2-2021.1
leiningen version : 2.9.6

**Comment by xu20160924** [comment]
Anyone face same problem?

**Comment by xu20160924** [comment]
Does nobody face this problem?

**Comment by xu20160924** [comment]
The more log detail
2021-07-15 11:31:04,071 [ 472479]   INFO - xecution.runners.ExecutionUtil - Error running 'metabase.core':<br>lein did not create a trampoline configuration.
com.intellij.execution.ExecutionException: lein did not create a trampoline configuration.
	at cursive.runner.ClojureScriptRunConfiguration.createLeinParameters(ClojureRunner.kt:369)
	at cursive.runner.ClojureScriptRunConfiguration$getRunProfileState$state$1.createDeferredParameters(ClojureRunner.kt:250)
	at cursive.runner.DeferredCommandLineState.cacheDeferredParameters(Deferred.kt:72)
	at cursive.runner.AbstractDeferredRunner$execute$1.run(Deferred.kt:104)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:998)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:497)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by xu20160924** [comment]
It's related JAVA_CMD

**Comment by kvy** [comment]
@xu20160924 

> It's related JAVA_CMD
Hi Could you please describe how to fixed this issue in detail?  thanks
