### ISSUE TITLE
Unknown alias key: :exec-fn in deps.edn

### ISSUE THREAD

**Issue by jhny** [cursive-ide/cursive#2583]
For some reason I am getting an unknown alias key in a configuration that is suppose to be valid (See screenshot). This only seem to happen in the alias `:test`

deps.edn
```
{:deps    {org.clojure/clojure {:mvn/version "1.10.3"}}
 :paths   ["src"]
 :aliases {:test {:extra-paths ["src/test"]
                  :extra-deps  {io.github.cognitect-labs/test-runner
                                {:git/url "https://github.com/cognitect-labs/test-runner.git"
                                 :sha     "8c3f22363d63715de4087b038d79ae0de36a3263"}}
                  :exec-fn     cognitect.test-runner.api/test}}}
```

```
Error resolving /Users/johnnyeradus/Development/clojure/test_cursive/deps.edn: Unknown alias key: :exec-fn

clojure.lang.ExceptionInfo: Unknown alias key: :exec-fn {:key :exec-fn}
	at clojure.tools.deps.alpha$choose_rule.invokeStatic(alpha.clj:41)
	at clojure.tools.deps.alpha$choose_rule.invoke(alpha.clj:39)
	at clojure.tools.deps.alpha$merge_alias_maps$fn__818$fn__820.invoke(alpha.clj:48)
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
	at clojure.core.protocols$fn__8140.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8140.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8088$G__8083__8101.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6828)
	at clojure.core$reduce.invoke(core.clj:6810)
	at clojure.tools.deps.alpha$merge_alias_maps$fn__818.invoke(alpha.clj:47)
	at clojure.core.protocols$fn__8159.invokeStatic(protocols.clj:168)
	at clojure.core.protocols$fn__8159.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8114$G__8109__8123.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8144.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8144.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8088$G__8083__8101.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6828)
	at clojure.core$reduce.invoke(core.clj:6810)
	at clojure.tools.deps.alpha$merge_alias_maps.invokeStatic(alpha.clj:46)
	at clojure.tools.deps.alpha$merge_alias_maps.doInvoke(alpha.clj:43)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$apply.invoke(core.clj:660)
	at clojure.tools.deps.alpha$combine_aliases.invokeStatic(alpha.clj:58)
	at clojure.tools.deps.alpha$combine_aliases.invoke(alpha.clj:52)
	at cursive.deps.project$project_details$calculate__1034.invoke(project.clj:94)
	at cursive.deps.relocate$with_deps_relocation.invokeStatic(relocate.clj:14)
	at cursive.deps.relocate$with_deps_relocation.invoke(relocate.clj:6)
	at cursive.deps.relocate$with_relocation.invokeStatic(relocate.clj:33)
	at cursive.deps.relocate$with_relocation.invoke(relocate.clj:19)
	at cursive.deps.project$project_details$fn__1047.invoke(project.clj:153)
	at clojure.core.protocols$fn__8159.invokeStatic(protocols.clj:168)
	at clojure.core.protocols$fn__8159.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8114$G__8109__8123.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8146.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8146.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8088$G__8083__8101.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6828)
	at clojure.core$reduce.invoke(core.clj:6810)
	at cursive.deps.project$project_details.invokeStatic(project.clj:129)
	at cursive.deps.project$project_details.invoke(project.clj:76)
	at clojure.lang.Var.invoke(Var.java:388)
	at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke(ClojureRuntimeShimImpl.java:124)
	at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke(ClojureRuntimeShimImpl.java:117)
	at cursive.shim.ShimBootstrap$Shim.apply(ShimBootstrap.java:53)
	at cursive.deps.DepsProjectDetails$doGetDetails$details$1.invoke(Project.kt:168)
	at cursive.deps.DepsProjectDetails$doGetDetails$details$1.invoke(Project.kt:85)
	at cursive.shim.ShimProvider.withShim(Shim.kt:117)
	at cursive.deps.DepsProjectDetails.doGetDetails(Project.kt:167)
	at cursive.deps.DepsProjectDetails.doGetDetails(Project.kt:85)
	at cursive.build.BuildSystemProjectDetails.getProjectDetails(BuildSystem.kt:42)
	at cursive.build.BuildSystemProjectsManager$reimportAllProjects$$inlined$synchronized$lambda$1.run(BuildSystemManager.kt:150)
	at cursive.build.BuildSystemUtil$runTask$1$1.run(BuildSystemUtil.kt:93)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:450)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:117)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:510)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:243)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:243)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by jhny** [comment]
Forgot to post the screenshot: ![test_cursive – deps edn 2021-08-19 08-45-09](https://user-images.githubusercontent.com/72846/130042745-0c2d9588-bb96-4237-b7e1-fb006dc47b12.png)

**Comment by cursive-ide** [comment]
I believe that's an error coming back from deps. Which version of Cursive are you on? And can you send a screenshot of your _Preferences | Build, Execution, Deployment | Build Tools | Clojure Deps_ page?

**Comment by jhny** [comment]
I think you're right, I took the liberty to update clojure on the host machine that runs intelliJ and it worked correctly after that. Sorry for causing a ruckus. I was expecting that Cursive did an indepenent check on deps.edn and that was causing it.

Thanks for the response!
