### ISSUE TITLE
Frequent NullPointerException while running inspections

### ISSUE THREAD

**Issue by aneilbaboo** [cursive-ide/cursive#2662]
My symbol resolution fails randomly because inspections crash partway through the process. I have to manually set and reset my custom resolutions to get it working again.

```
java.lang.NullPointerException
	at clojure.core$name.invokeStatic(core.clj:1597)
	at clojure.core$name.invoke(core.clj:1591)
	at cursive.inspections.unused$with_prefix.invokeStatic(unused.clj:187)
	at cursive.inspections.unused$with_prefix.invoke(unused.clj:186)
	at cursive.inspections.unused$annotate_clauses$annotate__24939$fn__24940.invoke(unused.clj:206)
	at clojure.core$mapv$fn__8470.invoke(core.clj:6937)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6852)
	at clojure.core$mapv.invokeStatic(core.clj:6928)
	at clojure.core$mapv.invoke(core.clj:6928)
	at cursive.inspections.unused$annotate_clauses$annotate__24939.invoke(unused.clj:200)
	at cursive.inspections.unused$annotate_clauses.invokeStatic(unused.clj:211)
	at cursive.inspections.unused$annotate_clauses.invoke(unused.clj:197)
	at cursive.inspections.unused$unused_require_elements$fn__24978.invoke(unused.clj:306)
	at clojure.core$map$fn__5881$fn__5882.invoke(core.clj:2746)
	at clojure.lang.TransformerIterator.step(TransformerIterator.java:79)
	at clojure.lang.TransformerIterator.hasNext(TransformerIterator.java:97)
	at clojure.lang.RT.chunkIteratorSeq(RT.java:575)
	at clojure.lang.RT.seqFrom(RT.java:605)
	at clojure.lang.RT.seq(RT.java:595)
	at clojure.core$seq__5420.invokeStatic(core.clj:139)
	at clojure.core$seq__5420.invoke(core.clj:139)
	at cursive.inspections.unused$unused_requires.invokeStatic(unused.clj:331)
	at cursive.inspections.unused$unused_requires.invoke(unused.clj:311)
	at clojure.lang.Var.invoke(Var.java:399)
	at cursive.api.DelayedFn.invoke(DelayedFn.java:46)
	at cursive.inspections.list.ClUnusedRequire.invoke(ListInspections.kt:31)
	at cursive.inspections.ClSymbolAndListInspection$buildVisitor$1.visitList(Inspections.kt:90)
	at cursive.psi.impl.list.ClListImpl.accept(ClListImpl.java:25)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:64)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:55)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:326)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$4(LocalInspectionsPass.java:285)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:159)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:151)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$5(LocalInspectionsPass.java:283)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:119)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$6(LocalInspectionsPass.java:283)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:83)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:83)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by cursive-ide** [comment]
Which version of Cursive are you on? There were fixes around this in the latest eap, eap6.

**Comment by aneilbaboo** [comment]
Ooops! Sorry about that. I'm normally always up to the latest version, but for some reason, I didn't see the notifications to upgrade. Thank you!
