### ISSUE TITLE
Cannot start Cursive in remote editing session

### ISSUE THREAD

**Issue by joshuaeckroth** [cursive-ide/cursive#2721]
Running `/opt/intellij-idea-ultimate-edition/bin/remote-dev-server.sh` (Arch Linux) to start a remote dev environment on the server, and then connecting on a Windows machine as the client, the server shows these errors, and Clojure files cannot be opened on the client instance:

```
2022-08-03 07:33:09,264 [   7367] SEVERE - #o.j.c.AsyncPromise - IntelliJ IDEA 2022.2  Build #IU-222.3345.118
2022-08-03 07:33:09,264 [   7367] SEVERE - #o.j.c.AsyncPromise - JDK: 17.0.3; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2022-08-03 07:33:09,265 [   7368] SEVERE - #o.j.c.AsyncPromise - OS: Linux
2022-08-03 07:33:09,265 [   7368] SEVERE - #o.j.c.AsyncPromise - Plugin to blame: Cursive version: 1.12.4-2022.2
2022-08-03 07:33:10,359 [   8462] SEVERE - #c.i.p.SingleRootFileViewProvider - Could not initialize class cursive.psi.impl.ClojureFileImpl
java.lang.NoClassDefFoundError: Could not initialize class cursive.psi.impl.ClojureFileImpl
        at cursive.parser.ClojureParserDefinition.createFile(ClojureParserDefinition.java:102)
        at com.intellij.psi.AbstractFileViewProvider.createFile(AbstractFileViewProvider.java:144)
        at com.intellij.psi.AbstractFileViewProvider.createFile(AbstractFileViewProvider.java:128)
        at com.intellij.psi.AbstractFileViewProvider.createFile(AbstractFileViewProvider.java:117)
        at com.intellij.psi.SingleRootFileViewProvider.createFile(SingleRootFileViewProvider.java:144)
        at com.intellij.psi.SingleRootFileViewProvider.getPsiInner(SingleRootFileViewProvider.java:100)
        at com.intellij.psi.AbstractFileViewProvider.getPsi(AbstractFileViewProvider.java:194)
        at com.intellij.psi.impl.file.impl.FileManagerImpl.findFile(FileManagerImpl.java:363)
        at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java:155)
        at org.jetbrains.idea.maven.utils.MavenUtil.lambda$isPomFileIgnoringName$21(MavenUtil.java:1434)
        at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:941)
        at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:68)
        at org.jetbrains.idea.maven.utils.MavenUtil.isPomFileIgnoringName(MavenUtil.java:1432)
        at org.jetbrains.idea.maven.utils.MavenUtil.isPomFile(MavenUtil.java:1402)
        at org.jetbrains.idea.maven.project.MavenUnlinkedProjectAware.isBuildFile(MavenUnlinkedProjectAware.kt:20)
        at com.intellij.openapi.externalSystem.autolink.UnlinkedProjectStartupActivity.getBuildFiles(UnlinkedProjectStartupActivity.kt:242)
        at com.intellij.openapi.externalSystem.autolink.UnlinkedProjectStartupActivity.access$getBuildFiles(UnlinkedProjectStartupActivity.kt:34)
        at com.intellij.openapi.externalSystem.autolink.UnlinkedProjectStartupActivity$showNotificationIfUnlinkedProjectsFound$3.invoke(UnlinkedProjectStartupActivity.kt:114)
        at com.intellij.openapi.externalSystem.autolink.UnlinkedProjectStartupActivity$showNotificationIfUnlinkedProjectsFound$3.invoke(UnlinkedProjectStartupActivity.kt:34)
        at com.intellij.openapi.externalSystem.autolink.UnlinkedProjectStartupActivity$sam$java_util_concurrent_Callable$0.call(UnlinkedProjectStartupActivity.kt)
        at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:536)
        at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:501)
        at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
        at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:75)
        at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:158)
        at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:115)
        at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:66)
        at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
        at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
        at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
        at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:66)
        at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:112)
        at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:75)
        at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:501)
        at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:408)
        at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:241)
        at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
        at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:214)
        at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
        at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:203)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

```
2022-08-03 07:33:16,742 [  14845] SEVERE - #c.i.o.a.i.FlushQueue - Could not initialize class clojure.java.api.Clojure
java.lang.NoClassDefFoundError: Could not initialize class clojure.java.api.Clojure
        at cursive.api.DelayedFn.getDelegate(DelayedFn.java:345)
        at cursive.api.DelayedFn.invoke(DelayedFn.java:31)
        at cursive.api.DelayedFn.getDelegate(DelayedFn.java:342)
        at cursive.api.DelayedFn.invoke(DelayedFn.java:41)
        at cursive.build.BuildSystemProjectsManager$reimportAllProjects$1$task$1$2.invoke(BuildSystemManager.kt:160)
        at cursive.build.BuildSystemProjectsManager$reimportAllProjects$1$task$1$2.invoke(BuildSystemManager.kt:159)
        at cursive.application.ApplicationKt.invokeLater$lambda-3(Application.kt:20)
        at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
        at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
        at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
        at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
        at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
        at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
        at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
        at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
        at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

Note, I'm using Cursive trial at the moment.

**Comment by cursive-ide** [comment]
Just checking, is Cursive installed in the remote instance?

**Comment by joshuaeckroth** [comment]
Yes, the plugin is installed on the "host". The UI tells me it is.

Using `remote-dev-server.sh` to run the remote instance (running this command on the host/server; see https://www.jetbrains.com/help/idea/remote-development-a.html#use_idea) and turning on debug tracing (see `remote-dev-server.sh --help`), I have:

```
+ IS_DARWIN=0
+ case "$(uname)" in
++ uname
+++ dirname /home/josh/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.3345.118/plugins/remote-dev-server/bin/launcher.sh
++ cd /home/josh/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.3345.118/plugins/remote-dev-server/bin
++ pwd
+ REMOTE_DEV_SERVER_BIN_DIR=/home/josh/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.3345.118/plugins/remote-dev-server/bin
++ dirname /home/josh/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.3345.118/plugins/remote-dev-server/bin
+ REMOTE_DEV_SERVER_DIR=/home/josh/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.3345.118/plugins/remote-dev-server
++ dirname /home/josh/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.3345.118/plugins/remote-dev-server
+ PLUGINS_DIR=/home/josh/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.3345.118/plugins
++ dirname /home/josh/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.3345.118/plugins
+ IDE_HOME=/home/josh/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.3345.118
+ IDE_BIN_DIR=/home/josh/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.3345.118/bin
+ DEFAULT_DIST=/home/josh/.cache/JetBrains/RemoteDev/dist
+ USER_PROVIDED_DIST=/home/josh/.cache/JetBrains/RemoteDev/userProvidedDist
+ IDE_SCRIPT_NAME=idea.sh
+ IDE_PRODUCT_CODE=IU
+ IDE_PRODUCT_UC=IDEA
+ IDE_PRODUCT_VM_OPTIONS=idea
+ IDE_DEFAULT_XMX=-Xmx750m
+ '[' -z idea.sh ']'
+ '[' -z IU ']'
+ '[' -z IDEA ']'
+ '[' -z idea ']'
+ '[' -z -Xmx750m ']'
...
2022-08-05 08:41:08,201 [    509]   WARN - #c.j.r.u.UnattendedHostStarterBase - Hostname is not provided, using: 'nostromo'. You can specify it manually with '--ssh-link-host' option
2022-08-05 08:41:08,203 [    511]   WARN - #c.j.r.u.UnattendedHostStarterBase - Username is not provided, using: 'josh'. You can specify it manually with '--ssh-link-user' option
2022-08-05 08:41:08,203 [    511]   WARN - #c.j.r.u.UnattendedHostStarterBase - Ssh port is not provided, using: '22'. You can specify it manually with '--ssh-link-port' option
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
Info  | RdCoroutineScope          | 33:JobScheduler FJ pool 9/19 | RdCoroutineHost overridden 
2022-08-05 08:41:08,499 [    807]   WARN - #c.i.i.s.i.StartupManagerImpl - Activities registered via registerPostStartupActivity must be dumb-aware: cursive.build.BuildSystemUtil$$Lambda$975/0x0000000100dc4bd0@66f57048
2022-08-05 08:41:08,544 [    852]   WARN - #c.i.u.j.JBCefApp - JCEF is manually disabled via 'ide.browser.jcef.enabled=false'
2022-08-05 08:41:08,582 [    890] SEVERE - #c.i.i.p.PluginManager - java.lang.ExceptionInInitializerError
java.util.concurrent.CompletionException: java.lang.ExceptionInInitializerError
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:562)
	at java.base/java.util.concurrent.ForkJoinTask.getException(ForkJoinTask.java:580)
	at java.base/java.util.concurrent.ForkJoinTask.invokeAll(ForkJoinTask.java:829)
	at com.intellij.serviceContainer.ComponentManagerImpl$preloadServices$3.run(ComponentManagerImpl.kt:1055)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	... 6 more
Caused by: java.lang.ExceptionInInitializerError
	at clojure.java.api.Clojure.<clinit>(Clojure.java:97)

*********
	at cursive.api.DelayedFn.getDelegate(DelayedFn.java:345)
	at cursive.api.DelayedFn.invoke(DelayedFn.java:31)
	at cursive.api.DelayedFn.getDelegate(DelayedFn.java:342)
	at cursive.api.DelayedFn.invoke(DelayedFn.java:31)
	at cursive.formatter.codeStyle.ClojureCodeStyleSettings.readExternal(ClojureCodeStyleSettings.java:126)
*********

	at com.intellij.psi.codeStyle.CustomCodeStyleSettingsManager.readExternal(CustomCodeStyleSettingsManager.java:176)
	at com.intellij.psi.codeStyle.CodeStyleSettings.readExternal(CodeStyleSettings.java:581)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleSchemeImpl.init(CodeStyleSchemeImpl.java:62)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleSchemeImpl.getCodeStyleSettings(CodeStyleSchemeImpl.java:90)
	at com.intellij.psi.codeStyle.CodeStyleSettingsManager.getCurrentSettings(CodeStyleSettingsManager.java:218)
	at com.intellij.psi.codeStyle.ProjectCodeStyleSettingsManager.initializeComponent(ProjectCodeStyleSettingsManager.java:46)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:131)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:48)
	at com.intellij.serviceContainer.ComponentManagerImpl.initializeComponent$intellij_platform_serviceContainer(ComponentManagerImpl.kt:535)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:55)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:41)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:119)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:73)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:66)
	at com.intellij.serviceContainer.ComponentManagerImpl.preloadService(ComponentManagerImpl.kt:1068)
	at com.intellij.serviceContainer.ComponentManagerImpl$preloadServices$1.invoke(ComponentManagerImpl.kt:1033)
	at com.intellij.serviceContainer.ComponentManagerImpl$preloadServices$1.run(ComponentManagerImpl.kt:55)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1375)
	... 5 more
Caused by: java.io.FileNotFoundException: Could not locate clojure/core__init.class, clojure/core.clj or clojure/core.cljc on classpath.
	at clojure.lang.RT.load(RT.java:520)
	at clojure.lang.RT.load(RT.java:482)
	at clojure.lang.RT.<clinit>(RT.java:341)
	... 29 more
2022-08-05 08:41:08,585 [    893] SEVERE - #c.i.i.p.PluginManager - IntelliJ IDEA 2022.2  Build #IU-222.3345.118
2022-08-05 08:41:08,585 [    893] SEVERE - #c.i.i.p.PluginManager - JDK: 17.0.3; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2022-08-05 08:41:08,585 [    893] SEVERE - #c.i.i.p.PluginManager - OS: Linux
2022-08-05 08:41:08,586 [    894] SEVERE - #c.i.i.p.PluginManager - Plugin to blame: Cursive version: 1.12.4-2022.2
```

and more errors essentially due to this first one.

I've highlighted above where Cursive is loaded, so the plugin must be installed. I manually installed it with `remote-dev-server.sh installPlugins` before starting the server.

Curiously, the `PLUGINS_DIR` above shows `/home/josh/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.3345.118/plugins` which does not have Cursive, but https://www.jetbrains.com/help/idea/remote-development-a.html#plugins says the remote editing plugins are stored per project, and indeed `/home/josh/.cache/JetBrains/RemoteDev-IU/_home_josh_[project-name]/plugins` has `clojure-plugin.zip`.

Does remote development work for you?

**Comment by cursive-ide** [comment]
I've actually never tried remote development, but it looks like I might have to set up a reproduction setup.

**Comment by joshuaeckroth** [comment]
Thanks, this is a blocker for some in our team.

**Comment by CalebMacdonaldBlack** [comment]
Would love to see this fixed as well.

**Comment by askonomm** [comment]
I develop inside a VM that I ssh into so this would be awesome for me, too.

**Comment by KoryB** [comment]
I tried this using Gateway 2022.3.1 and am having a similar issue. The client opens, but clojure files cannot open, and the project tree does not load properly.

**Comment by shrimp3r** [comment]
It would be really useful for this to be fixed, as I think remote development will become more popular with stuff like https://cloud.google.com/workstations

**Comment by Sardtok** [comment]
Using Gateway and running IntelliJ in WSL I keep getting the following error when using Cursive:
The plugin com.cursiveclojure.cursive failed to save settings. Please restart IntelliJ IDEA.

Inside settings the following three tabs fail to load (the loading indicator keeps spinning forever):
- Build, Execution, Deployment -> Compiler -> Clojure Compiler
- Languages & Frameworks -> Clojure -> REPL Commands
- Languages & Frameworks -> Clojure -> Test Integration

The project keeps Scanning forever.

Similar errors where the clojure.core namespaces cannot be found is the cause, and I get these in multiple locations. The first one in the log:

```
2023-08-29 10:33:48,589 [   3344] SEVERE - #c.i.o.a.i.CoroutineExceptionHandlerImpl - Unhandled exception in [CoroutineName(com.intellij.psi.codeStyle.ProjectCodeStyleSettingsManager preloading), StandaloneCoroutine{Cancelling}@59a9472c, Dispatchers.Default]
java.lang.ExceptionInInitializerError
	at clojure.java.api.Clojure.<clinit>(Clojure.java:97)
	at cursive.api.DelayedFn.getDelegate(DelayedFn.java:345)
	at cursive.api.DelayedFn.invoke(DelayedFn.java:31)
	at cursive.api.DelayedFn.getDelegate(DelayedFn.java:342)
	at cursive.api.DelayedFn.invoke(DelayedFn.java:31)
	at cursive.formatter.codeStyle.ClojureCodeStyleSettings.readExternal(ClojureCodeStyleSettings.java:126)
	at com.intellij.psi.codeStyle.CustomCodeStyleSettingsManager.readExternal(CustomCodeStyleSettingsManager.java:177)
	at com.intellij.psi.codeStyle.CodeStyleSettings.readExternal(CodeStyleSettings.java:584)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleSchemeImpl.readFromDataHolder(CodeStyleSchemeImpl.java:65)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleSchemeImpl.getCodeStyleSettings(CodeStyleSchemeImpl.java:88)
	at com.intellij.psi.codeStyle.CodeStyleSettingsManager.getCurrentSettings(CodeStyleSettingsManager.java:232)
	at com.intellij.psi.codeStyle.ProjectCodeStyleSettingsManager.initializeComponent(ProjectCodeStyleSettingsManager.java:47)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:133)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:48)
	at com.intellij.serviceContainer.ComponentManagerImpl.initializeComponent$intellij_platform_serviceContainer(ComponentManagerImpl.kt:577)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:51)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:43)
	at com.intellij.serviceContainer.BaseComponentAdapter.doCreateInstance(BaseComponentAdapter.kt:158)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance(BaseComponentAdapter.kt:137)
	at com.intellij.serviceContainer.BaseComponentAdapter.access$createInstance(BaseComponentAdapter.kt:21)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invokeSuspend(BaseComponentAdapter.kt:185)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invoke(BaseComponentAdapter.kt)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invoke(BaseComponentAdapter.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceAsync(BaseComponentAdapter.kt:180)
	at com.intellij.serviceContainer.ComponentManagerImpl.preloadService$suspendImpl(ComponentManagerImpl.kt:1162)
	at com.intellij.serviceContainer.ComponentManagerImpl.preloadService(ComponentManagerImpl.kt)
	at com.intellij.serviceContainer.ComponentManagerImpl$preloadServices$1.invokeSuspend(ComponentManagerImpl.kt:1146)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.io.FileNotFoundException: Could not locate clojure/core__init.class, clojure/core.clj or clojure/core.cljc on classpath.
	at clojure.lang.RT.load(RT.java:520)
	at clojure.lang.RT.load(RT.java:482)
	at clojure.lang.RT.<clinit>(RT.java:341)
	... 36 more
```

**Comment by Bigsy** [comment]
Also running into this issue with idea WSL remote setup, I am working around it by simply running intellij as WSLg app but its less than ideal. Would be great to have this working.

**Comment by agriffis** [comment]
I'm trying IntelliJ for the first time, with the remote dev feature because that's how I work.

When I try to start the Cursive REPL (connecting to existing nrepl) then it seems to just hang. It looks like this:

<img width="656" height="264" alt="Image" src="https://github.com/user-attachments/assets/389f1804-dbe1-4517-9a18-397e546c2a80" />

At the prompt, I can start it with `lein repl :connect 192.168.11.11:7888` (which is the same way I've configured IntelliJ)

I'm not sure if it's the same as this issue, but the description "Cannot start Cursive in remote editing session" applies.

Given that this issue is still open, does that mean that Cursive hasn't gained support for remote editing in the intervening years?

**Comment by agriffis** [comment]
@cmf Interesting, thanks! I hope that you'll be able to do it soon. It's encouraging to know that the remote dev features are now available for you to integrate with.

I am probably in the minority, but this is a must-have for me to seriously consider IntelliJ. I'm considering migrating from my existing tmux/neovim remote-development setup.

I'm subscribed to this issue so I'll get a notification if you update here when you have something for people to try.
