### ISSUE TITLE
java.lang.NullPointerException: facade.login must not be null

### ISSUE THREAD

**Issue by orange-guo** [cursive-ide/cursive#2740]
# Problem description
An exception occurred when importing a leiningen project into IntelliJ-idea
# Other Background information
IntelliJ-idea version is `2022.2.3`
cursive idea plugin version is `1.12.5-eap2-2022.2`
operation system is `ubuntu-22.04`

# Exception stack trace
```
java.lang.NullPointerException: facade.login must not be null
	at cursive.leiningen.LeiningenUtil.standardArgs(LeiningenSupport.kt:83)
	at cursive.leiningen.project.LeiningenProjectDetails$doGetDetails$value$1.invoke(ProjectDetails.kt:76)
	at cursive.leiningen.project.LeiningenProjectDetails$doGetDetails$value$1.invoke(ProjectDetails.kt:70)
	at cursive.shim.ShimProvider.withShim(Shim.kt:117)
	at cursive.leiningen.project.LeiningenProjectDetails.doGetDetails(ProjectDetails.kt:70)
	at cursive.leiningen.project.LeiningenProjectDetails.doGetDetails(ProjectDetails.kt:62)
	at cursive.build.BuildSystemProjectDetails.getProjectDetails(BuildSystem.kt:45)
	at cursive.build.BuildSystemProjectsManager.reimportAllProjects$lambda-3$lambda-2(BuildSystemManager.kt:149)
	at cursive.build.BuildSystemUtil$runTask$1$1.run(BuildSystemUtil.kt:83)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by orange-guo** [comment]
I found the same issue <#2144> from closed issues

**Comment by orange-guo** [comment]
Solution: do not select proxy authentication in tab Http Proxy if your proxy is not using authentication
