### ISSUE TITLE
java.lang.NullPointerException: facade.password must not be null

### ISSUE THREAD

**Issue by pstephenwille** [cursive-ide/cursive#2757]
I just registered the Cursive plugin and get this error when trying `Run REPL for myproject`.
The project runs fine from CLI and it's listed in the Leiningen panel in Intellij.
Any idea what's going on?

`java.lang.NullPointerException: facade.password must not be null
	at cursive.leiningen.LeiningenUtil.standardArgs(LeiningenSupport.kt:84)
	at cursive.leiningen.project.LeiningenProjectDetails$doGetDetails$value$1.invoke(ProjectDetails.kt:76)
	at cursive.leiningen.project.LeiningenProjectDetails$doGetDetails$value$1.invoke(ProjectDetails.kt:70)
	at cursive.shim.ShimProvider.withShim(Shim.kt:117)
	at cursive.leiningen.project.LeiningenProjectDetails.doGetDetails(ProjectDetails.kt:70)
	at cursive.leiningen.project.LeiningenProjectDetails.doGetDetails(ProjectDetails.kt:62)
	at cursive.build.BuildSystemProjectDetails.getProjectDetails(BuildSystem.kt:45)
	at cursive.build.BuildSystemProjectsManager.reimportAllProjects$lambda-3$lambda-2(BuildSystemManager.kt:149)
	at cursive.build.BuildSystemUtil$runTask$1$1.run(BuildSystemUtil.kt:83)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
`

**Comment by cursive-ide** [comment]
This looks like your IntelliJ is configured to use an HTTP proxy, and it's configured to authenticate, but you don't have a password set. Is that the case?

**Comment by pstephenwille** [comment]
I had to down grade to 2022.2 and am getting a new error.
The run/debug looks a little different than the one from 2022.3 too


![image](https://user-images.githubusercontent.com/498165/209198781-b0642f90-4c07-452c-989d-319d2a869918.png)

![image](https://user-images.githubusercontent.com/498165/209198969-a5765e5e-a8bc-41dc-bff5-f08183015c90.png)
