### ISSUE TITLE
REPL does not automatically select .shadow-cljs/nrepl.port for nREPL connection type

### ISSUE THREAD

**Issue by jdhollis** [cursive-ide/cursive#2759]
Hi, Colin.

Ran into an issue with “Use standard port file” with an “nREPL” connection type to `shadow-cljs`. It seems that `.shadow-cljs/socket-repl.port` is being picked up instead, resulting in the following exception:

`Exception starting REPL: java.lang.IllegalStateException: Could not open new session; :clone response: Disconnected from remote server.`

If I explicitly specify `.shadow-cljs/nrepl.port`, everything works as expected.

![Screen Shot 2022-12-25 at 2 40 51 PM](https://user-images.githubusercontent.com/31834/209480393-03b5ed29-392a-4928-a3a8-16250eb8c389.png)

For reference, I’m using IntelliJ 2022.3.1 (Build #IU-223.8214.52) with Cursive 1.12.7-eap1-2022.3.

**Comment by zampino** [comment]
I actually do have the same issue after upgrading to Cursive 1.12.7 2022.3 - IntelliJ IDEA 2022.3.2 (CE).
My nREPL is started by an external process and puts a file .nrepl-port at project source root. 

My setting: _Edit Configurations > Remote REPL > Use port from REPL file >  Use standard port file_ no longer works and produces:

```
Connecting to remote nREPL server...
Exception starting REPL: java.lang.IllegalStateException: Could not open new session; :clone response: Disconnected from remote server.
```

Our nREPL is not started by shadow, and it produces a regular `.nrepl-port` file. In fact, by setting the option Specify custom port file to .nrepl-port it does connect fine as mentioned by @jdhollis.

**Comment by zampino** [comment]
This is the stacktrace from IntelliJ:
```
java.lang.Throwable: Error reading from nREPL client
java.lang.ArithmeticException: long overflow
 at java.lang.Math.multiplyExact (Math.java:1004)
    clojure.lang.Numbers.multiply (Numbers.java:1971)
    nrepl.bencode$read_long.invokeStatic (bencode.clj:129)
    nrepl.bencode$read_long.invokePrim (bencode.clj:-1)
    nrepl.bencode$read_long.invokeStatic (bencode.clj:127)
    nrepl.bencode$read_long.invokePrim (bencode.clj:-1)
    nrepl.bencode$read_long.invokeStatic (bencode.clj:127)
    nrepl.bencode$read_long.invokePrim (bencode.clj:-1)
    nrepl.bencode$read_long.invokeStatic (bencode.clj:127)
    nrepl.bencode$read_long.invokePrim (bencode.clj:-1)
    nrepl.bencode$read_netstring_STAR_.invokeStatic (bencode.clj:156)
    nrepl.bencode$read_netstring_STAR_.invoke (bencode.clj:154)
    nrepl.bencode$read_token.invokeStatic (bencode.clj:247)
    nrepl.bencode$read_token.invoke (bencode.clj:237)
    nrepl.bencode$read_bencode.invokeStatic (bencode.clj:257)
    nrepl.bencode$read_bencode.invoke (bencode.clj:254)
    nrepl.transport$bencode$fn__4147$fn__4148.invoke (transport.clj:113)
    nrepl.transport$bencode$fn__4147.invoke (transport.clj:113)
    nrepl.transport$fn_transport$fn__4112.invoke (transport.clj:42)
    clojure.core$binding_conveyor_fn$fn__5823.invoke (core.clj:2047)
    clojure.lang.AFn.call (AFn.java:18)
    java.util.concurrent.FutureTask.run (FutureTask.java:264)
    java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1136)
    java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:635)
    java.lang.Thread.run (Thread.java:833)

	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at cursive.logging$do_error.invokeStatic(logging.clj:60)
	at cursive.logging$do_error.invoke(logging.clj:59)
	at cursive.logging$do_log.invokeStatic(logging.clj:45)
	at cursive.logging$do_log.doInvoke(logging.clj:38)
	at clojure.lang.RestFn.invoke(RestFn.java:464)
	at cursive.repl.nrepl$start$reify__5248.run(nrepl.clj:151)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:246)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
