### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "org.mozilla.javascript.ast.AstNode.getType()" because "iter" is null

### ISSUE THREAD

**Issue by jkeys089** [cursive-ide/cursive#2789]
I get the stacktrace below anytime I open a project that uses eslint:
```
java.lang.Throwable: Exception parsing /projects/test/node_modules/eslint-plugin-vue/lib/rules/no-watch-after-await.js
java.lang.NullPointerException: Cannot invoke "org.mozilla.javascript.ast.AstNode.getType()" because "iter" is null
 at org.mozilla.javascript.Parser.generatorExpressionLoop (Parser.java:3516)
    org.mozilla.javascript.Parser.generatorExpression (Parser.java:3460)
    org.mozilla.javascript.Parser.argumentList (Parser.java:2723)
    org.mozilla.javascript.Parser.memberExprTail (Parser.java:2870)
    org.mozilla.javascript.Parser.memberExpr (Parser.java:2789)
    org.mozilla.javascript.Parser.unaryExpr (Parser.java:2647)
    org.mozilla.javascript.Parser.mulExpr (Parser.java:2568)
    org.mozilla.javascript.Parser.addExpr (Parser.java:2552)
    org.mozilla.javascript.Parser.shiftExpr (Parser.java:2533)
    org.mozilla.javascript.Parser.relExpr (Parser.java:2508)
    org.mozilla.javascript.Parser.eqExpr (Parser.java:2480)
    org.mozilla.javascript.Parser.bitAndExpr (Parser.java:2469)
    org.mozilla.javascript.Parser.bitXorExpr (Parser.java:2458)
    org.mozilla.javascript.Parser.bitOrExpr (Parser.java:2447)
    org.mozilla.javascript.Parser.andExpr (Parser.java:2436)
    org.mozilla.javascript.Parser.orExpr (Parser.java:2425)
    org.mozilla.javascript.Parser.condExpr (Parser.java:2389)
    org.mozilla.javascript.Parser.assignExpr (Parser.java:2345)
    org.mozilla.javascript.Parser.expr (Parser.java:2324)
    org.mozilla.javascript.Parser.returnOrYield (Parser.java:1940)
    org.mozilla.javascript.Parser.statementHelper (Parser.java:1222)
    org.mozilla.javascript.Parser.statement (Parser.java:1119)
    org.mozilla.javascript.Parser.parseFunctionBody (Parser.java:744)
    org.mozilla.javascript.Parser.function (Parser.java:926)
    org.mozilla.javascript.Parser.function (Parser.java:858)
    org.mozilla.javascript.Parser.methodDefinition (Parser.java:3726)
    org.mozilla.javascript.Parser.objectLiteral (Parser.java:3612)
    org.mozilla.javascript.Parser.primaryExpr (Parser.java:3129)
    org.mozilla.javascript.Parser.memberExpr (Parser.java:2753)
    org.mozilla.javascript.Parser.unaryExpr (Parser.java:2647)
    org.mozilla.javascript.Parser.mulExpr (Parser.java:2568)
    org.mozilla.javascript.Parser.addExpr (Parser.java:2552)
    org.mozilla.javascript.Parser.shiftExpr (Parser.java:2533)
    org.mozilla.javascript.Parser.relExpr (Parser.java:2508)
    org.mozilla.javascript.Parser.eqExpr (Parser.java:2480)
    org.mozilla.javascript.Parser.bitAndExpr (Parser.java:2469)
    org.mozilla.javascript.Parser.bitXorExpr (Parser.java:2458)
    org.mozilla.javascript.Parser.bitOrExpr (Parser.java:2447)
    org.mozilla.javascript.Parser.andExpr (Parser.java:2436)
    org.mozilla.javascript.Parser.orExpr (Parser.java:2425)
    org.mozilla.javascript.Parser.condExpr (Parser.java:2389)
    org.mozilla.javascript.Parser.assignExpr (Parser.java:2345)
    org.mozilla.javascript.Parser.assignExpr (Parser.java:2368)
    org.mozilla.javascript.Parser.expr (Parser.java:2324)
    org.mozilla.javascript.Parser.nameOrLabel (Parser.java:2073)
    org.mozilla.javascript.Parser.statementHelper (Parser.java:1255)
    org.mozilla.javascript.Parser.statement (Parser.java:1119)
    org.mozilla.javascript.Parser.parse (Parser.java:640)
    org.mozilla.javascript.Parser.parse (Parser.java:570)
    cursive.index.js$parse.invokeStatic (js.clj:29)
    cursive.index.js$parse.invoke (js.clj:20)
    cursive.index.js$index$fn__24949.invoke (js.clj:188)
    cursive.index.js$index.invokeStatic (js.clj:187)
    cursive.index.js$index.invoke (js.clj:185)
    cursive.index.js$index_javascript.invokeStatic (js.clj:229)
    cursive.index.js$index_javascript.invoke (js.clj:224)
    clojure.lang.Var.invoke (Var.java:384)
    cursive.api.DelayedFn.invoke (DelayedFn.java:31)
    cursive.index.PsiDependentIndexExtension.lambda$getIndexer$0 (PsiDependentIndexExtension.java:50)
    com.intellij.util.indexing.impl.MapReduceIndex.mapByIndexer (MapReduceIndex.java:306)
    com.intellij.util.indexing.impl.MapReduceIndex.mapInput (MapReduceIndex.java:297)
    com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.mapInput (VfsAwareMapReduceIndex.java:172)
    com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.mapInput (VfsAwareMapReduceIndex.java:39)
    com.intellij.util.indexing.impl.MapReduceIndex.mapInputAndPrepareUpdate (MapReduceIndex.java:242)
    com.intellij.indexing.composite.CompositeInvertedIndexBase.updateBaseIndex (CompositeInvertedIndexBase.java:294)
    com.intellij.indexing.composite.CompositeInvertedIndexBase.mapInputAndPrepareUpdate (CompositeInvertedIndexBase.java:64)
    com.intellij.indexing.composite.CompositeInvertedIndexBase.mapInputAndPrepareUpdate (CompositeInvertedIndexBase.java:30)
    com.intellij.util.indexing.FileBasedIndexImpl.createSingleIndexValueApplier (FileBasedIndexImpl.java:1681)
    com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$26 (FileBasedIndexImpl.java:1546)
    com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyWithProvidedValueIn (FileTypeManagerImpl.java:675)
    com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent (FileBasedIndexImpl.java:1494)
    com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent (FileBasedIndexImpl.java:1467)
    com.intellij.util.indexing.contentQueue.IndexUpdateRunner.lambda$indexOneFileOfJob$4 (IndexUpdateRunner.java:317)
    com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor.callWrapped (NonBlockingReadActionImpl.java:746)
    com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor$MonitoredComputation.call (NonBlockingReadActionImpl.java:778)
    com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction (NonBlockingReadActionImpl.java:573)
    com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3 (NonBlockingReadActionImpl.java:537)
    com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction (ApplicationImpl.java:1102)
    com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0 (ProgressIndicatorUtils.java:72)
    com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite (ProgressIndicatorUtilService.java:63)
    com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite (ProgressIndicatorUtils.java:129)
    com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1 (ProgressIndicatorUtils.java:110)
    com.intellij.openapi.progress.ProgressManager.lambda$runProcess$1 (ProgressManager.java:70)
    com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2 (CoreProgressManager.java:186)
    com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13 (CoreProgressManager.java:604)
    com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun (CoreProgressManager.java:679)
    com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress (CoreProgressManager.java:635)
    com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress (CoreProgressManager.java:603)
    com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress (ProgressManagerImpl.java:60)
    com.intellij.openapi.progress.impl.CoreProgressManager.runProcess (CoreProgressManager.java:173)
    com.intellij.openapi.progress.ProgressManager.runProcess (ProgressManager.java:70)
    com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority (ProgressIndicatorUtils.java:107)
    com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority (ProgressIndicatorUtils.java:72)
    com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation (NonBlockingReadActionImpl.java:537)
    com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.executeSynchronously (NonBlockingReadActionImpl.java:464)
    com.intellij.openapi.application.impl.NonBlockingReadActionImpl.executeSynchronously (NonBlockingReadActionImpl.java:218)
    com.intellij.util.indexing.contentQueue.IndexUpdateRunner.indexOneFileOfJob (IndexUpdateRunner.java:321)
    com.intellij.util.indexing.contentQueue.IndexUpdateRunner.lambda$indexJobsFairly$3 (IndexUpdateRunner.java:243)
    com.intellij.openapi.progress.impl.ProgressSuspender.executeNonSuspendableSection (ProgressSuspender.java:80)
    com.intellij.util.indexing.contentQueue.IndexUpdateRunner.indexJobsFairly (IndexUpdateRunner.java:246)
    com.intellij.util.indexing.contentQueue.IndexUpdateRunner.lambda$doIndexFiles$2 (IndexUpdateRunner.java:177)
    com.intellij.util.concurrency.BoundedTaskExecutor.doRun (BoundedTaskExecutor.java:248)
    com.intellij.util.concurrency.BoundedTaskExecutor.access$200 (BoundedTaskExecutor.java:28)
    com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue (BoundedTaskExecutor.java:221)
    com.intellij.util.ConcurrencyUtil.runUnderThreadName (ConcurrencyUtil.java:227)
    com.intellij.util.concurrency.BoundedTaskExecutor$1.run (BoundedTaskExecutor.java:210)
    java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1136)
    java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:635)
    java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run (Executors.java:702)
    java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run (Executors.java:699)
    java.security.AccessController.doPrivileged (AccessController.java:399)
    java.util.concurrent.Executors$PrivilegedThreadFactory$1.run (Executors.java:699)
    java.lang.Thread.run (Thread.java:833)

	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at cursive.logging$do_error.invokeStatic(logging.clj:60)
	at cursive.logging$do_error.invoke(logging.clj:59)
	at cursive.logging$do_log.invokeStatic(logging.clj:45)
	at cursive.logging$do_log.doInvoke(logging.clj:38)
	at clojure.lang.RestFn.invoke(RestFn.java:490)
	at cursive.index.js$index$fn__24949.invoke(js.clj:190)
	at cursive.index.js$index.invokeStatic(js.clj:187)
	at cursive.index.js$index.invoke(js.clj:185)
	at cursive.index.js$index_javascript.invokeStatic(js.clj:229)
	at cursive.index.js$index_javascript.invoke(js.clj:224)
	at clojure.lang.Var.invoke(Var.java:384)
	at cursive.api.DelayedFn.invoke(DelayedFn.java:31)
	at cursive.index.PsiDependentIndexExtension.lambda$getIndexer$0(PsiDependentIndexExtension.java:50)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapByIndexer(MapReduceIndex.java:306)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:297)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:172)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:39)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInputAndPrepareUpdate(MapReduceIndex.java:242)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.updateBaseIndex(CompositeInvertedIndexBase.java:294)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.mapInputAndPrepareUpdate(CompositeInvertedIndexBase.java:64)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.mapInputAndPrepareUpdate(CompositeInvertedIndexBase.java:30)
	at com.intellij.util.indexing.FileBasedIndexImpl.createSingleIndexValueApplier(FileBasedIndexImpl.java:1681)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$26(FileBasedIndexImpl.java:1546)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyWithProvidedValueIn(FileTypeManagerImpl.java:675)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1494)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1467)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner.lambda$indexOneFileOfJob$4(IndexUpdateRunner.java:317)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor.callWrapped(NonBlockingReadActionImpl.java:746)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor$MonitoredComputation.call(NonBlockingReadActionImpl.java:778)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:573)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:537)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1102)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:72)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:129)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:110)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$1(ProgressManager.java:70)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:70)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:107)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:72)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:537)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.executeSynchronously(NonBlockingReadActionImpl.java:464)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl.executeSynchronously(NonBlockingReadActionImpl.java:218)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner.indexOneFileOfJob(IndexUpdateRunner.java:321)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner.lambda$indexJobsFairly$3(IndexUpdateRunner.java:243)
	at com.intellij.openapi.progress.impl.ProgressSuspender.executeNonSuspendableSection(ProgressSuspender.java:80)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner.indexJobsFairly(IndexUpdateRunner.java:246)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner.lambda$doIndexFiles$2(IndexUpdateRunner.java:177)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:248)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:28)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:221)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:210)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Is there some way to exclude node_modules from cursive indexing?

**Comment by rozhok** [comment]
Same here. This is super annoying.
