### ISSUE TITLE
Unexpected end of ZLIB input stream

### ISSUE THREAD

**Issue by Biserkov** [cursive-ide/cursive#2853]
**Workaround**: Delete `~/.deps.clj/1.11.1.1413` and try again.

**Old workaround**:  Use with deps.clj version 1.11.1.1403 or older ( Settings > Buid, Execution, Deployment > Build Tools > Clojure deps).

Version 1.13.1-eap7-2023.3

A notification with the error message above show up on project start (during indexing).

Trying to run a REPL with Deps results in the following exception.

Trying to run a REPL with IntelliJ project classpath works.

deps.clj version 1.11.1.1413 and 1.11.1411

```
java.io.EOFException: Unexpected end of ZLIB input stream
	at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:244)
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.base/java.util.zip.ZipInputStream.read(ZipInputStream.java:196)
	at java.base/java.util.zip.CheckedInputStream.read(CheckedInputStream.java:82)
	at java.base/java.io.InputStream.transferTo(InputStream.java:782)
	at java.base/java.nio.file.Files.copy(Files.java:3171)
	at borkdude.deps$unzip.invokeStatic(deps.clj:422)
	at borkdude.deps$unzip.invoke(deps.clj:401)
	at borkdude.deps$clojure_tools_install_BANG_.invokeStatic(deps.clj:597)
	at borkdude.deps$clojure_tools_install_BANG_.invoke(deps.clj:535)
	at borkdude.deps$_main$fn__339.invoke(deps.clj:911)
	at borkdude.deps$_main.invokeStatic(deps.clj:909)
	at borkdude.deps$_main.doInvoke(deps.clj:867)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at cursive.deps_clj.shim$invoke_deps$fn__396.invoke(Unknown Source)
	at cursive.deps_clj.shim$do_invoke.invokeStatic(Unknown Source)
	at cursive.deps_clj.shim$do_invoke.invoke(Unknown Source)
	at cursive.deps_clj.shim$invoke_deps.invokeStatic(Unknown Source)
	at cursive.deps_clj.shim$invoke_deps.invoke(Unknown Source)
	at clojure.lang.Var.invoke(Var.java:393)
	at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke(ClojureRuntimeShimImpl.java:136)
	at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke(ClojureRuntimeShimImpl.java:128)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:167)
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:102)
	at cursive.embed$invoke_in.invokeStatic(embed.clj:51)
	at cursive.embed$invoke_in.doInvoke(embed.clj:45)
	at clojure.lang.RestFn.invoke(RestFn.java:490)
	at cursive.deps.project$invoke_deps$fn__19315.invoke(project.clj:223)
	at cursive.deps.project$invoke_deps.invokeStatic(project.clj:221)
	at cursive.deps.project$invoke_deps.invoke(project.clj:215)
	at cursive.deps.project$process_command_line.invokeStatic(project.clj:381)
	at cursive.deps.project$process_command_line.doInvoke(project.clj:376)
	at clojure.lang.RestFn.invoke(RestFn.java:500)
	at clojure.lang.Var.invoke(Var.java:406)
	at cursive.api.DelayedFn.invoke(DelayedFn.java:51)
	at cursive.runner.BaseJvmClojureRunConfiguration.createDepsParameters(ClojureRunnerBase.kt:150)
	at cursive.repl.runner.LocalConfiguration$getRunProfileState$2.createDeferredParameters(LocalReplRunConfigurations.kt:118)
	at cursive.runner.DeferredCommandLineState.cacheDeferredParameters(Deferred.kt:72)
	at cursive.runner.AbstractDeferredRunner$execute$1.run(Deferred.kt:104)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:428)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:115)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:478)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:251)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:251)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:465)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$19(ProgressRunner.java:477)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by cursive-ide** [comment]
I'm going to close this because I don't think there's much Cursive can do about this. It looks like the download of the Clojure tools by deps.clj was corrupted somehow.
