### ISSUE TITLE
Exceptions thrown when file's file type is overridden

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/cursive#2858]
If you have a file without a Clojure extension, you can [manually override its file type](https://www.jetbrains.com/help/idea/creating-and-registering-file-types.html#quickly-change-file-type). You might want to do this if you have a babashka script and you don't want it to have a clj extension, for example. However, doing this produces an exception:
```
java.lang.NullPointerException: Cannot invoke "clojure.lang.Named.getName()" because "x" is null
	at clojure.core$name.invokeStatic(core.clj:1610)
	at clojure.core$name.invoke(core.clj:1604)
	at cursive.language$with_language.invokeStatic(language.clj:56)
	at cursive.language$with_language.invoke(language.clj:55)
	at cursive.extensions.clojure.core.resolve$global_var_meta.invokeStatic(resolve.clj:171)
	at cursive.extensions.clojure.core.resolve$global_var_meta.invoke(resolve.clj:105)
	at cursive.index$with_parsed.invokeStatic(index.clj:646)
	at cursive.index$with_parsed.invoke(index.clj:644)
...etc etc...
```

**Comment by cursive-ide** [comment]
Fix released in 1.13.1 on 2023-12-07.
