### ISSUE TITLE
Error generating stubs with 1.13.2

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/cursive#2891]
When generating stubs with Cursive 1.13.2, if the library includes `com.taoensso/timbre` then the following error is produced. This appears to be because timbre includes code referencing carmine (an appender), but does not include carmine as a dep. Presumably the library user includes carmine themselves if they want to use it with timbre.

```
WARNING: Error output generating stubs for module [REDACTED] (not all files generated)

Exit code: 1 
java.io.FileNotFoundException: Could not locate taoensso/carmine__init.class, taoensso/carmine.clj or taoensso/carmine.cljc on classpath.
at clojure.lang.RT.load(RT.java:462)
at clojure.lang.RT.load(RT.java:424)
at clojure.core$load$fn__6908.invoke(core.clj:6162)
at clojure.core$load.invokeStatic(core.clj:6161)
at clojure.core$load.doInvoke(core.clj:6145)
at clojure.lang.RestFn.invoke(RestFn.java:408)
at clojure.core$load_one.invokeStatic(core.clj:5934)
at clojure.core$load_one.invoke(core.clj:5929)
at clojure.core$load_lib$fn__6850.invoke(core.clj:5976)
at clojure.core$load_lib.invokeStatic(core.clj:5975)
at clojure.core$load_lib.doInvoke(core.clj:5954)
at clojure.lang.RestFn.applyTo(RestFn.java:142)
at clojure.core$apply.invokeStatic(core.clj:669)
at clojure.core$load_libs.invokeStatic(core.clj:6017)
at clojure.core$load_libs.doInvoke(core.clj:6001)
at clojure.lang.RestFn.applyTo(RestFn.java:137)
at clojure.core$apply.invokeStatic(core.clj:669)
at clojure.core$require.invokeStatic(core.clj:6039)
at clojure.core$require.doInvoke(core.clj:6039)
at clojure.lang.RestFn.invoke(RestFn.java:408)
at cursive.stubs.metadata.clojure$read_ns.invokeStatic(clojure.clj:67)
at cursive.stubs.metadata.clojure$read_ns.invoke(clojure.clj:66)
at user$eval255.invokeStatic(create-stub565394460323951236.clj:2)
at user$eval255.invoke(create-stub565394460323951236.clj:2)
at clojure.lang.Compiler.eval(Compiler.java:7194)
at clojure.lang.Compiler.load(Compiler.java:7653)
at clojure.lang.Compiler.loadFile(Compiler.java:7591)
at clojure.main$load_script.invokeStatic(main.clj:475)
at clojure.main$script_opt.invokeStatic(main.clj:535)
at clojure.main$script_opt.invoke(main.clj:530)
at clojure.main$main.invokeStatic(main.clj:664)
at clojure.main$main.doInvoke(main.clj:616)
at clojure.lang.RestFn.applyTo(RestFn.java:137)
at clojure.lang.Var.applyTo(Var.java:705)
at clojure.main.main(main.java:40)
```

**Comment by cursive-ide** [comment]
Fix released in 1.13.3 on 2024-04-04.
