### ISSUE TITLE
com.intellij.execution.ExecutionException: Error executing Leiningen task: Not implemented

### ISSUE THREAD

**Issue by jspyeatt** [cursive-ide/cursive#2901]
I am running intellij v2023.3.4 with cursive and I can't get leiningen working at all. When I try to use anything at such as running Tasks->help in the leiningen widget I'm seeing this in the logs. IntelliJ is running under amazon coretto 21.

Any help would be greatly appreciated.

```
2024-05-06 11:30:58,735 [239529820]   INFO - #c.i.e.r.ExecutionUtil - Error running 'Leiningen':<br>Error executing Leiningen task: Not implemented
com.intellij.execution.ExecutionException: Error executing Leiningen task: Not implemented
	at cursive.leiningen.run.LeiningenRunTaskConfiguration$getRunProfileState$state$1.createDeferredParameters(LeiningenRunTaskConfiguration.kt:139)
	at cursive.runner.DeferredCommandLineState.cacheDeferredParameters(Deferred.kt:72)
	at cursive.runner.AbstractDeferredRunner$execute$1.run(Deferred.kt:104)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:132)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:484)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:248)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:248)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:498)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.UnsupportedOperationException: Not implemented
	at me.bechberger.jfrplugin.runner.BasePluginRunConfigurationExtension.updateJavaParameters(BasePluginRunConfigurationExtension.kt:56)
	at cursive.runner.RunConfigurationExtensionsKt.extendJavaParameters(RunConfigurationExtensions.kt:38)
	at cursive.runner.BaseJvmClojureRunConfiguration.setCommonParams(ClojureRunnerBase.kt:225)
	at cursive.leiningen.run.LeiningenRunTaskConfiguration.access$setCommonParams(LeiningenRunTaskConfiguration.kt:60)
	at cursive.leiningen.run.LeiningenRunTaskConfiguration$getRunProfileState$state$1.createDeferredParameters(LeiningenRunTaskConfiguration.kt:129)
	... 24 more
```

**Comment by cursive-ide** [comment]
I think this line is the problem:

> Caused by: java.lang.UnsupportedOperationException: Not implemented
at me.bechberger.jfrplugin.runner.BasePluginRunConfigurationExtension.updateJavaParameters(BasePluginRunConfigurationExtension.kt:56)

I don’t know what the JFR plugin is, but dies disabling that help?

On Tue, May 7, 2024, at 4:53 AM, John Pyeatt wrote:
> 
> 
> I am running intellij v2023.3.4 with cursive and I can't get leiningen working at all. When I try to use anything at such as running Tasks->help in the leiningen widget I'm seeing this in the logs. IntelliJ is running under amazon coretto 21.
> 
> Any help would be greatly appreciated.
> 
> `2024-05-06 11:30:58,735 [239529820]   INFO - #c.i.e.r.ExecutionUtil - Error running 'Leiningen':<br>Error executing Leiningen task: Not implemented
> com.intellij.execution.ExecutionException: Error executing Leiningen task: Not implemented
> 	at cursive.leiningen.run.LeiningenRunTaskConfiguration$getRunProfileState$state$1.createDeferredParameters(LeiningenRunTaskConfiguration.kt:139)
> 	at cursive.runner.DeferredCommandLineState.cacheDeferredParameters(Deferred.kt:72)
> 	at cursive.runner.AbstractDeferredRunner$execute$1.run(Deferred.kt:104)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:434)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:132)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:484)
> 	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:248)
> 	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
> 	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
> 	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:248)
> 	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:498)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
> 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
> 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
> 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
> 	at java.base/java.lang.Thread.run(Thread.java:840)
> Caused by: java.lang.UnsupportedOperationException: Not implemented
> 	at me.bechberger.jfrplugin.runner.BasePluginRunConfigurationExtension.updateJavaParameters(BasePluginRunConfigurationExtension.kt:56)
> 	at cursive.runner.RunConfigurationExtensionsKt.extendJavaParameters(RunConfigurationExtensions.kt:38)
> 	at cursive.runner.BaseJvmClojureRunConfiguration.setCommonParams(ClojureRunnerBase.kt:225)
> 	at cursive.leiningen.run.LeiningenRunTaskConfiguration.access$setCommonParams(LeiningenRunTaskConfiguration.kt:60)
> 	at cursive.leiningen.run.LeiningenRunTaskConfiguration$getRunProfileState$state$1.createDeferredParameters(LeiningenRunTaskConfiguration.kt:129)
> 	... 24 more
`

**Comment by jspyeatt** [comment]
That plugin is the java flight recorder plugin. I did disable it. But things still didn't work. Eventually I got things working by upgrading cursive, disabling that plugin, clearing the ide cache and Reparing the IDE. Disabling the plugin in and of itself did nothing. But somehow the combination of all 4 steps got things back on track.
