### ISSUE TITLE
Exception when syncing projects with 1.13.4-eap1

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/cursive#2905]
When loading any project under IntelliJ 2024.1 with Cursive 1.13.4-eap1, the following exception is produced:

```
2024-05-19 14:23:06,234 [   3598]   WARN - #cursive.build.BuildSystemUtil - Current thread: Thread[ApplicationImpl pooled thread 15,4,main]; expected: Thread[AWT-EventQueue-0,6,main]
java.lang.IllegalStateException: Current thread: Thread[ApplicationImpl pooled thread 15,4,main]; expected: Thread[AWT-EventQueue-0,6,main]
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.checkWriteThreadAccess(ReadMostlyRWLock.java:315)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.checkForPossibilityOfWriteLock(ReadMostlyRWLock.java:250)
	at com.intellij.openapi.application.impl.RwLockHolder.startWrite(RwLockHolder.kt:507)
	at com.intellij.openapi.application.impl.RwLockHolder.runWriteAction(RwLockHolder.kt:352)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:888)
	at cursive.build.sync$initialise_paths_BANG_.invokeStatic(sync.clj:60)
	at cursive.build.sync$initialise_paths_BANG_.invoke(sync.clj:56)
	at cursive.deps.sync$sync_modules_BANG_.invokeStatic(sync.clj:198)
	at cursive.deps.sync$sync_modules_BANG_.invoke(sync.clj:165)
	at cursive.deps.sync$sync$fn__15598.invoke(sync.clj:390)
	at cursive.deps.sync$sync.invokeStatic(sync.clj:383)
	at cursive.deps.sync$sync.invoke(sync.clj:343)
	at clojure.lang.Var.invoke(Var.java:393)
	at cursive.api.DelayedFn.invoke(DelayedFn.java:41)
	at cursive.build.BuildSystemProjectsManager.reimportAllProjects$lambda$10$lambda$9(BuildSystemManager.kt:174)
	at cursive.build.BuildSystemUtil$runTask$1$1.run(BuildSystemUtil.kt:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:477)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:528)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:250)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:100)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:221)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:46)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:220)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:100)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:250)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:500)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:86)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:81)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:466)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by cursive-ide** [comment]
Fix released in 1.13.4-eap2 on 2024-05-19.
