### ISSUE TITLE
`idea diff` and `idea merge` fail to load due to Cursive error

### ISSUE THREAD

**Issue by nwjsmith** [cursive-ide/cursive#2998]
When running `idea diff` I get the following error:

```
2024-12-12 11:59:00,362 [     41]   WARN - #c.i.i.p.PluginManager - Plugin PluginDescriptor(name=Cursive, id=com.cursiveclojure.cursive, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2024.3/plugins/clojure-plugin, version=1.14.1-eap1-2024.3, package=null, isBundled=false) depends on Kotlin plugin via `cursive-kotlin.xml` but the plugin is not compatible with the Kotlin plugin in the  K2 mode. So, the `cursive-kotlin.xml` was not loaded
2024-12-12 11:59:00,716 [    395]   WARN - c.i.o.u.r.overrides - Conflicting registry key definition for key kotlin.mpp.tests.force.gradle: it was defined by plugin org.jetbrains.kotlin but redefined by plugin org.jetbrains.kotlin. Consider adding overrides="true" for one of the plugins, see the documentation for com.intellij.openapi.util.registry.RegistryKeyBean.overrides for more details.
2024-12-12 11:59:01,419 [   1098]   WARN - #c.i.o.e.c.i.EditorColorsManagerImpl - Cannot find scheme: Monokai from plugins: com.intellij.lang.jsgraphql
2024-12-12 11:59:02,434 [   2113] SEVERE - #c.i.o.a.i.AnyThreadWriteThreadingSupport - null
java.lang.ExceptionInInitializerError
        at clojure.java.api.Clojure.<clinit>(Clojure.java:97)
        at cursive.api.DelayedFn.getDelegate(DelayedFn.java:345)
        at cursive.api.DelayedFn.invoke(DelayedFn.java:31)
        at cursive.api.DelayedFn.getDelegate(DelayedFn.java:342)
        at cursive.api.DelayedFn.invoke(DelayedFn.java:31)
        at cursive.formatter.codeStyle.ClojureCodeStyleSettings.readExternal(ClojureCodeStyleSettings.java:126)
        at com.intellij.psi.codeStyle.CustomCodeStyleSettingsManager.readExternal(CustomCodeStyleSettingsManager.java:177)
        at com.intellij.psi.codeStyle.CodeStyleSettings.readExternal(CodeStyleSettings.java:579)
        at com.intellij.psi.impl.source.codeStyle.CodeStyleSchemeImpl.readFromDataHolder(CodeStyleSchemeImpl.java:64)
        at com.intellij.psi.impl.source.codeStyle.CodeStyleSchemeImpl.getCodeStyleSettings(CodeStyleSchemeImpl.java:86)
        at com.intellij.psi.codeStyle.CodeStyleSettingsManager.getCurrentSettings(CodeStyleSettingsManager.java:299)
        at com.intellij.application.options.CodeStyle.getDefaultSettings(CodeStyle.java:50)
        at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.createDocument(FileDocumentManagerImpl.java:228)
        at com.intellij.openapi.fileEditor.impl.FileDocumentManagerBase.getDocument(FileDocumentManagerBase.java:72)
        at com.intellij.diff.DiffContentFactoryImpl.lambda$createContentFromFile$0(DiffContentFactoryImpl.java:329)
        at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction(AnyThreadWriteThreadingSupport.kt:314)
        at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction(AnyThreadWriteThreadingSupport.kt:262)
        at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:863)
        at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:66)
        at com.intellij.diff.DiffContentFactoryImpl.createContentFromFile(DiffContentFactoryImpl.java:329)
        at com.intellij.diff.DiffContentFactoryImpl.createContentFromFile(DiffContentFactoryImpl.java:321)
        at com.intellij.diff.DiffContentFactoryImpl.create(DiffContentFactoryImpl.java:170)
        at com.intellij.ide.diff.DiffElement.createDiffContent(DiffElement.java:136)
        at com.intellij.openapi.diff.impl.dir.DirDiffPanel$MyDiffRequestProcessor.loadRequest(DirDiffPanel.java:561)
        at com.intellij.openapi.diff.impl.dir.DirDiffPanel$MyDiffRequestProcessor.loadRequest(DirDiffPanel.java:537)
        at com.intellij.diff.impl.CacheDiffRequestProcessor.doLoadRequest(CacheDiffRequestProcessor.java:176)
        at com.intellij.diff.impl.CacheDiffRequestProcessor.lambda$updateRequest$1(CacheDiffRequestProcessor.java:129)
        at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$computeInBackgroundAndTryWait$6(BackgroundTaskUtil.java:164)
        at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:223)
        at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:45)
        at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:222)
        at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$14(CoreProgressManager.java:674)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:749)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:705)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:673)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
        at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:203)
        at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$computeInBackgroundAndTryWait$7(BackgroundTaskUtil.java:163)
        at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport$executeOnPooledThread$1.run(AnyThreadWriteThreadingSupport.kt:167)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at com.intellij.util.concurrency.ContextCallable.lambda$call$1(ContextCallable.java:74)
        at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:83)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
        at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
        at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:107)
        at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:101)
        at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.io.FileNotFoundException: Could not locate clojure/core__init.class, clojure/core.clj or clojure/core.cljc on classpath.
        at clojure.lang.RT.load(RT.java:539)
        at clojure.lang.RT.load(RT.java:501)
        at clojure.lang.RT.<clinit>(RT.java:360)
        ... 55 more
2024-12-12 11:59:02,437 [   2116] SEVERE - #c.i.o.a.i.AnyThreadWriteThreadingSupport - IntelliJ IDEA 2024.3.1  Build #IU-243.22562.145
2024-12-12 11:59:02,437 [   2116] SEVERE - #c.i.o.a.i.AnyThreadWriteThreadingSupport - JDK: 21.0.5; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-12-12 11:59:02,437 [   2116] SEVERE - #c.i.o.a.i.AnyThreadWriteThreadingSupport - OS: Mac OS X
2024-12-12 11:59:02,438 [   2117] SEVERE - #c.i.o.a.i.AnyThreadWriteThreadingSupport - Plugin to blame: Cursive version: 1.14.1-eap1-2024.3
2024-12-12 11:59:02,438 [   2117] SEVERE - #c.i.o.a.i.AnyThreadWriteThreadingSupport - Last Action:
2024-12-12 11:59:02,621 [   2300] SEVERE - #c.i.o.a.i.AnyThreadWriteThreadingSupport - Could not initialize class clojure.java.api.Clojure
java.lang.NoClassDefFoundError: Could not initialize class clojure.java.api.Clojure
        at cursive.api.DelayedFn.getDelegate(DelayedFn.java:345)
        at cursive.api.DelayedFn.invoke(DelayedFn.java:31)
        at cursive.api.DelayedFn.getDelegate(DelayedFn.java:342)
        at cursive.api.DelayedFn.invoke(DelayedFn.java:31)
        at cursive.formatter.codeStyle.ClojureCodeStyleSettings.readExternal(ClojureCodeStyleSettings.java:126)
        at com.intellij.psi.codeStyle.CustomCodeStyleSettingsManager.readExternal(CustomCodeStyleSettingsManager.java:177)
        at com.intellij.psi.codeStyle.CodeStyleSettings.readExternal(CodeStyleSettings.java:579)
        at com.intellij.psi.impl.source.codeStyle.CodeStyleSchemeImpl.readFromDataHolder(CodeStyleSchemeImpl.java:64)
        at com.intellij.psi.impl.source.codeStyle.CodeStyleSchemeImpl.getCodeStyleSettings(CodeStyleSchemeImpl.java:86)
        at com.intellij.psi.codeStyle.CodeStyleSettingsManager.getCurrentSettings(CodeStyleSettingsManager.java:299)
        at com.intellij.application.options.CodeStyle.getDefaultSettings(CodeStyle.java:50)
        at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.createDocument(FileDocumentManagerImpl.java:228)
        at com.intellij.openapi.fileEditor.impl.FileDocumentManagerBase.getDocument(FileDocumentManagerBase.java:72)
        at com.intellij.diff.DiffContentFactoryImpl.lambda$createContentFromFile$0(DiffContentFactoryImpl.java:329)
        at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction(AnyThreadWriteThreadingSupport.kt:314)
        at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction(AnyThreadWriteThreadingSupport.kt:262)
        at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:863)
        at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:66)
        at com.intellij.diff.DiffContentFactoryImpl.createContentFromFile(DiffContentFactoryImpl.java:329)
        at com.intellij.diff.DiffContentFactoryImpl.createContentFromFile(DiffContentFactoryImpl.java:321)
        at com.intellij.diff.DiffContentFactoryImpl.create(DiffContentFactoryImpl.java:170)
        at com.intellij.ide.diff.DiffElement.createDiffContent(DiffElement.java:136)
        at com.intellij.openapi.diff.impl.dir.DirDiffPanel$MyDiffRequestProcessor.loadRequest(DirDiffPanel.java:561)
        at com.intellij.openapi.diff.impl.dir.DirDiffPanel$MyDiffRequestProcessor.loadRequest(DirDiffPanel.java:537)
        at com.intellij.diff.impl.CacheDiffRequestProcessor.doLoadRequest(CacheDiffRequestProcessor.java:176)
        at com.intellij.diff.impl.CacheDiffRequestProcessor.lambda$updateRequest$1(CacheDiffRequestProcessor.java:129)
        at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$computeInBackgroundAndTryWait$6(BackgroundTaskUtil.java:164)
        at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:223)
        at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:45)
        at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:222)
        at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$14(CoreProgressManager.java:674)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:749)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:705)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:673)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
        at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:203)
        at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$computeInBackgroundAndTryWait$7(BackgroundTaskUtil.java:163)
        at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport$executeOnPooledThread$1.run(AnyThreadWriteThreadingSupport.kt:167)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at com.intellij.util.concurrency.ContextCallable.lambda$call$1(ContextCallable.java:74)
        at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:83)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
        at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
        at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:107)
        at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:101)
        at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.ExceptionInInitializerError [in thread "ApplicationImpl pooled thread 2"]
        at clojure.java.api.Clojure.<clinit>(Clojure.java:97)
        ... 54 more
2024-12-12 11:59:02,622 [   2301] SEVERE - #c.i.o.a.i.AnyThreadWriteThreadingSupport - IntelliJ IDEA 2024.3.1  Build #IU-243.22562.145
2024-12-12 11:59:02,622 [   2301] SEVERE - #c.i.o.a.i.AnyThreadWriteThreadingSupport - JDK: 21.0.5; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-12-12 11:59:02,622 [   2301] SEVERE - #c.i.o.a.i.AnyThreadWriteThreadingSupport - OS: Mac OS X
2024-12-12 11:59:02,623 [   2302] SEVERE - #c.i.o.a.i.AnyThreadWriteThreadingSupport - Plugin to blame: Cursive version: 1.14.1-eap1-2024.3
2024-12-12 11:59:02,623 [   2302] SEVERE - #c.i.o.a.i.AnyThreadWriteThreadingSupport - Last Action:
```

and likewise, when I run `idea merge`, I get a similar error:

```
2024-12-12 12:00:08,852 [     42]   WARN - #c.i.i.p.PluginManager - Plugin PluginDescriptor(name=Cursive, id=com.cursiveclojure.cursive, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2024.3/plugins/clojure-plugin, version=1.14.1-eap1-2024.3, package=null, isBundled=false) depends on Kotlin plugin via `cursive-kotlin.xml` but the plugin is not compatible with the Kotlin plugin in the  K2 mode. So, the `cursive-kotlin.xml` was not loaded
2024-12-12 12:00:09,275 [    465]   WARN - c.i.o.u.r.overrides - Conflicting registry key definition for key kotlin.mpp.tests.force.gradle: it was defined by plugin org.jetbrains.kotlin but redefined by plugin org.jetbrains.kotlin. Consider adding overrides="true" for one of the plugins, see the documentation for com.intellij.openapi.util.registry.RegistryKeyBean.overrides for more details.
2024-12-12 12:00:10,055 [   1245]   WARN - #c.i.o.e.c.i.EditorColorsManagerImpl - Cannot find scheme: Monokai from plugins: com.intellij.lang.jsgraphql
2024-12-12 12:00:10,765 [   1955]   WARN - #c.i.d.m.MergeRequestProcessor - Cannot show diff: null
com.intellij.diff.chains.DiffRequestProducerException: Cannot show diff: null
        at com.intellij.diff.applications.MergeApplication$MyMergeRequestProducer.process(MergeApplication.kt:90)
        at com.intellij.diff.merge.MergeRequestProcessor.lambda$init$2(MergeRequestProcessor.java:137)
        at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$submitTask$8(BackgroundTaskUtil.java:266)
        at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$createBackgroundTask$10(BackgroundTaskUtil.java:302)
        at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:98)
        at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:223)
        at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:45)
        at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:222)
        at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$14(CoreProgressManager.java:674)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:749)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:705)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:673)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
        at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:203)
        at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:98)
        at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$createBackgroundTask$11(BackgroundTaskUtil.java:297)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
        at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
        at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:107)
        at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:101)
        at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ExceptionInInitializerError
        at clojure.java.api.Clojure.<clinit>(Clojure.java:97)
        at cursive.api.DelayedFn.getDelegate(DelayedFn.java:345)
        at cursive.api.DelayedFn.invoke(DelayedFn.java:31)
        at cursive.api.DelayedFn.getDelegate(DelayedFn.java:342)
        at cursive.api.DelayedFn.invoke(DelayedFn.java:31)
        at cursive.formatter.codeStyle.ClojureCodeStyleSettings.readExternal(ClojureCodeStyleSettings.java:126)
        at com.intellij.psi.codeStyle.CustomCodeStyleSettingsManager.readExternal(CustomCodeStyleSettingsManager.java:177)
        at com.intellij.psi.codeStyle.CodeStyleSettings.readExternal(CodeStyleSettings.java:579)
        at com.intellij.psi.impl.source.codeStyle.CodeStyleSchemeImpl.readFromDataHolder(CodeStyleSchemeImpl.java:64)
        at com.intellij.psi.impl.source.codeStyle.CodeStyleSchemeImpl.getCodeStyleSettings(CodeStyleSchemeImpl.java:86)
        at com.intellij.psi.codeStyle.CodeStyleSettingsManager.getCurrentSettings(CodeStyleSettingsManager.java:299)
        at com.intellij.application.options.CodeStyle.getDefaultSettings(CodeStyle.java:50)
        at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.createDocument(FileDocumentManagerImpl.java:228)
        at com.intellij.openapi.fileEditor.impl.FileDocumentManagerBase.getDocument(FileDocumentManagerBase.java:72)
        at com.intellij.diff.DiffRequestFactoryImpl.lambda$createTextMergeRequest$0(DiffRequestFactoryImpl.java:336)
        at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction(AnyThreadWriteThreadingSupport.kt:314)
        at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction(AnyThreadWriteThreadingSupport.kt:262)
        at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:863)
        at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:66)
        at com.intellij.diff.DiffRequestFactoryImpl.createTextMergeRequest(DiffRequestFactoryImpl.java:336)
        at com.intellij.diff.DiffRequestFactoryImpl.createTextMergeRequest(DiffRequestFactoryImpl.java:322)
        at com.intellij.diff.DiffRequestFactoryImpl.createTextMergeRequest(DiffRequestFactoryImpl.java:310)
        at com.intellij.diff.DiffRequestFactoryImpl.createTextMergeRequestFromFiles(DiffRequestFactoryImpl.java:436)
        at com.intellij.diff.DiffRequestFactoryImpl.createMergeRequestFromFiles(DiffRequestFactoryImpl.java:411)
        at com.intellij.diff.DiffRequestFactoryImpl.createMergeRequestFromFiles(DiffRequestFactoryImpl.java:396)
        at com.intellij.diff.applications.MergeApplication$MyMergeRequestProducer.process(MergeApplication.kt:79)
        ... 28 more
Caused by: java.io.FileNotFoundException: Could not locate clojure/core__init.class, clojure/core.clj or clojure/core.cljc on classpath.
        at clojure.lang.RT.load(RT.java:539)
        at clojure.lang.RT.load(RT.java:501)
        at clojure.lang.RT.<clinit>(RT.java:360)
        ... 54 more
Error: Failed to resolve conflicts
```

**Comment by nwjsmith** [comment]
Sorry, I forgot to mention that this is Cursive 1.14.1-eap1-2024.3 running on IntelliJ IDEA 2024.3.1

**Comment by cursive-ide** [comment]
Just to clarify, are you running this as a command line tool?

**Comment by nwjsmith** [comment]
Yes, from the command line as the merge/diff tool for Jujutsu.

**Comment by nwjsmith** [comment]
I've created a reproducer here: https://github.com/nwjsmith/cursive-intellij-merge-diff-reproducer

**Comment by nwjsmith** [comment]
The error doesn't occur when I have a Clojure project already loaded in IntelliJ and I launch from the CLI, but it does show up when launching fresh.

An aside: sorry for how disjointed this bug report is. If there's anything I can do to further pinpoint the issue (maybe trying different versions of Cursive?) let me know.
