### ISSUE TITLE
Additional source path outside of project dir not included (no additional content root generated)

### ISSUE THREAD

**Issue by vmarcinko** [cursive-ide/cursive#324]
If additional source path is setup to be outside of project root dir (eg. for some development purposes to reference other source dirs), then cursive should generate additional "content root" for this module (beside main one corresponding to project root dir) that includes this path. 

Here is example of project.clj piece:
```
  :profiles     {:dev {:dependencies [[org.clojure/clojure      "1.5.1"]
                                                       [com.cemerick/pomegranate "0.2.0"]
                                                       [digest                   "1.4.3"]]
                       :source-paths ["../boot/src" "src"]}})
And error is reported:
The file 'C:/IdeaProjects/open_source/boot/src' is not under content entry root 'C:/IdeaProjects/open_source/boot.core'
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:113)
	at com.intellij.openapi.roots.impl.ContentEntryImpl.b(ContentEntryImpl.java:332)
	at com.intellij.openapi.roots.impl.ContentEntryImpl.a(ContentEntryImpl.java:284)
	at com.intellij.openapi.roots.impl.ContentEntryImpl.a(ContentEntryImpl.java:279)
	at com.intellij.openapi.roots.impl.ContentEntryImpl.addSourceFolder(ContentEntryImpl.java:203)
	at com.intellij.openapi.roots.impl.ContentEntryImpl.addSourceFolder(ContentEntryImpl.java:210)
	at com.intellij.openapi.roots.impl.ContentEntryImpl.addSourceFolder(ContentEntryImpl.java:196)
	at com.intellij.openapi.roots.impl.ContentEntryImpl.addSourceFolder(ContentEntryImpl.java:189)
	at cursive.leiningen.module.ModuleCreationUtils$1.run(ModuleCreationUtils.java:110)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:37)
	at com.intellij.openapi.application.WriteAction$1$1.run(WriteAction.java:47)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:981)
```

**Comment by cursive-ide** [comment]
See [here](https://youtrack.jetbrains.com/issue/IDEA-122577#comment=27-1158589) for implementation discussion.
