### ISSUE TITLE
Unable to start a local REPL with the created configuration

### ISSUE THREAD

**Issue by jmgimeno** [cursive-ide/cursive#369]
I create a REPL configuration by right clicking on project.clj

```
(defproject regexps "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.5.1"]]
  :main regexps.core)
```

And I get the following error:

```
Exception in thread "main" java.io.FileNotFoundException: Could not locate cljsbuild/compiler__init.class or cljsbuild/compiler.clj on classpath: 
```

which has no sense, because it is no a clojurescript project.

lein repl works perfecty on the command line.

My configuration for leiningen is the brew installed one and its path is:

```
/usr/local/Cellar/leiningen/2.3.4/bin/lein
```

with neither leiningen home nor leiningen jar overriden.

```
Starting nREPL server...
/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/bin/java -Dclojure.compile.path=/Users/jmgimeno/Dropbox/Developer/owned/regexps/target/classes -Dregexps.version=0.1.0-SNAPSHOT -Dfile.encoding=UTF-8 -Dclojure.debug=false -Didea.launcher.port=7533 "-Didea.launcher.bin.path=/Applications/IntelliJ IDEA 13.app/bin" -classpath "/Users/jmgimeno/Dropbox/Developer/owned/regexps/test:/Users/jmgimeno/Dropbox/Developer/owned/regexps/src:/Users/jmgimeno/Dropbox/Developer/owned/regexps/dev-resources:/Users/jmgimeno/Dropbox/Developer/owned/regexps/resources:/Users/jmgimeno/Dropbox/Developer/owned/regexps/target/classes:/Users/jmgimeno/.m2/repository/clojure-complete/clojure-complete/0.2.3/clojure-complete-0.2.3.jar:/Users/jmgimeno/.m2/repository/org/clojure/tools.nrepl/0.2.3/tools.nrepl-0.2.3.jar:/Users/jmgimeno/.m2/repository/org/clojure/clojure/1.5.1/clojure-1.5.1.jar:/Applications/IntelliJ IDEA 13.app/lib/idea_rt.jar" com.intellij.rt.execution.application.AppMain clojure.main -i /private/var/folders/xp/5sxgh_ln64z9lqrhbb5ncl740000gn/T/form-init2384622675151845250.clj
Exception in thread "main" java.io.FileNotFoundException: Could not locate cljsbuild/compiler__init.class or cljsbuild/compiler.clj on classpath: 
    at clojure.lang.RT.load(RT.java:443)
    at clojure.lang.RT.load(RT.java:411)
    at clojure.core$load$fn__5018.invoke(core.clj:5530)
    at clojure.core$load.doInvoke(core.clj:5529)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5336)
    at clojure.core$load_lib$fn__4967.invoke(core.clj:5375)
    at clojure.core$load_lib.doInvoke(core.clj:5374)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:619)
    at clojure.core$load_libs.doInvoke(core.clj:5413)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:619)
    at clojure.core$require.doInvoke(core.clj:5496)
    at clojure.lang.RestFn.invoke(RestFn.java:436)
    at user$eval7.invoke(form-init2384622675151845250.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6619)
    at clojure.lang.Compiler.eval(Compiler.java:6608)
    at clojure.lang.Compiler.load(Compiler.java:7064)
    at clojure.lang.Compiler.loadFile(Compiler.java:7020)
    at clojure.main$load_script.invoke(main.clj:294)
    at clojure.main$init_opt.invoke(main.clj:299)
    at clojure.main$initialize.invoke(main.clj:327)
    at clojure.main$null_opt.invoke(main.clj:362)
    at clojure.main$main.doInvoke(main.clj:440)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:419)
    at clojure.lang.AFn.applyToHelper(AFn.java:163)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.main.main(main.java:37)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

Process finished with exit code 1
No nREPL ack received
```

**Comment by viesti** [comment]
Any progress on this issue?

**Comment by cursiveclojure** [comment]
No - this is a downstream issue. cemerick closed the associated issue because after 18 months no-one had offered a patch to fix it. It's annoying for Cursive users, but realistically I don't know that toolchain at all, and people who do still couldn't figure it out, so I can't invest that much time trying to fix it myself. If anyone else wants to I'll be delighted, though!

**Comment by viesti** [comment]
Ok. Just a hunch, but this could be related to http://dev.clojure.org/jira/browse/CLJ-1544 (referenced from https://github.com/cemerick/austin/issues/23).

**Comment by cursiveclojure** [comment]
Hmm, nice catch - that does look plausible, since Cursive is AOT compiled and unfortunately since AOT is infectious in Clojure right now, that means that the nREPL etc that I'm using is also AOT compiled. I'll need to read that issue more closely to see if I can come up with a plausible explanation for what is happening and perhaps a fix.

**Comment by cursiveclojure** [comment]
There's another pointer that it might be the same issue - [CLJ-1544](http://dev.clojure.org/jira/browse/CLJ-1544) has been rolled back for the moment because it causes an issue with Clojure 1.7 alpha 5, but only under JDK 7, not JDK 8. I almost certainly tried to use JDK 7 to reproduce the issue originally, and I could reproduce the issue with `lein repl` - @jmgimeno could not reproduce it using `lein repl`, but he's on JDK 8.

**Comment by puredanger** [comment]
CLJ-1544 was not rolled back because of a JDK-specific problem. We just want to get more clarity about the root problem and potential fixes.

**Comment by cursiveclojure** [comment]
@puredanger Sure, but it seems like the issue with the patch could be reproduced on JDK 7 but not JDK 8, right? Anyway, just looking for similarities with this problem.

**Comment by puredanger** [comment]
No, that was an early (and wrong) assumption.

**Comment by micahasmith** [comment]
today i had this issue, i rebooted intellij and it started working again

**Comment by terjedahl** [comment]
**Similar/related issue?**
I have been working on a Leiningen plugin.  
I use "hooks" to extend the classpath, and can se that when I do `lein repl` my hook is called, and my classpath is appended.
But when I run rREPL w/Leiningen in Cursive IDE / IntelliJ, my neither middleware nor hooks are called, and classpath is not appended.

My workaround is the same as above: 
1.  Do `lein repl`  or `lein repl :headless`
2.  Run a remote nREPL client to connect it (using the "Leiningen REPL port" option).

**Comment by aaronblenkush** [comment]
I experienced this issue when I had Parameters set to "dev.clj", a file that did not exist. The issue was resolved by clearing that value. This is the Parameters field under Common Options in the Run/Debug Configuration for a Local Clojure REPL.

**Comment by danielcompton** [comment]
This hit me too, in my I got around it by commenting out `[lein-figwheel "0.6.5"]` from `[:profiles :dev :plugins]`.

**Comment by mmower** [comment]
I have a project doing this. It's a fresh project created with:

lein new re-frame <prjname> +handler +re-com +re-frisk

Starting nREPL server...
/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/bin/java -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:58503,suspend=y,server=n -Dfile.encoding=UTF-8 -XX:-OmitStackTraceInFastThrow -Dclojure.compile.path=/Users/matt/Projects/Play/smiley/target/classes -Dsmiley.version=0.1.0-SNAPSHOT -Dclojure.debug=false -classpath "/Users/matt/Projects/Play/smiley/test:/Users/matt/Projects/Play/smiley/src/clj:/Users/matt/Projects/Play/smiley/dev-resources:/Users/matt/Projects/Play/smiley/resources:/Users/matt/Projects/Play/smiley/target/classes:/Users/matt/.m2/repository/org/eclipse/jetty/jetty-http/9.2.10.v20150310/jetty-http-9.2.10.v20150310.jar:/Users/matt/.m2/repository/org/clojure/java.classpath/0.2.2/java.classpath-0.2.2.jar:/Users/matt/.m2/repository/org/clojure/clojure/1.8.0/clojure-1.8.0.jar:/Users/matt/.m2/repository/instaparse/instaparse/1.4.0/instaparse-1.4.0.jar:/Users/matt/.m2/repository/medley/medley/0.7.3/medley-0.7.3.jar:/Users/matt/.m2/repository/ring/ring-devel/1.4.0/ring-devel-1.4.0.jar:/Users/matt/.m2/repository/org/eclipse/jetty/jetty-server/9.2.10.v20150310/jetty-server-9.2.10.v20150310.jar:/Users/matt/.m2/repository/org/clojure/tools.macro/0.1.5/tools.macro-0.1.5.jar:/Users/matt/.m2/repository/data-frisk-reagent/data-frisk-reagent/0.3.5/data-frisk-reagent-0.3.5.jar:/Users/matt/.m2/repository/reagent/reagent/0.6.0/reagent-0.6.0.jar:/Users/matt/.m2/repository/ring/ring-codec/1.0.0/ring-codec-1.0.0.jar:/Users/matt/.m2/repository/org/clojure/tools.analyzer.jvm/0.6.10/tools.analyzer.jvm-0.6.10.jar:/Users/matt/.m2/repository/com/cognitect/transit-cljs/0.8.239/transit-cljs-0.8.239.jar:/Users/matt/.m2/repository/ring/ring-servlet/1.4.0/ring-servlet-1.4.0.jar:/Users/matt/.m2/repository/clj-time/clj-time/0.9.0/clj-time-0.9.0.jar:/Users/matt/.m2/repository/re-frisk/re-frisk/0.3.2/re-frisk-0.3.2.jar:/Users/matt/.m2/repository/re-com/re-com/0.8.3/re-com-0.8.3.jar:/Users/matt/.m2/repository/org/clojure/tools.analyzer/0.6.9/tools.analyzer-0.6.9.jar:/Users/matt/.m2/repository/org/clojure/tools.nrepl/0.2.12/tools.nrepl-0.2.12.jar:/Users/matt/.m2/repository/com/google/javascript/closure-compiler-externs/v20160315/closure-compiler-externs-v20160315.jar:/Users/matt/.m2/repository/clojure-complete/clojure-complete/0.2.4/clojure-complete-0.2.4.jar:/Users/matt/.m2/repository/args4j/args4j/2.0.26/args4j-2.0.26.jar:/Users/matt/.m2/repository/cljsjs/react-dom-server/15.2.1-0/react-dom-server-15.2.1-0.jar:/Users/matt/.m2/repository/binaryage/devtools/0.8.2/devtools-0.8.2.jar:/Users/matt/.m2/repository/org/clojure/core.async/0.2.391/core.async-0.2.391.jar:/Users/matt/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar:/Users/matt/.m2/repository/yogthos/config/0.8/config-0.8.jar:/Users/matt/.m2/repository/crypto-equality/crypto-equality/1.0.0/crypto-equality-1.0.0.jar:/Users/matt/.m2/repository/ring/ring-jetty-adapter/1.4.0/ring-jetty-adapter-1.4.0.jar:/Users/matt/.m2/repository/org/clojure/google-closure-library-third-party/0.0-20160609-f42b4a24/google-closure-library-third-party-0.0-20160609-f42b4a24.jar:/Users/matt/.m2/repository/org/clojure/google-closure-library/0.0-20160609-f42b4a24/google-closure-library-0.0-20160609-f42b4a24.jar:/Users/matt/.m2/repository/org/clojure/core.memoize/0.5.9/core.memoize-0.5.9.jar:/Users/matt/.m2/repository/com/cognitect/transit-js/0.8.846/transit-js-0.8.846.jar:/Users/matt/.m2/repository/hiccup/hiccup/1.0.5/hiccup-1.0.5.jar:/Users/matt/.m2/repository/re-frame/re-frame/0.9.1/re-frame-0.9.1.jar:/Users/matt/.m2/repository/org/clojure/tools.logging/0.3.1/tools.logging-0.3.1.jar:/Users/matt/.m2/repository/com/andrewmcveigh/cljs-time/0.4.0/cljs-time-0.4.0.jar:/Users/matt/.m2/repository/org/eclipse/jetty/jetty-io/9.2.10.v20150310/jetty-io-9.2.10.v20150310.jar:/Users/matt/.m2/repository/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar:/Users/matt/.m2/repository/ring/ring-core/1.4.0/ring-core-1.4.0.jar:/Users/matt/.m2/repository/commons-codec/commons-codec/1.6/commons-codec-1.6.jar:/Users/matt/.m2/repository/cljsjs/react-dom/15.2.1-0/react-dom-15.2.1-0.jar:/Users/matt/.m2/repository/org/ow2/asm/asm-all/4.2/asm-all-4.2.jar:/Users/matt/.m2/repository/org/clojure/tools.namespace/0.2.10/tools.namespace-0.2.10.jar:/Users/matt/.m2/repository/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar:/Users/matt/.m2/repository/org/clojure/data.json/0.2.6/data.json-0.2.6.jar:/Users/matt/.m2/repository/org/clojure/data.priority-map/0.0.7/data.priority-map-0.0.7.jar:/Users/matt/.m2/repository/ring/ring/1.4.0/ring-1.4.0.jar:/Users/matt/.m2/repository/org/clojure/tools.reader/1.0.0-beta3/tools.reader-1.0.0-beta3.jar:/Users/matt/.m2/repository/compojure/compojure/1.5.0/compojure-1.5.0.jar:/Users/matt/.m2/repository/crypto-random/crypto-random/1.2.0/crypto-random-1.2.0.jar:/Users/matt/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar:/Users/matt/.m2/repository/com/google/javascript/closure-compiler-unshaded/v20160315/closure-compiler-unshaded-v20160315.jar:/Users/matt/.m2/repository/ns-tracker/ns-tracker/0.3.0/ns-tracker-0.3.0.jar:/Users/matt/.m2/repository/org/mozilla/rhino/1.7R5/rhino-1.7R5.jar:/Users/matt/.m2/repository/org/clojure/clojurescript/1.9.229/clojurescript-1.9.229.jar:/Users/matt/.m2/repository/joda-time/joda-time/2.6/joda-time-2.6.jar:/Users/matt/.m2/repository/commons-fileupload/commons-fileupload/1.3.1/commons-fileupload-1.3.1.jar:/Users/matt/.m2/repository/org/eclipse/jetty/jetty-util/9.2.10.v20150310/jetty-util-9.2.10.v20150310.jar:/Users/matt/.m2/repository/com/google/guava/guava/19.0/guava-19.0.jar:/Users/matt/.m2/repository/org/clojure/core.cache/0.6.5/core.cache-0.6.5.jar:/Users/matt/.m2/repository/cljsjs/react/15.2.1-0/react-15.2.1-0.jar:/Users/matt/.m2/repository/clout/clout/2.1.2/clout-2.1.2.jar:/Users/matt/.m2/repository/clj-stacktrace/clj-stacktrace/0.2.8/clj-stacktrace-0.2.8.jar:/Users/matt/.m2/repository/com/google/protobuf/protobuf-java/2.5.0/protobuf-java-2.5.0.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar" clojure.main -i /private/var/folders/dw/tmf07r7n1cv6khc7rc35q4cw0000gn/T/form-init6664503631468015144.clj
Connected to the target VM, address: '127.0.0.1:58503', transport: 'socket'
Exception in thread "main" java.io.FileNotFoundException: Could not locate cljsbuild/compiler__init.class or cljsbuild/compiler.clj on classpath., compiling:(/private/var/folders/dw/tmf07r7n1cv6khc7rc35q4cw0000gn/T/form-init6664503631468015144.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.io.FileNotFoundException: Could not locate cljsbuild/compiler__init.class or cljsbuild/compiler.clj on classpath.
	at clojure.lang.RT.load(RT.java:456)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at user$eval9.invokeStatic(form-init6664503631468015144.clj:1)
	at user$eval9.invoke(form-init6664503631468015144.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	... 14 more
Disconnected from the target VM, address: '127.0.0.1:58503', transport: 'socket'

Process finished with exit code 1
Exception starting REPL: java.lang.InterruptedException
