### ISSUE TITLE
Deleting last defn in a namespace breaks IntelliJ UI

### ISSUE THREAD

**Issue by voj** [cursive-ide/cursive#565]
IntelliJ 13.1.5, Cursive-13.1-0.1.40

I can reproduce this reliably:
- find the usages of the last defn in a namespace
- select and delete the defn
- an Exception is logged and the UI redraw breaks, requiring me to restart IntelliJ
- (UI redraw is partially fixed when undoing the delete without restarting)
- usage window must be open for bug to occur.

```
chars sequence.length:11942, start:12054, end:12060: chars sequence.length:11942, start:12054, end:12060
java.lang.IndexOutOfBoundsException: chars sequence.length:11942, start:12054, end:12060
    at com.intellij.util.text.CharSequenceSubSequence.<init>(CharSequenceSubSequence.java:32)
    at com.intellij.util.text.ImmutableText.subSequence(ImmutableText.java:383)
    at com.intellij.openapi.editor.impl.DocumentImpl$6.compute(DocumentImpl.java:812)
    at com.intellij.openapi.editor.impl.DocumentImpl$6.compute(DocumentImpl.java:809)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:921)
    at com.intellij.openapi.editor.impl.DocumentImpl.getText(DocumentImpl.java:809)
    at plugin.symbol$arglists$fn__9052.invoke(symbol.clj:83)
    at clojure.core$mapv$fn__6258.invoke(core.clj:6241)
    at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:58)
    at clojure.core.protocols$fn__6041.invoke(protocols.clj:98)
    at clojure.core.protocols$fn__6005$G__6000__6014.invoke(protocols.clj:19)
    at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31)
    at clojure.core.protocols$fn__6024.invoke(protocols.clj:60)
    at clojure.core.protocols$fn__5979$G__5974__5992.invoke(protocols.clj:13)
    at clojure.core$reduce.invoke(core.clj:6177)
    at clojure.core$mapv.invoke(core.clj:6241)
    at plugin.symbol$arglists.invoke(symbol.clj:83)
    at plugin.symbol$icon.invoke(symbol.clj:106)
    at clojure.lang.Var.invoke(Var.java:415)
    at cursive.psi.impl.synthetic.SyntheticSymbol.getIcon(SyntheticSymbol.java:176)
    at cursive.psi.impl.synthetic.SyntheticSymbol$2.getIcon(SyntheticSymbol.java:194)
    at com.intellij.ui.ComputableIcon$2.compute(ComputableIcon.java:59)
    at com.intellij.ui.ComputableIcon$2.compute(ComputableIcon.java:56)
    at com.intellij.ui.ComputableIcon.getIcon(ComputableIcon.java:38)
    at com.intellij.find.findUsages.PsiElement2UsageTargetAdapter.getIcon(PsiElement2UsageTargetAdapter.java:283)
    at com.intellij.usages.impl.UsageViewTreeCellRenderer.customizeCellRenderer(UsageViewTreeCellRenderer.java:112)
    at com.intellij.ui.ColoredTreeCellRenderer.getTreeCellRendererComponent(ColoredTreeCellRenderer.java:116)
    at javax.swing.plaf.basic.BasicTreeUI$NodeDimensionsHandler.getNodeDimensions(BasicTreeUI.java:2718)
    at javax.swing.tree.AbstractLayoutCache.getNodeDimensions(AbstractLayoutCache.java:475)
    at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.updatePreferredSize(VariableHeightLayoutCache.java:1342)
    at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.updatePreferredSize(VariableHeightLayoutCache.java:1333)
    at javax.swing.tree.VariableHeightLayoutCache.treeNodesChanged(VariableHeightLayoutCache.java:418)
    at javax.swing.plaf.basic.BasicTreeUI$Handler.treeNodesChanged(BasicTreeUI.java:3765)
    at javax.swing.tree.DefaultTreeModel.fireTreeNodesChanged(DefaultTreeModel.java:468)
    at javax.swing.tree.DefaultTreeModel.nodesChanged(DefaultTreeModel.java:330)
    at javax.swing.tree.DefaultTreeModel.nodeChanged(DefaultTreeModel.java:261)
    at com.intellij.usages.impl.Node.update(Node.java:113)
    at com.intellij.usages.impl.UsageViewImpl.checkNodeValidity(UsageViewImpl.java:1091)
    at com.intellij.usages.impl.UsageViewImpl.checkNodeValidity(UsageViewImpl.java:1085)
    at com.intellij.usages.impl.UsageViewImpl.checkNodeValidity(UsageViewImpl.java:1085)
    at com.intellij.usages.impl.UsageViewImpl.updateImmediately(UsageViewImpl.java:1039)
    at com.intellij.usages.impl.UsageViewImpl.access$3300(UsageViewImpl.java:88)
    at com.intellij.usages.impl.UsageViewImpl$27$1.run(UsageViewImpl.java:1105)
    at com.intellij.psi.impl.PsiDocumentManagerBase.cancelAndRunWhenAllCommitted(PsiDocumentManagerBase.java:254)
    at com.intellij.usages.impl.UsageViewImpl$27.run(UsageViewImpl.java:1102)
    at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
    at com.intellij.util.Alarm$Request$1.run(Alarm.java:327)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:319)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:697)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)



java.lang.IndexOutOfBoundsException: chars sequence.length:11942, start:12054, end:12060
    at com.intellij.util.text.CharSequenceSubSequence.<init>(CharSequenceSubSequence.java:32)
    at com.intellij.util.text.ImmutableText.subSequence(ImmutableText.java:383)
    at com.intellij.openapi.editor.impl.DocumentImpl$6.compute(DocumentImpl.java:812)
    at com.intellij.openapi.editor.impl.DocumentImpl$6.compute(DocumentImpl.java:809)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:921)
    at com.intellij.openapi.editor.impl.DocumentImpl.getText(DocumentImpl.java:809)
    at plugin.symbol$arglists$fn__9052.invoke(symbol.clj:83)
    at clojure.core$mapv$fn__6258.invoke(core.clj:6241)
    at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:58)
    at clojure.core.protocols$fn__6041.invoke(protocols.clj:98)
    at clojure.core.protocols$fn__6005$G__6000__6014.invoke(protocols.clj:19)
    at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31)
    at clojure.core.protocols$fn__6024.invoke(protocols.clj:60)
    at clojure.core.protocols$fn__5979$G__5974__5992.invoke(protocols.clj:13)
    at clojure.core$reduce.invoke(core.clj:6177)
    at clojure.core$mapv.invoke(core.clj:6241)
    at plugin.symbol$arglists.invoke(symbol.clj:83)
    at plugin.symbol$icon.invoke(symbol.clj:106)
    at clojure.lang.Var.invoke(Var.java:415)
    at cursive.psi.impl.synthetic.SyntheticSymbol.getIcon(SyntheticSymbol.java:176)
    at cursive.psi.impl.synthetic.SyntheticSymbol$2.getIcon(SyntheticSymbol.java:194)
    at com.intellij.ui.ComputableIcon$2.compute(ComputableIcon.java:59)
    at com.intellij.ui.ComputableIcon$2.compute(ComputableIcon.java:56)
    at com.intellij.ui.ComputableIcon.getIcon(ComputableIcon.java:38)
    at com.intellij.find.findUsages.PsiElement2UsageTargetAdapter.getIcon(PsiElement2UsageTargetAdapter.java:283)
    at com.intellij.usages.impl.UsageViewTreeCellRenderer.customizeCellRenderer(UsageViewTreeCellRenderer.java:112)
    at com.intellij.ui.ColoredTreeCellRenderer.getTreeCellRendererComponent(ColoredTreeCellRenderer.java:116)
    at javax.swing.plaf.basic.BasicTreeUI.paintRow(BasicTreeUI.java:1491)
    at com.intellij.util.ui.tree.WideSelectionTreeUI.paintRow(WideSelectionTreeUI.java:401)
    at javax.swing.plaf.basic.BasicTreeUI.paint(BasicTreeUI.java:1203)
    at com.intellij.util.ui.tree.WideSelectionTreeUI.paint(WideSelectionTreeUI.java:429)
    at javax.swing.plaf.ComponentUI.update(ComponentUI.java:153)
    at javax.swing.JComponent.paintComponent(JComponent.java:760)
    at com.intellij.ui.treeStructure.Tree.paintComponent(Tree.java:328)
    at javax.swing.JComponent.paint(JComponent.java:1037)
    at com.intellij.ui.treeStructure.Tree.paint(Tree.java:244)
    at javax.swing.JComponent.paintChildren(JComponent.java:870)
    at javax.swing.JComponent.paint(JComponent.java:1046)
    at javax.swing.JViewport.paint(JViewport.java:795)
    at com.intellij.ui.components.JBViewport.paint(JBViewport.java:119)
    at javax.swing.JComponent.paintChildren(JComponent.java:870)
    at javax.swing.JComponent.paint(JComponent.java:1046)
    at javax.swing.JComponent.paintChildren(JComponent.java:870)
    at javax.swing.JComponent.paint(JComponent.java:1046)
    at javax.swing.JComponent.paintChildren(JComponent.java:870)
    at javax.swing.JComponent.paint(JComponent.java:1046)
    at javax.swing.JComponent.paintChildren(JComponent.java:870)
    at javax.swing.JComponent.paint(JComponent.java:1046)
    at javax.swing.JComponent.paintChildren(JComponent.java:870)
    at javax.swing.JComponent.paint(JComponent.java:1046)
    at javax.swing.JComponent.paintChildren(JComponent.java:870)
    at javax.swing.JComponent.paint(JComponent.java:1046)
    at javax.swing.JComponent.paintChildren(JComponent.java:870)
    at javax.swing.JComponent.paint(JComponent.java:1046)
    at javax.swing.JComponent.paintChildren(JComponent.java:870)
    at javax.swing.JComponent.paint(JComponent.java:1046)
    at javax.swing.JComponent.paintChildren(JComponent.java:870)
    at javax.swing.JComponent.paint(JComponent.java:1046)
    at javax.swing.JComponent.paintChildren(JComponent.java:870)
    at javax.swing.JComponent.paint(JComponent.java:1046)
    at javax.swing.JComponent.paintChildren(JComponent.java:870)
    at javax.swing.JComponent.paint(JComponent.java:1046)
    at javax.swing.JComponent.paintChildren(JComponent.java:870)
    at javax.swing.JComponent.paint(JComponent.java:1046)
    at javax.swing.JComponent.paintChildren(JComponent.java:870)
    at javax.swing.JComponent.paint(JComponent.java:1046)
    at javax.swing.JComponent.paintChildren(JComponent.java:870)
    at javax.swing.JComponent.paint(JComponent.java:1046)
    at javax.swing.JComponent.paintChildren(JComponent.java:870)
    at javax.swing.JComponent.paint(JComponent.java:1046)
    at javax.swing.JLayeredPane.paint(JLayeredPane.java:567)
    at javax.swing.JComponent.paintChildren(JComponent.java:870)
    at com.intellij.openapi.wm.impl.ToolWindowsPane.paintChildren(ToolWindowsPane.java:185)
    at javax.swing.JComponent.paint(JComponent.java:1046)
    at javax.swing.JLayeredPane.paint(JLayeredPane.java:567)
    at javax.swing.JComponent.paintChildren(JComponent.java:870)
    at javax.swing.JComponent.paint(JComponent.java:1046)
    at javax.swing.JComponent._paintImmediately(JComponent.java:5106)
    at javax.swing.JComponent.paintImmediately(JComponent.java:4890)
    at javax.swing.RepaintManager$3.run(RepaintManager.java:814)
    at javax.swing.RepaintManager$3.run(RepaintManager.java:802)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:802)
    at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:745)
    at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:725)
    at javax.swing.RepaintManager.access$1000(RepaintManager.java:46)
    at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1680)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:697)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

```

**Comment by danielcompton** [comment]
This still occurs in 0.1.58.
