### ISSUE TITLE
Exception when using quick definition on synthetic class

### ISSUE THREAD

**Issue by cursive-ghost** [cursive-ide/cursive#591]
```
Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
Details: Current thread: Thread[ApplicationImpl pooled thread 77,4,main] 1418922861
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-1 14.0#IU-139.222.5, eap:true,6,main] 1172865462
java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:126)
    at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1017)
    at com.intellij.psi.impl.source.tree.SharedImplUtil.getParent(SharedImplUtil.java:44)
    at com.intellij.psi.impl.source.tree.LeafPsiElement.getParent(LeafPsiElement.java:75)
    at cursive.psi.impl.synthetic.SyntheticClass.getDefiningElement(SyntheticClass.java:68)
    at plugin.intellij.class.proxy$cursive.psi.impl.synthetic.SyntheticClass$PsiQualifiedNamedElement$VarContainer$9e937acb.getDefiningElement(Unknown Source)
    at cursive.psi.impl.synthetic.SyntheticClass.getTextRange(SyntheticClass.java:38)
    at plugin.intellij.class.proxy$cursive.psi.impl.synthetic.SyntheticClass$PsiQualifiedNamedElement$VarContainer$9e937acb.getTextRange(Unknown Source)
    at com.intellij.codeInsight.navigation.ImplementationSearcher.searchImplementations(ImplementationSearcher.java:80)
    at com.intellij.codeInsight.hint.actions.ShowImplementationsAction.getSelfAndImplementations(ShowImplementationsAction.java:354)
    at com.intellij.codeInsight.hint.actions.ShowImplementationsAction.a(ShowImplementationsAction.java:346)
    at com.intellij.codeInsight.hint.actions.ShowImplementationsAction.access$500(ShowImplementationsAction.java:63)
    at com.intellij.codeInsight.hint.actions.ShowImplementationsAction$ImplementationsUpdaterTask.run(ShowImplementationsAction.java:461)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$TaskRunnable.run(ProgressManagerImpl.java:609)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$3.run(ProgressManagerImpl.java:194)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.a(ProgressManagerImpl.java:281)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:233)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:181)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$9.run(ProgressManagerImpl.java:518)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:405)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:695)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)

```

**Comment by blerou** [comment]
Same here. This happens when I try to load a file in the repl.

```
Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
Details: Current thread: Thread[pool-66-thread-2,5,main] 487698381
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0 14.1#IC-141.177.4, eap:false,6,main] 1437588025
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:982)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.getDocument(FileDocumentManagerImpl.java:169)
	at cursive.repl.actions$do_load_file_BANG_.invoke(actions.clj:257)
	at cursive.repl.actions$load_files_BANG_.invoke(actions.clj:305)
	at cursive.repl.actions$load_file_BANG_.invoke(actions.clj:338)
	at cursive.repl.actions$load_file$fn__8605.invoke(actions.clj:384)
	at cursive.repl.nrepl$submit$fn__3548.invoke(nrepl.clj:69)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by cursiveclojure** [comment]
@blerou Your issue is actually a different one - it's a 14.1 problem, fixed in the next build.
